/*
 * IFLL — Built-in Chinese-English Word Bank
 * ~280 carefully selected word pairs for immersive learning
 * Tags: all | daily | cet4 | cet6 | ielts | graduate
 */
const WORD_BANK = [
  /* ── Daily Life (日常) ── */
  { zh: '时间', en: 'time', def: 'the indefinite continued progress of existence', level: 'cet4', cat: 'daily' },
  { zh: '今天', en: 'today', def: 'on this present day', level: 'daily', cat: 'daily' },
  { zh: '明天', en: 'tomorrow', def: 'the day after today', level: 'daily', cat: 'daily' },
  { zh: '晚上', en: 'evening', def: 'the period of time at the end of the day', level: 'daily', cat: 'daily' },
  { zh: '早上', en: 'morning', def: 'the early part of the day', level: 'daily', cat: 'daily' },
  { zh: '工作', en: 'work', def: 'activity involving mental or physical effort', level: 'cet4', cat: 'daily' },
  { zh: '朋友', en: 'friend', def: 'a person with whom one has a bond of mutual affection', level: 'cet4', cat: 'daily' },
  { zh: '家庭', en: 'family', def: 'a group of parents and children living together', level: 'cet4', cat: 'daily' },
  { zh: '学校', en: 'school', def: 'an institution for educating children', level: 'cet4', cat: 'daily' },
  { zh: '生活', en: 'life', def: 'the condition of being alive', level: 'cet4', cat: 'daily' },
  { zh: '世界', en: 'world', def: 'the earth with all its countries and peoples', level: 'cet4', cat: 'daily' },
  { zh: '食物', en: 'food', def: 'any substance consumed for nutritional support', level: 'daily', cat: 'daily' },
  { zh: '健康', en: 'health', def: 'the state of being free from illness', level: 'cet4', cat: 'daily' },
  { zh: '身体', en: 'body', def: 'the physical structure of a person', level: 'cet4', cat: 'daily' },
  { zh: '孩子', en: 'child', def: 'a young human being', level: 'daily', cat: 'daily' },
  { zh: '父母', en: 'parent', def: 'a father or mother', level: 'daily', cat: 'daily' },
  { zh: '城市', en: 'city', def: 'a large town', level: 'cet4', cat: 'daily' },
  { zh: '地方', en: 'place', def: 'a particular position or area', level: 'cet4', cat: 'daily' },
  { zh: '事情', en: 'matter', def: 'an affair or situation under consideration', level: 'cet4', cat: 'daily' },
  { zh: '习惯', en: 'habit', def: 'a settled tendency of behavior', level: 'cet4', cat: 'daily' },
  { zh: '语言', en: 'language', def: 'a system of communication', level: 'cet4', cat: 'daily' },
  { zh: '梦想', en: 'dream', def: 'a cherished aspiration', level: 'cet4', cat: 'daily' },
  { zh: '游戏', en: 'game', def: 'an activity for amusement', level: 'daily', cat: 'daily' },
  { zh: '音乐', en: 'music', def: 'vocal or instrumental sounds combined', level: 'daily', cat: 'daily' },
  { zh: '电影', en: 'movie', def: 'a story recorded as a series of images', level: 'daily', cat: 'daily' },
  { zh: '照片', en: 'photo', def: 'a picture made using a camera', level: 'daily', cat: 'daily' },
  { zh: '天气', en: 'weather', def: 'the state of the atmosphere', level: 'daily', cat: 'daily' },
  { zh: '衣服', en: 'clothes', def: 'garments worn on the body', level: 'daily', cat: 'daily' },
  { zh: '颜色', en: 'color', def: 'the property of producing sensations on the eye', level: 'daily', cat: 'daily' },
  { zh: '电话', en: 'phone', def: 'a device for transmitting voice', level: 'daily', cat: 'daily' },
  { zh: '消息', en: 'message', def: 'a verbal or written communication', level: 'cet4', cat: 'daily' },
  { zh: '意思', en: 'meaning', def: 'what is intended to be expressed', level: 'cet4', cat: 'daily' },

  /* ── Abstract Concepts (抽象) ── */
  { zh: '问题', en: 'problem', def: 'a matter or situation regarded as unwelcome', level: 'cet4', cat: 'abstract' },
  { zh: '方法', en: 'method', def: 'a particular way of doing something', level: 'cet4', cat: 'abstract' },
  { zh: '结果', en: 'result', def: 'the outcome of an action or process', level: 'cet4', cat: 'abstract' },
  { zh: '原因', en: 'cause', def: 'a person or thing that gives rise to something', level: 'cet4', cat: 'abstract' },
  { zh: '目的', en: 'purpose', def: 'the reason for which something is done', level: 'cet4', cat: 'abstract' },
  { zh: '过程', en: 'process', def: 'a series of steps to achieve a result', level: 'cet4', cat: 'abstract' },
  { zh: '情况', en: 'situation', def: 'the set of circumstances at a given time', level: 'cet4', cat: 'abstract' },
  { zh: '关系', en: 'relation', def: 'the way things are connected', level: 'cet4', cat: 'abstract' },
  { zh: '条件', en: 'condition', def: 'a state of being or set of circumstances', level: 'cet4', cat: 'abstract' },
  { zh: '机会', en: 'opportunity', def: 'a set of circumstances making something possible', level: 'cet4', cat: 'abstract' },
  { zh: '能力', en: 'ability', def: 'possession of the means to do something', level: 'cet4', cat: 'abstract' },
  { zh: '态度', en: 'attitude', def: 'a settled way of thinking or feeling', level: 'cet4', cat: 'abstract' },
  { zh: '价值', en: 'value', def: 'the regard something is held to deserve', level: 'cet4', cat: 'abstract' },
  { zh: '方式', en: 'mode', def: 'a way in which something occurs', level: 'cet6', cat: 'abstract' },
  { zh: '本质', en: 'essence', def: 'the intrinsic nature of something', level: 'cet6', cat: 'abstract' },
  { zh: '特征', en: 'trait', def: 'a distinguishing quality or characteristic', level: 'cet6', cat: 'abstract' },
  { zh: '因素', en: 'factor', def: 'a circumstance that influences a result', level: 'cet4', cat: 'abstract' },
  { zh: '现象', en: 'phenomenon', def: 'a fact or event that can be observed', level: 'cet4', cat: 'abstract' },
  { zh: '经验', en: 'experience', def: 'practical contact with and observation of facts', level: 'cet4', cat: 'abstract' },
  { zh: '知识', en: 'knowledge', def: 'information gained through experience or education', level: 'cet4', cat: 'abstract' },
  { zh: '概念', en: 'concept', def: 'an abstract idea or notion', level: 'cet4', cat: 'abstract' },
  { zh: '意识', en: 'awareness', def: 'knowledge or perception of a situation', level: 'cet4', cat: 'abstract' },
  { zh: '记忆', en: 'memory', def: 'the faculty of storing and recalling past experiences', level: 'cet4', cat: 'abstract' },
  { zh: '印象', en: 'impression', def: 'a feeling or understanding about someone or something', level: 'cet4', cat: 'abstract' },
  { zh: '想象', en: 'imagination', def: 'the ability to form new ideas and images', level: 'cet4', cat: 'abstract' },
  { zh: '现实', en: 'reality', def: 'the state of things as they actually exist', level: 'cet4', cat: 'abstract' },
  { zh: '未来', en: 'future', def: 'the time yet to come', level: 'cet4', cat: 'abstract' },
  { zh: '传统', en: 'tradition', def: 'a long-established custom or belief', level: 'cet4', cat: 'abstract' },
  { zh: '文化', en: 'culture', def: 'the customs and beliefs of a particular group', level: 'cet4', cat: 'abstract' },
  { zh: '社会', en: 'society', def: 'the community of people living together', level: 'cet4', cat: 'abstract' },

  /* ── Action Verbs (动作) ── */
  { zh: '需要', en: 'require', def: 'to need for a particular purpose', level: 'cet4', cat: 'verb' },
  { zh: '包括', en: 'include', def: 'to contain as part of a whole', level: 'cet4', cat: 'verb' },
  { zh: '提供', en: 'provide', def: 'to make available for use', level: 'cet4', cat: 'verb' },
  { zh: '使用', en: 'use', def: 'to take or employ for a purpose', level: 'cet4', cat: 'verb' },
  { zh: '考虑', en: 'consider', def: 'to think about carefully', level: 'cet4', cat: 'verb' },
  { zh: '表示', en: 'indicate', def: 'to point out or show', level: 'cet4', cat: 'verb' },
  { zh: '存在', en: 'exist', def: 'to have objective reality', level: 'cet4', cat: 'verb' },
  { zh: '产生', en: 'generate', def: 'to bring into existence', level: 'cet4', cat: 'verb' },
  { zh: '影响', en: 'affect', def: 'to have an effect on', level: 'cet4', cat: 'verb' },
  { zh: '支持', en: 'support', def: 'to bear all or part of the weight of', level: 'cet4', cat: 'verb' },
  { zh: '发展', en: 'develop', def: 'to grow or cause to grow', level: 'cet4', cat: 'verb' },
  { zh: '改变', en: 'change', def: 'to make or become different', level: 'cet4', cat: 'verb' },
  { zh: '增加', en: 'increase', def: 'to become greater in size or amount', level: 'cet4', cat: 'verb' },
  { zh: '减少', en: 'reduce', def: 'to make smaller or less', level: 'cet4', cat: 'verb' },
  { zh: '保持', en: 'maintain', def: 'to cause to continue', level: 'cet4', cat: 'verb' },
  { zh: '实现', en: 'achieve', def: 'to successfully reach a goal', level: 'cet4', cat: 'verb' },
  { zh: '选择', en: 'choose', def: 'to pick out or select', level: 'cet4', cat: 'verb' },
  { zh: '决定', en: 'decide', def: 'to make a choice', level: 'cet4', cat: 'verb' },
  { zh: '开始', en: 'start', def: 'to begin or commence', level: 'cet4', cat: 'verb' },
  { zh: '完成', en: 'complete', def: 'to finish making or doing', level: 'cet4', cat: 'verb' },
  { zh: '继续', en: 'continue', def: 'to keep doing something', level: 'cet4', cat: 'verb' },
  { zh: '建立', en: 'establish', def: 'to set up on a firm basis', level: 'cet4', cat: 'verb' },
  { zh: '提高', en: 'improve', def: 'to make or become better', level: 'cet4', cat: 'verb' },
  { zh: '确认', en: 'confirm', def: 'to establish the truth of', level: 'cet4', cat: 'verb' },
  { zh: '分析', en: 'analyze', def: 'to examine in detail', level: 'cet4', cat: 'verb' },
  { zh: '比较', en: 'compare', def: 'to examine for similarities and differences', level: 'cet4', cat: 'verb' },
  { zh: '解释', en: 'explain', def: 'to make clear or understandable', level: 'cet4', cat: 'verb' },
  { zh: '讨论', en: 'discuss', def: 'to talk about in detail', level: 'cet4', cat: 'verb' },
  { zh: '接受', en: 'accept', def: 'to willingly receive', level: 'cet4', cat: 'verb' },
  { zh: '拒绝', en: 'refuse', def: 'to indicate unwillingness to do', level: 'cet4', cat: 'verb' },

  /* ── Quality / Adjectives (性质/形容词) ── */
  { zh: '重要', en: 'important', def: 'of great significance or value', level: 'cet4', cat: 'adj' },
  { zh: '主要', en: 'main', def: 'chief in size or importance', level: 'cet4', cat: 'adj' },
  { zh: '基本', en: 'basic', def: 'forming an essential foundation', level: 'cet4', cat: 'adj' },
  { zh: '完全', en: 'complete', def: 'having all parts or elements', level: 'cet4', cat: 'adj' },
  { zh: '具体', en: 'specific', def: 'clearly defined or identified', level: 'cet4', cat: 'adj' },
  { zh: '直接', en: 'direct', def: 'without intervening factors', level: 'cet4', cat: 'adj' },
  { zh: '普遍', en: 'common', def: 'occurring or appearing frequently', level: 'cet4', cat: 'adj' },
  { zh: '明显', en: 'obvious', def: 'easily perceived or understood', level: 'cet4', cat: 'adj' },
  { zh: '复杂', en: 'complex', def: 'consisting of many interconnected parts', level: 'cet4', cat: 'adj' },
  { zh: '简单', en: 'simple', def: 'easily understood or done', level: 'cet4', cat: 'adj' },
  { zh: '有效', en: 'valid', def: 'having a sound basis in logic or fact', level: 'cet4', cat: 'adj' },
  { zh: '有利', en: 'favorable', def: 'expressing approval or support', level: 'cet6', cat: 'adj' },
  { zh: '困难', en: 'difficult', def: 'needing much effort or skill', level: 'cet4', cat: 'adj' },
  { zh: '容易', en: 'easy', def: 'achieved without great effort', level: 'cet4', cat: 'adj' },
  { zh: '安全', en: 'safe', def: 'free from danger or risk', level: 'cet4', cat: 'adj' },
  { zh: '危险', en: 'dangerous', def: 'likely to cause harm or injury', level: 'cet4', cat: 'adj' },
  { zh: '正确', en: 'correct', def: 'free from error; true', level: 'cet4', cat: 'adj' },
  { zh: '错误', en: 'wrong', def: 'not correct or true', level: 'cet4', cat: 'adj' },
  { zh: '可能', en: 'possible', def: 'able to be done or achieved', level: 'cet4', cat: 'adj' },
  { zh: '必要', en: 'necessary', def: 'required to be done or achieved', level: 'cet4', cat: 'adj' },
  { zh: '适当', en: 'proper', def: 'suitable for a particular purpose', level: 'cet4', cat: 'adj' },
  { zh: '独立', en: 'independent', def: 'free from outside control', level: 'cet4', cat: 'adj' },
  { zh: '积极', en: 'active', def: 'engaging in physical movement or activity', level: 'cet4', cat: 'adj' },
  { zh: '消极', en: 'passive', def: 'accepting without active response', level: 'cet6', cat: 'adj' },
  { zh: '临时', en: 'temporary', def: 'lasting for a limited time', level: 'cet4', cat: 'adj' },
  { zh: '长期', en: 'long-term', def: 'extending over a long time', level: 'cet4', cat: 'adj' },
  { zh: '专业', en: 'professional', def: 'relating to a particular profession', level: 'cet4', cat: 'adj' },
  { zh: '全面', en: 'comprehensive', def: 'including all elements or aspects', level: 'cet4', cat: 'adj' },
  { zh: '敏感', en: 'sensitive', def: 'quick to detect or respond', level: 'cet4', cat: 'adj' },
  { zh: '严格', en: 'strict', def: 'demanding that rules are obeyed', level: 'cet4', cat: 'adj' },

  /* ── Time / Sequence (时间/顺序) ── */
  { zh: '目前', en: 'currently', def: 'at the present moment', level: 'cet4', cat: 'time' },
  { zh: '当前', en: 'present', def: 'existing or occurring now', level: 'cet4', cat: 'time' },
  { zh: '之前', en: 'before', def: 'during the period of time preceding', level: 'cet4', cat: 'time' },
  { zh: '之后', en: 'after', def: 'in the time following', level: 'cet4', cat: 'time' },
  { zh: '首先', en: 'firstly', def: 'in the first place', level: 'cet4', cat: 'time' },
  { zh: '最后', en: 'finally', def: 'at or in the end', level: 'cet4', cat: 'time' },
  { zh: '同时', en: 'meanwhile', def: 'at the same time', level: 'cet4', cat: 'time' },
  { zh: '立即', en: 'immediately', def: 'without any delay', level: 'cet4', cat: 'time' },
  { zh: '最终', en: 'eventually', def: 'in the end', level: 'cet4', cat: 'time' },
  { zh: '逐渐', en: 'gradually', def: 'in a gradual way; slowly', level: 'cet4', cat: 'time' },
  { zh: '始终', en: 'always', def: 'at all times', level: 'cet4', cat: 'time' },
  { zh: '曾经', en: 'once', def: 'at some time in the past', level: 'cet4', cat: 'time' },
  { zh: '原本', en: 'originally', def: 'from the beginning', level: 'cet6', cat: 'time' },
  { zh: '即将', en: 'upcoming', def: 'about to happen', level: 'cet4', cat: 'time' },
  { zh: '最近', en: 'recently', def: 'not long ago', level: 'cet4', cat: 'time' },
  { zh: '期间', en: 'during', def: 'throughout the course of', level: 'cet4', cat: 'time' },
  { zh: '阶段', en: 'stage', def: 'a period or step in a process', level: 'cet4', cat: 'time' },
  { zh: '时刻', en: 'moment', def: 'a brief period of time', level: 'cet4', cat: 'time' },
  { zh: '频率', en: 'frequency', def: 'the rate at which something occurs', level: 'cet4', cat: 'time' },
  { zh: '期限', en: 'deadline', def: 'the latest time for something', level: 'cet4', cat: 'time' },

  /* ── Technology (技术) ── */
  { zh: '系统', en: 'system', def: 'a set of connected parts forming a complex whole', level: 'cet4', cat: 'tech' },
  { zh: '网络', en: 'network', def: 'a group of interconnected things', level: 'cet4', cat: 'tech' },
  { zh: '数据', en: 'data', def: 'facts and statistics collected together', level: 'cet4', cat: 'tech' },
  { zh: '程序', en: 'program', def: 'a set of coded instructions for a computer', level: 'cet4', cat: 'tech' },
  { zh: '功能', en: 'feature', def: 'a distinctive attribute or capability', level: 'cet4', cat: 'tech' },
  { zh: '选项', en: 'option', def: 'a thing that may be chosen', level: 'cet4', cat: 'tech' },
  { zh: '设置', en: 'setting', def: 'the way something is configured', level: 'cet4', cat: 'tech' },
  { zh: '版本', en: 'version', def: 'a particular form of something', level: 'cet4', cat: 'tech' },
  { zh: '文档', en: 'document', def: 'a piece of written or electronic text', level: 'cet4', cat: 'tech' },
  { zh: '链接', en: 'link', def: 'a reference to another resource', level: 'cet4', cat: 'tech' },
  { zh: '文件', en: 'file', def: 'a collection of data treated as a unit', level: 'cet4', cat: 'tech' },
  { zh: '资源', en: 'resource', def: 'a supply that can be drawn on', level: 'cet4', cat: 'tech' },
  { zh: '工具', en: 'tool', def: 'a device used to carry out a function', level: 'cet4', cat: 'tech' },
  { zh: '平台', en: 'platform', def: 'a place for development or operation', level: 'cet4', cat: 'tech' },
  { zh: '应用', en: 'application', def: 'a program designed for end users', level: 'cet4', cat: 'tech' },
  { zh: '界面', en: 'interface', def: 'a point of interaction with a system', level: 'cet4', cat: 'tech' },
  { zh: '数据库', en: 'database', def: 'a structured set of data held in a computer', level: 'cet4', cat: 'tech' },
  { zh: '服务器', en: 'server', def: 'a computer serving other computers', level: 'cet4', cat: 'tech' },
  { zh: '客户端', en: 'client', def: 'a computer accessing a server', level: 'cet4', cat: 'tech' },
  { zh: '加密', en: 'encryption', def: 'the process of encoding information', level: 'cet6', cat: 'tech' },
  { zh: '协议', en: 'protocol', def: 'a set of rules for data exchange', level: 'cet6', cat: 'tech' },
  { zh: '缓存', en: 'cache', def: 'a storage layer for faster access', level: 'cet6', cat: 'tech' },
  { zh: '备份', en: 'backup', def: 'a copy of data for recovery', level: 'cet4', cat: 'tech' },
  { zh: '错误', en: 'error', def: 'a mistake or fault in operation', level: 'cet4', cat: 'tech' },

  /* ── Academic / Formal (学术/书面) ── */
  { zh: '研究', en: 'research', def: 'systematic investigation to establish facts', level: 'cet4', cat: 'academic' },
  { zh: '分析', en: 'analysis', def: 'detailed examination of the elements of something', level: 'cet4', cat: 'academic' },
  { zh: '理论', en: 'theory', def: 'a system of ideas explaining something', level: 'cet4', cat: 'academic' },
  { zh: '实践', en: 'practice', def: 'the actual application of an idea', level: 'cet4', cat: 'academic' },
  { zh: '标准', en: 'standard', def: 'a level of quality or attainment', level: 'cet4', cat: 'academic' },
  { zh: '范围', en: 'range', def: 'the area covered or included', level: 'cet4', cat: 'academic' },
  { zh: '比例', en: 'ratio', def: 'the relative size of two quantities', level: 'cet4', cat: 'academic' },
  { zh: '效率', en: 'efficiency', def: 'the state of achieving maximum productivity', level: 'cet4', cat: 'academic' },
  { zh: '质量', en: 'quality', def: 'the standard of something as measured', level: 'cet4', cat: 'academic' },
  { zh: '数量', en: 'quantity', def: 'the amount of something', level: 'cet4', cat: 'academic' },
  { zh: '趋势', en: 'trend', def: 'a general direction in which something develops', level: 'cet4', cat: 'academic' },
  { zh: '结构', en: 'structure', def: 'the arrangement of parts in something', level: 'cet4', cat: 'academic' },
  { zh: '功能', en: 'function', def: 'a special activity or purpose', level: 'cet4', cat: 'academic' },
  { zh: '数据', en: 'statistics', def: 'the collection and analysis of numerical data', level: 'cet6', cat: 'academic' },
  { zh: '策略', en: 'strategy', def: 'a plan to achieve a long-term goal', level: 'cet4', cat: 'academic' },
  { zh: '方案', en: 'scheme', def: 'a systematic plan of action', level: 'cet4', cat: 'academic' },
  { zh: '指标', en: 'indicator', def: 'a thing that indicates a state or level', level: 'cet6', cat: 'academic' },
  { zh: '维度', en: 'dimension', def: 'an aspect or feature of a situation', level: 'cet6', cat: 'academic' },
  { zh: '内容', en: 'content', def: 'the material dealt with in a work', level: 'cet4', cat: 'academic' },
  { zh: '背景', en: 'background', def: 'the circumstances surrounding an event', level: 'cet4', cat: 'academic' },
  { zh: '结论', en: 'conclusion', def: 'a judgment reached by reasoning', level: 'cet4', cat: 'academic' },
  { zh: '依据', en: 'basis', def: 'the underlying foundation for an idea', level: 'cet4', cat: 'academic' },
  { zh: '角度', en: 'perspective', def: 'a particular way of viewing things', level: 'cet4', cat: 'academic' },
  { zh: '目标', en: 'goal', def: 'the object of ambition or effort', level: 'cet4', cat: 'academic' },
  { zh: '风险', en: 'risk', def: 'the possibility of loss or injury', level: 'cet4', cat: 'academic' },
  { zh: '收益', en: 'benefit', def: 'a helpful or good effect', level: 'cet4', cat: 'academic' },
  { zh: '成本', en: 'cost', def: 'the price paid to acquire something', level: 'cet4', cat: 'academic' },
  { zh: '预算', en: 'budget', def: 'an estimate of income and expenditure', level: 'cet4', cat: 'academic' },
  { zh: '投资', en: 'investment', def: 'the act of investing money for profit', level: 'cet4', cat: 'academic' },
  { zh: '管理', en: 'management', def: 'the process of dealing with or controlling', level: 'cet4', cat: 'academic' },

  /* ── Conjunction / Logic (连接/逻辑) ── */
  { zh: '因此', en: 'therefore', def: 'for that reason', level: 'cet4', cat: 'logic' },
  { zh: '然而', en: 'however', def: 'used to introduce a contrasting point', level: 'cet4', cat: 'logic' },
  { zh: '尽管', en: 'although', def: 'in spite of the fact that', level: 'cet4', cat: 'logic' },
  { zh: '因为', en: 'because', def: 'for the reason that', level: 'cet4', cat: 'logic' },
  { zh: '所以', en: 'so', def: 'for that reason', level: 'cet4', cat: 'logic' },
  { zh: '但是', en: 'but', def: 'used to introduce a difference', level: 'cet4', cat: 'logic' },
  { zh: '如果', en: 'if', def: 'on the condition that', level: 'cet4', cat: 'logic' },
  { zh: '而且', en: 'moreover', def: 'as a further matter', level: 'cet4', cat: 'logic' },
  { zh: '不仅', en: 'not-only', def: 'not just one thing but also another', level: 'cet4', cat: 'logic' },
  { zh: '或者', en: 'or', def: 'used to link alternatives', level: 'cet4', cat: 'logic' },
  { zh: '另外', en: 'furthermore', def: 'in addition to what has been said', level: 'cet4', cat: 'logic' },
  { zh: '总之', en: 'overall', def: 'taking everything into account', level: 'cet4', cat: 'logic' },
  { zh: '由于', en: 'due-to', def: 'because of', level: 'cet4', cat: 'logic' },
  { zh: '除非', en: 'unless', def: 'except on the condition that', level: 'cet4', cat: 'logic' },
  { zh: '虽然', en: 'though', def: 'despite the fact that', level: 'cet4', cat: 'logic' },

  /* ── Adverb / Degree (副词/程度) ── */
  { zh: '非常', en: 'very', def: 'to a high degree', level: 'cet4', cat: 'adverb' },
  { zh: '特别', en: 'especially', def: 'in particular', level: 'cet4', cat: 'adverb' },
  { zh: '相对', en: 'relatively', def: 'in comparison to something else', level: 'cet4', cat: 'adverb' },
  { zh: '相当', en: 'quite', def: 'to a moderate or significant extent', level: 'cet4', cat: 'adverb' },
  { zh: '比较', en: 'fairly', def: 'to a moderate degree', level: 'cet4', cat: 'adverb' },
  { zh: '稍微', en: 'slightly', def: 'to a small extent', level: 'cet4', cat: 'adverb' },
  { zh: '完全', en: 'totally', def: 'completely; entirely', level: 'cet4', cat: 'adverb' },
  { zh: '几乎', en: 'almost', def: 'not quite; very nearly', level: 'cet4', cat: 'adverb' },
  { zh: '大约', en: 'approximately', def: 'roughly; about', level: 'cet4', cat: 'adverb' },
  { zh: '仅仅', en: 'merely', def: 'only; just', level: 'cet4', cat: 'adverb' },
  { zh: '至少', en: 'at-least', def: 'not less than', level: 'cet4', cat: 'adverb' },
  { zh: '仍然', en: 'still', def: 'up to the present time', level: 'cet4', cat: 'adverb' },
  { zh: '已经', en: 'already', def: 'before the time in question', level: 'cet4', cat: 'adverb' },
  { zh: '刚刚', en: 'just', def: 'a very short time ago', level: 'cet4', cat: 'adverb' },
  { zh: '从来', en: 'never', def: 'at no time in the past or future', level: 'cet4', cat: 'adverb' },
  { zh: '反复', en: 'repeatedly', def: 'over and over again', level: 'cet4', cat: 'adverb' },
  { zh: '通常', en: 'usually', def: 'under normal conditions', level: 'cet4', cat: 'adverb' },
  { zh: '实际', en: 'actually', def: 'as a matter of fact', level: 'cet4', cat: 'adverb' },
  { zh: '基本上', en: 'basically', def: 'in the most essential respects', level: 'cet4', cat: 'adverb' },
  { zh: '也许', en: 'perhaps', def: 'used to express possibility', level: 'cet4', cat: 'adverb' },

  /* ── 100 Additional High-Frequency Cet-4 Words ── */
  { zh: '行动', en: 'action', def: 'the process of doing something', level: 'cet4', cat: 'verb' },
  { zh: '反应', en: 'reaction', def: 'a response to something', level: 'cet4', cat: 'abstract' },
  { zh: '建议', en: 'suggestion', def: 'an idea put forward for consideration', level: 'cet4', cat: 'verb' },
  { zh: '计划', en: 'plan', def: 'a detailed proposal for doing something', level: 'cet4', cat: 'abstract' },
  { zh: '项目', en: 'project', def: 'a planned piece of work', level: 'cet4', cat: 'abstract' },
  { zh: '任务', en: 'task', def: 'a piece of work to be done', level: 'cet4', cat: 'abstract' },
  { zh: '订单', en: 'order', def: 'a request for something to be supplied', level: 'cet4', cat: 'daily' },
  { zh: '账户', en: 'account', def: 'an arrangement with a bank to deposit money', level: 'cet4', cat: 'daily' },
  { zh: '密码', en: 'password', def: 'a secret word for authentication', level: 'cet4', cat: 'tech' },
  { zh: '安全', en: 'security', def: 'the state of being protected', level: 'cet4', cat: 'abstract' },
  { zh: '保护', en: 'protect', def: 'to keep safe from harm', level: 'cet4', cat: 'verb' },
  { zh: '连接', en: 'connect', def: 'to link or join together', level: 'cet4', cat: 'verb' },
  { zh: '传输', en: 'transfer', def: 'to move from one place to another', level: 'cet4', cat: 'verb' },
  { zh: '操作', en: 'operate', def: 'to control the functioning of', level: 'cet4', cat: 'verb' },
  { zh: '控制', en: 'control', def: 'the power to influence behavior', level: 'cet4', cat: 'verb' },
  { zh: '检查', en: 'check', def: 'to examine for accuracy or quality', level: 'cet4', cat: 'verb' },
  { zh: '处理', en: 'process', def: 'to deal with systematically', level: 'cet4', cat: 'verb' },
  { zh: '收集', en: 'collect', def: 'to gather together', level: 'cet4', cat: 'verb' },
  { zh: '发布', en: 'release', def: 'to make something available', level: 'cet4', cat: 'verb' },
  { zh: '更新', en: 'update', def: 'to make more modern or current', level: 'cet4', cat: 'verb' },
  { zh: '限制', en: 'limit', def: 'a point beyond which something cannot go', level: 'cet4', cat: 'verb' },
  { zh: '申请', en: 'apply', def: 'to make a formal request', level: 'cet4', cat: 'verb' },
  { zh: '注册', en: 'register', def: 'to record in a list', level: 'cet4', cat: 'verb' },
  { zh: '登录', en: 'login', def: 'to gain access to a system', level: 'cet4', cat: 'verb' },
  { zh: '搜索', en: 'search', def: 'to try to find something', level: 'cet4', cat: 'verb' },
  { zh: '浏览', en: 'browse', def: 'to look through casually', level: 'cet4', cat: 'verb' },
  { zh: '下载', en: 'download', def: 'to copy data from one system to another', level: 'cet4', cat: 'verb' },
  { zh: '上传', en: 'upload', def: 'to transfer data to a larger system', level: 'cet4', cat: 'verb' },
  { zh: '显示', en: 'display', def: 'to make visible', level: 'cet4', cat: 'verb' },
  { zh: '输入', en: 'input', def: 'to put data into a computer', level: 'cet4', cat: 'verb' },
  { zh: '输出', en: 'output', def: 'data produced by a computer', level: 'cet4', cat: 'verb' },
  { zh: '编辑', en: 'edit', def: 'to prepare written material for publication', level: 'cet4', cat: 'verb' },
  { zh: '测试', en: 'test', def: 'a procedure to evaluate something', level: 'cet4', cat: 'verb' },
  { zh: '设计', en: 'design', def: 'a plan or drawing produced for creation', level: 'cet4', cat: 'verb' },
  { zh: '开发', en: 'develop', def: 'to create or improve gradually', level: 'cet4', cat: 'verb' },
  { zh: '部署', en: 'deploy', def: 'to bring into effective action', level: 'cet6', cat: 'verb' },
  { zh: '升级', en: 'upgrade', def: 'to raise to a higher standard', level: 'cet4', cat: 'verb' },
  { zh: '优化', en: 'optimize', def: 'to make the best use of', level: 'cet6', cat: 'verb' },
  { zh: '调整', en: 'adjust', def: 'to alter slightly for a better fit', level: 'cet4', cat: 'verb' },
  { zh: '恢复', en: 'recover', def: 'to return to a normal state', level: 'cet4', cat: 'verb' },
  { zh: '取消', en: 'cancel', def: 'to decide an event will not take place', level: 'cet4', cat: 'verb' },
  { zh: '参与', en: 'participate', def: 'to take part in', level: 'cet4', cat: 'verb' },
  { zh: '承诺', en: 'promise', def: 'to assure that one will do something', level: 'cet4', cat: 'verb' },
  { zh: '保证', en: 'guarantee', def: 'a formal assurance of quality', level: 'cet4', cat: 'verb' },
  { zh: '尊重', en: 'respect', def: 'to admire deeply as a result of qualities', level: 'cet4', cat: 'verb' },
  { zh: '信任', en: 'trust', def: 'firm belief in the reliability of someone', level: 'cet4', cat: 'abstract' },
  { zh: '感谢', en: 'appreciate', def: 'to recognize the value of', level: 'cet4', cat: 'verb' },
  { zh: '合作', en: 'cooperate', def: 'to work jointly towards a common end', level: 'cet4', cat: 'verb' },
  { zh: '沟通', en: 'communicate', def: 'to share or exchange information', level: 'cet4', cat: 'verb' },
  { zh: '理解', en: 'understand', def: 'to perceive the meaning of', level: 'cet4', cat: 'verb' },
  { zh: '记忆', en: 'memorize', def: 'to commit to memory', level: 'cet4', cat: 'verb' },
  { zh: '练习', en: 'practice', def: 'repeated exercise to acquire skill', level: 'cet4', cat: 'verb' },
  { zh: '准备', en: 'prepare', def: 'to make ready for use', level: 'cet4', cat: 'verb' },
  { zh: '分享', en: 'share', def: 'to have or use jointly', level: 'cet4', cat: 'verb' },
  { zh: '收藏', en: 'collect', def: 'to accumulate for preservation', level: 'cet4', cat: 'verb' },
  { zh: '关注', en: 'follow', def: 'to pay attention to', level: 'cet4', cat: 'verb' },
  { zh: '推荐', en: 'recommend', def: 'to suggest as being good', level: 'cet4', cat: 'verb' },
  { zh: '反馈', en: 'feedback', def: 'information about a product etc.', level: 'cet4', cat: 'abstract' },
  { zh: '通知', en: 'notify', def: 'to inform formally', level: 'cet4', cat: 'verb' },
  { zh: '关注', en: 'concern', def: 'a matter of interest or importance', level: 'cet6', cat: 'abstract' },
  { zh: '活力', en: 'energy', def: 'the capacity for doing work', level: 'cet4', cat: 'abstract' },
  { zh: '潜力', en: 'potential', def: 'latent qualities that may be developed', level: 'cet4', cat: 'abstract' },
  { zh: '挑战', en: 'challenge', def: 'a summons to a contest of skill', level: 'cet4', cat: 'abstract' },
  { zh: '困境', en: 'dilemma', def: 'a situation requiring a difficult choice', level: 'cet6', cat: 'abstract' },
  { zh: '矛盾', en: 'conflict', def: 'a serious disagreement', level: 'cet4', cat: 'abstract' },
  { zh: '平衡', en: 'balance', def: 'an even distribution of weight', level: 'cet4', cat: 'abstract' },
  { zh: '压力', en: 'pressure', def: 'a feeling of stressful urgency', level: 'cet4', cat: 'abstract' },
  { zh: '动力', en: 'motivation', def: 'a reason to act in a certain way', level: 'cet4', cat: 'abstract' },
  { zh: '灵感', en: 'inspiration', def: 'the process of being mentally stimulated', level: 'cet4', cat: 'abstract' },
  { zh: '好奇', en: 'curiosity', def: 'a strong desire to know', level: 'cet4', cat: 'abstract' },
  { zh: '耐心', en: 'patience', def: 'the capacity to accept delay', level: 'cet4', cat: 'abstract' },
  { zh: '勇气', en: 'courage', def: 'the ability to do something difficult', level: 'cet4', cat: 'abstract' },
  { zh: '自信', en: 'confidence', def: 'a feeling of self-assurance', level: 'cet4', cat: 'abstract' },
  { zh: '责任', en: 'responsibility', def: 'the state of being accountable', level: 'cet4', cat: 'abstract' },
  { zh: '纪律', en: 'discipline', def: 'the practice of training to obey rules', level: 'cet4', cat: 'abstract' },
  { zh: '自由', en: 'freedom', def: 'the power to act as one wants', level: 'cet4', cat: 'abstract' },
  { zh: '公平', en: 'fairness', def: 'impartial and just treatment', level: 'cet4', cat: 'abstract' },
  { zh: '平等', en: 'equality', def: 'the state of being equal', level: 'cet4', cat: 'abstract' },
  { zh: '正义', en: 'justice', def: 'just behavior or treatment', level: 'cet4', cat: 'abstract' },
  { zh: '繁荣', en: 'prosperity', def: 'the state of being prosperous', level: 'cet4', cat: 'abstract' },
  { zh: '危机', en: 'crisis', def: 'a time of intense difficulty', level: 'cet4', cat: 'abstract' },
  { zh: '灾难', en: 'disaster', def: 'a sudden calamitous event', level: 'cet4', cat: 'abstract' },
  { zh: '冲突', en: 'clash', def: 'a violent confrontation', level: 'cet6', cat: 'abstract' },
  { zh: '谈判', en: 'negotiate', def: 'to discuss to reach an agreement', level: 'cet4', cat: 'verb' },
  { zh: '妥协', en: 'compromise', def: 'to settle differences by mutual concession', level: 'cet4', cat: 'verb' },
  { zh: '改革', en: 'reform', def: 'to make changes for improvement', level: 'cet4', cat: 'verb' },
  { zh: '创新', en: 'innovate', def: 'to introduce something new', level: 'cet4', cat: 'verb' },
  { zh: '竞争', en: 'compete', def: 'to strive to gain or win something', level: 'cet4', cat: 'verb' },
  { zh: '批评', en: 'criticize', def: 'to indicate faults in a disapproving way', level: 'cet4', cat: 'verb' },
  { zh: '表扬', en: 'praise', def: 'to express warm approval', level: 'cet4', cat: 'verb' },
  { zh: '庆祝', en: 'celebrate', def: 'to mark a special day with festivities', level: 'cet4', cat: 'verb' },
  { zh: '旅行', en: 'travel', def: 'to make a journey', level: 'cet4', cat: 'verb' },
  { zh: '运动', en: 'exercise', def: 'physical activity for health', level: 'cet4', cat: 'verb' },
  { zh: '休息', en: 'rest', def: 'to cease work to recover strength', level: 'cet4', cat: 'verb' },
  { zh: '睡眠', en: 'sleep', def: 'a natural periodic state of rest', level: 'cet4', cat: 'daily' },
  { zh: '学习', en: 'study', def: 'the devotion of time to acquiring knowledge', level: 'cet4', cat: 'verb' },
  { zh: '思考', en: 'think', def: 'to form thoughts in the mind', level: 'cet4', cat: 'verb' },
  { zh: '相信', en: 'believe', def: 'to accept as true', level: 'cet4', cat: 'verb' },
  { zh: '感觉', en: 'feel', def: 'to be aware of through touch or emotion', level: 'cet4', cat: 'verb' },
  { zh: '期望', en: 'expect', def: 'to regard as likely to happen', level: 'cet4', cat: 'verb' },
  { zh: '回忆', en: 'recall', def: 'to bring a memory into the mind', level: 'cet4', cat: 'verb' },
  { zh: '忽略', en: 'ignore', def: 'to refuse to take notice of', level: 'cet4', cat: 'verb' },
  { zh: '避免', en: 'avoid', def: 'to keep away from', level: 'cet4', cat: 'verb' },
  { zh: '承认', en: 'admit', def: 'to confess to be true', level: 'cet4', cat: 'verb' },
  { zh: '坚持', en: 'persist', def: 'to continue firmly in a course of action', level: 'cet4', cat: 'verb' },
  { zh: '放弃', en: 'give-up', def: 'to stop making an effort', level: 'cet4', cat: 'verb' },
  { zh: '获得', en: 'gain', def: 'to obtain or secure something', level: 'cet4', cat: 'verb' },
  { zh: '失去', en: 'lose', def: 'to be deprived of', level: 'cet4', cat: 'verb' },
  { zh: '加入', en: 'join', def: 'to become a member of', level: 'cet4', cat: 'verb' },
  { zh: '离开', en: 'leave', def: 'to go away from', level: 'cet4', cat: 'verb' },
  { zh: '到达', en: 'arrive', def: 'to reach a destination', level: 'cet4', cat: 'verb' },
  { zh: '跟随', en: 'follow', def: 'to come after in time or order', level: 'cet4', cat: 'verb' },
  { zh: '表达', en: 'express', def: 'to convey a thought or feeling', level: 'cet4', cat: 'verb' },
  { zh: '描述', en: 'describe', def: 'to give an account of', level: 'cet4', cat: 'verb' },
  { zh: '总结', en: 'summarize', def: 'to give a brief statement of main points', level: 'cet4', cat: 'verb' },
  { zh: '预测', en: 'predict', def: 'to say something will happen in the future', level: 'cet4', cat: 'verb' },
  { zh: '假设', en: 'assume', def: 'to suppose to be the case without proof', level: 'cet4', cat: 'verb' },
  { zh: '证明', en: 'prove', def: 'to demonstrate the truth of', level: 'cet4', cat: 'verb' },
  { zh: '观察', en: 'observe', def: 'to watch carefully', level: 'cet4', cat: 'verb' },
  { zh: '反映', en: 'reflect', def: 'to show or represent', level: 'cet4', cat: 'verb' },
  { zh: '符合', en: 'satisfy', def: 'to meet the expectations or requirements', level: 'cet4', cat: 'verb' },
  { zh: '超过', en: 'exceed', def: 'to be greater than', level: 'cet4', cat: 'verb' },
  { zh: '组成', en: 'compose', def: 'to make up the whole', level: 'cet4', cat: 'verb' },
  { zh: '涉及', en: 'involve', def: 'to include as a necessary part', level: 'cet4', cat: 'verb' },
  { zh: '代表', en: 'represent', def: 'to act on behalf of', level: 'cet4', cat: 'verb' },
  { zh: '属于', en: 'belong', def: 'to be the property of', level: 'cet4', cat: 'verb' },
  { zh: '依赖', en: 'depend', def: 'to be reliant on', level: 'cet4', cat: 'verb' },
  { zh: '反对', en: 'oppose', def: 'to be against', level: 'cet4', cat: 'verb' },
  { zh: '赞扬', en: 'praise', def: 'to express approval', level: 'cet4', cat: 'verb' },
  { zh: '惩罚', en: 'punish', def: 'to inflict a penalty on', level: 'cet4', cat: 'verb' },
  { zh: '奖励', en: 'reward', def: 'to give something in recognition of service', level: 'cet4', cat: 'verb' },
  { zh: '贡献', en: 'contribute', def: 'to give towards a common purpose', level: 'cet4', cat: 'verb' },
  { zh: '领导', en: 'lead', def: 'to guide in a direction', level: 'cet4', cat: 'verb' },
  { zh: '管理', en: 'administer', def: 'to manage the running of', level: 'cet6', cat: 'verb' },
  { zh: '组织', en: 'organize', def: 'to arrange systematically', level: 'cet4', cat: 'verb' },
  { zh: '创办', en: 'found', def: 'to establish an institution', level: 'cet4', cat: 'verb' },
  { zh: '实施', en: 'implement', def: 'to put a plan into effect', level: 'cet4', cat: 'verb' },
  { zh: '执行', en: 'execute', def: 'to carry out a task', level: 'cet4', cat: 'verb' },
  { zh: '审查', en: 'review', def: 'to examine or assess formally', level: 'cet4', cat: 'verb' },
  { zh: '评估', en: 'evaluate', def: 'to determine the value of', level: 'cet4', cat: 'verb' },
  { zh: '监督', en: 'supervise', def: 'to watch over a person at work', level: 'cet4', cat: 'verb' },
  { zh: '指导', en: 'guide', def: 'to lead or direct', level: 'cet4', cat: 'verb' },
  { zh: '训练', en: 'train', def: 'to teach a particular skill', level: 'cet4', cat: 'verb' },
  { zh: '教育', en: 'educate', def: 'to give intellectual or moral instruction', level: 'cet4', cat: 'verb' },
  { zh: '培养', en: 'cultivate', def: 'to develop an attitude or skill', level: 'cet4', cat: 'verb' },
];

/* Build lookup Map (O(1) per key) */
const WORD_BANK_MAP = new Map();
for (const entry of WORD_BANK) {
  WORD_BANK_MAP.set(entry.zh, entry);
}
