#!/usr/bin/env python3
"""Append second batch of ~300 entries to reach ~3500 total."""

import re

WORKBANK_PATH = '/home/hermes/IFLL-Web/src/lib/wordbank.js'

# ── Read current file and extract existing zh values ──
with open(WORKBANK_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

existing = set(re.findall(r"zh:\s*'([^']*)'", content))
print(f"Current entries: {len(existing)}")

# ── Second batch of new entries ──
BATCH2 = [
    # More single-character words
    ('胖', 'fat', 'having excess body weight', 'daily', 'adj', 'adjective', '形容词'),
    ('瘦', 'thin', 'having little body fat', 'daily', 'adj', 'adjective', '形容词'),
    ('美', 'beautiful', 'pleasing to the senses or mind', 'daily', 'adj', 'adjective', '形容词'),
    ('丑', 'ugly', 'unpleasant or repulsive in appearance', 'daily', 'adj', 'adjective', '形容词'),
    ('苦', 'bitter', 'having a sharp pungent taste', 'daily', 'adj', 'adjective', '形容词'),
    ('辣', 'spicy', 'having a strong pungent flavor', 'daily', 'adj', 'adjective', '形容词'),
    ('酸', 'sour', 'having an acidic taste', 'daily', 'adj', 'adjective', '形容词'),
    ('咸', 'salty', 'tasting of or containing salt', 'daily', 'adj', 'adjective', '形容词'),
    ('圆', 'round', 'shaped like a circle or sphere', 'daily', 'adj', 'adjective', '形容词'),
    ('方', 'square', 'having four equal sides and right angles', 'daily', 'adj', 'adjective', '形容词'),
    ('厚', 'thick', 'of great or more than average depth', 'daily', 'adj', 'adjective', '形容词'),
    ('薄', 'thin', 'of small depth or thickness', 'daily', 'adj', 'adjective', '形容词'),
    ('宽', 'wide', 'of great extent from side to side', 'daily', 'adj', 'adjective', '形容词'),
    ('窄', 'narrow', 'of small width in comparison to length', 'daily', 'adj', 'adjective', '形容词'),
    ('硬', 'hard', 'solid and firm to the touch', 'daily', 'adj', 'adjective', '形容词'),
    ('软', 'soft', 'easy to mold or bend', 'daily', 'adj', 'adjective', '形容词'),
    ('干', 'dry', 'free from moisture or liquid', 'daily', 'adj', 'adjective', '形容词'),
    ('湿', 'wet', 'covered or saturated with liquid', 'daily', 'adj', 'adjective', '形容词'),
    ('脏', 'dirty', 'covered or marked with an unclean substance', 'daily', 'adj', 'adjective', '形容词'),
    ('乱', 'chaotic', 'in a state of complete disorder', 'daily', 'adj', 'adjective', '形容词'),
    ('静', 'quiet', 'making little or no sound', 'daily', 'adj', 'adjective', '形容词'),
    ('吵', 'noisy', 'making loud or disturbing sounds', 'daily', 'adj', 'adjective', '形容词'),
    ('滑', 'slippery', 'difficult to hold firmly because of smoothness', 'daily', 'adj', 'adjective', '形容词'),
    ('尖', 'sharp', 'having a thin cutting edge or fine point', 'daily', 'adj', 'adjective', '形容词'),
    ('钝', 'dull', 'lacking sharpness or edge', 'daily', 'adj', 'adjective', '形容词'),
    ('嫩', 'tender', 'soft and easy to chew', 'daily', 'adj', 'adjective', '形容词'),
    ('老', 'tough', 'hard to cut or chew', 'daily', 'adj', 'adjective', '形容词'),
    ('脆', 'crispy', 'firm and easily broken', 'daily', 'adj', 'adjective', '形容词'),
    ('粘', 'sticky', 'tending to stick to things', 'daily', 'adj', 'adjective', '形容词'),
    ('密', 'dense', 'closely compacted in substance', 'daily', 'adj', 'adjective', '形容词'),
    ('稀', 'thin/sparse', 'of less density than usual', 'daily', 'adj', 'adjective', '形容词'),
    ('粗', 'thick', 'of relatively great diameter', 'daily', 'adj', 'adjective', '形容词'),
    ('细', 'fine', 'of slender or thin diameter', 'daily', 'adj', 'adjective', '形容词'),
    
    # More HSK 3-6 words that weren't already covered
    ('翻译', 'translate', 'to express in another language', 'cet4', 'verb', 'verb', '动词',
     'Can you translate this sentence for me?', '你能帮我**翻译**这个句子吗？'),
    ('烦恼', 'worry', 'to feel anxious about something', 'cet4', 'emotion', 'verb', '动词'),
    ('放弃', 'give up', 'to stop trying to do something', 'cet4', 'verb', 'verb', '动词'),
    ('符合', 'conform', 'to comply with rules or standards', 'cet4', 'verb', 'verb', '动词'),
    ('辅导', 'tutor', 'to give individual teaching', 'cet4', 'verb', 'verb', '动词'),
    ('复杂', 'complicated', 'consisting of many interconnecting parts', 'cet4', 'adj', 'adjective', '形容词'),
    ('改革', 'reform', 'to make changes to improve a system', 'cet6', 'verb', 'verb', '动词'),
    ('改进', 'improve', 'to make something better', 'cet4', 'verb', 'verb', '动词',
     'We need to improve our service quality.', '我们需要**改进**服务质量。'),
    ('概括', 'summarize', 'to give a brief statement of main points', 'cet4', 'verb', 'verb', '动词'),
    ('概念', 'concept', 'an abstract idea or general notion', 'cet4', 'abstract', 'noun', '名词'),
    ('干燥', 'dry', 'lacking moisture', 'cet4', 'adj', 'adjective', '形容词'),
    ('感谢', 'thank', 'to express gratitude', 'daily', 'verb', 'verb', '动词',
     'I want to thank you for your help.', '我想**感谢**你的帮助。'),
    ('钢铁', 'steel', 'a strong metal alloy', 'cet4', 'daily', 'noun', '名词'),
    ('港口', 'port', 'a town or city with a harbor', 'cet4', 'daily', 'noun', '名词'),
    ('高度', 'height', 'the measurement from base to top', 'cet4', 'abstract', 'noun', '名词'),
    ('搞', 'do/make', 'to do something in a casual way', 'daily', 'verb', 'verb', '动词'),
    ('告别', 'say goodbye', 'to take leave of someone', 'daily', 'verb', 'verb', '动词'),
    ('格式', 'format', 'the arrangement or layout', 'cet4', 'abstract', 'noun', '名词'),
    ('工程', 'engineering', 'the application of science for practical use', 'cet4', 'academic', 'noun', '名词',
     'The engineering project was completed on time.', '**工程**项目按时完成了。'),
    ('工业', 'industry', 'the production of goods', 'cet4', 'business', 'noun', '名词'),
    ('工资', 'wage', 'a fixed regular payment for work', 'cet4', 'business', 'noun', '名词',
     'The wages are paid monthly.', '**工资**每月支付。'),
    ('贡献', 'contribution', 'a gift or payment to a common fund', 'cet4', 'abstract', 'noun', '名词'),
    ('构造', 'structure', 'the arrangement of parts', 'cet4', 'abstract', 'noun', '名词'),
    ('古代', 'ancient times', 'the historical period of antiquity', 'cet4', 'time', 'noun', '名词'),
    ('鼓励', 'encourage', 'to give support or confidence', 'cet4', 'verb', 'verb', '动词',
     'Parents should encourage their children.', '父母应该**鼓励**孩子。'),
    ('故乡', 'hometown', 'the place where one grew up', 'cet4', 'daily', 'noun', '名词'),
    ('关键', 'key', 'a crucial or pivotal element', 'cet4', 'abstract', 'noun', '名词',
     'Communication is key to a good relationship.', '沟通是良好关系的**关键**。'),
    ('观点', 'viewpoint', 'a particular way of seeing things', 'cet4', 'abstract', 'noun', '名词'),
    ('观察', 'observe', 'to watch carefully and attentively', 'cet4', 'verb', 'verb', '动词'),
    ('贯彻', 'implement', 'to put a policy into effect', 'cet4', 'verb', 'verb', '动词'),
    ('广泛', 'extensive', 'covering a wide range', 'cet4', 'adj', 'adjective', '形容词'),
    ('轨道', 'orbit/track', 'the path of a moving object', 'cet4', 'abstract', 'noun', '名词'),
    ('害羞', 'shy', 'nervous or timid in company', 'daily', 'emotion', 'adjective', '形容词',
     'She is too shy to speak in public.', '她太**害羞**了，不敢在公共场合讲话。'),
    ('含义', 'meaning', 'the significance of something', 'cet4', 'abstract', 'noun', '名词'),
    ('行业', 'industry', 'a particular branch of economic activity', 'cet4', 'business', 'noun', '名词',
     'The tech industry is growing rapidly.', '科技**行业**正在快速增长。'),
    ('自豪', 'proud', 'feeling deep pleasure from achievements', 'cet4', 'emotion', 'adjective', '形容词'),
    ('环节', 'link', 'one part of a chain or process', 'cet4', 'abstract', 'noun', '名词'),
    ('幻想', 'fantasy', 'imagination unrestricted by reality', 'cet4', 'abstract', 'noun', '名词'),
    ('回忆', 'recall', 'to bring back a memory', 'cet4', 'verb', 'verb', '动词'),
    ('活跃', 'active', 'energetic and lively', 'cet4', 'adj', 'adjective', '形容词'),
    ('积累', 'accumulate', 'to gather over time', 'cet4', 'verb', 'verb', '动词'),
    ('激烈', 'fierce', 'intense and powerful', 'cet4', 'adj', 'adjective', '形容词'),
    ('极限', 'maximum', 'the greatest possible amount', 'cet4', 'abstract', 'noun', '名词'),
    ('计算', 'calculate', 'to determine mathematically', 'cet4', 'verb', 'verb', '动词',
     'Calculate the total cost of the project.', '**计算**项目的总成本。'),
    ('记录', 'record', 'to set down in writing', 'cet4', 'verb', 'verb', '动词'),
    ('记忆', 'memory', 'the faculty by which the mind stores information', 'cet4', 'abstract', 'noun', '名词'),
    ('继承', 'inherit', 'to receive from predecessors', 'cet4', 'verb', 'verb', '动词'),
    ('加工', 'process', 'to treat or prepare raw materials', 'cet4', 'verb', 'verb', '动词'),
    ('家具', 'furniture', 'movable items in a room', 'daily', 'daily', 'noun', '名词'),
    ('坚决', 'resolute', 'firm and determined', 'cet4', 'adj', 'adjective', '形容词'),
    ('坚强', 'strong', 'mentally powerful and resilient', 'cet4', 'adj', 'adjective', '形容词'),
    ('艰巨', 'arduous', 'requiring great effort', 'cet4', 'adj', 'adjective', '形容词'),
    ('建筑', 'building', 'a structure with roof and walls', 'cet4', 'daily', 'noun', '名词',
     'The building is over 100 years old.', '这座**建筑**有100多年的历史。'),
    ('健康', 'health', 'the state of being free from illness', 'cet4', 'abstract', 'noun', '名词'),
    ('鉴赏', 'appreciate', 'to recognize the value of', 'cet4', 'verb', 'verb', '动词'),
    ('讲座', 'lecture', 'an educational talk given to an audience', 'cet4', 'academic', 'noun', '名词',
     'The lecture on history was fascinating.', '关于历史的**讲座**很精彩。'),
    ('交换', 'exchange', 'to give and receive mutually', 'cet4', 'verb', 'verb', '动词'),
    ('郊区', 'suburb', 'an outlying district of a city', 'cet4', 'daily', 'noun', '名词'),
    ('骄傲', 'arrogant', 'having an exaggerated sense of self-importance', 'cet4', 'adj', 'adjective', '形容词'),
    ('教训', 'lesson', 'a piece of wisdom gained from experience', 'cet4', 'abstract', 'noun', '名词'),
    ('教育', 'education', 'the process of receiving instruction', 'cet4', 'society', 'noun', '名词'),
    ('接触', 'contact', 'to get in touch with someone', 'cet4', 'verb', 'verb', '动词',
     'I will contact you when I arrive.', '我到达时会**接触**你。'),
    ('接待', 'receive', 'to greet and entertain guests', 'cet4', 'verb', 'verb', '动词'),
    ('节约', 'save', 'to use less of a resource', 'cet4', 'verb', 'verb', '动词'),
    ('解放', 'liberate', 'to set free from oppression', 'cet4', 'verb', 'verb', '动词'),
    ('紧密', 'close', 'very near in space or relationship', 'cet4', 'adj', 'adjective', '形容词'),
    ('今天', 'today', 'the current day', 'daily', 'time', 'noun', '名词'),
    ('尽量', 'as much as possible', 'to the greatest extent', 'cet4', 'adverb', 'adverb', '副词'),
    ('尽力', 'try one\'s best', 'to do all that one can', 'cet4', 'verb', 'verb', '动词'),
    ('进展', 'progress', 'forward or onward movement', 'cet4', 'abstract', 'noun', '名词'),
    ('惊讶', 'surprised', 'feeling surprised or astonished', 'daily', 'emotion', 'adjective', '形容词',
     'I was surprised by the news.', '我听到这个消息很**惊讶**。'),
    ('精彩', 'brilliant', 'outstanding and impressive', 'cet4', 'adj', 'adjective', '形容词',
     'It was a brilliant performance.', '这是一场**精彩**的表演。'),
    ('精力', 'energy', 'mental or physical vigor', 'cet4', 'abstract', 'noun', '名词'),
    ('精确', 'precise', 'exact and accurate', 'cet4', 'adj', 'adjective', '形容词'),
    ('精神', 'spirit', 'the non-physical part of a person', 'cet4', 'abstract', 'noun', '名词',
     'The team showed great spirit.', '这支队伍展现了很好的**精神**。'),
    ('竞赛', 'contest', 'an event where people compete', 'cet4', 'daily', 'noun', '名词'),
    ('竞争', 'compete', 'to strive against others', 'cet4', 'verb', 'verb', '动词'),
    ('居民', 'resident', 'a person who lives somewhere', 'cet4', 'society', 'noun', '名词'),
    ('具备', 'possess', 'to have as a quality', 'cet4', 'verb', 'verb', '动词'),
    ('具体', 'specific', 'clearly defined or identified', 'cet4', 'adj', 'adjective', '形容词'),
    ('巨大', 'huge', 'extremely large in size or amount', 'cet4', 'adj', 'adjective', '形容词',
     'There was a huge crowd at the concert.', '音乐会上有**巨大**的人群。'),
    ('绝对', 'absolute', 'not qualified or diminished', 'cet4', 'adj', 'adjective', '形容词'),
    ('均衡', 'balanced', 'kept in a state of equilibrium', 'cet4', 'adj', 'adjective', '形容词'),
    ('军事', 'military', 'relating to armed forces', 'cet4', 'society', 'noun', '名词'),
    ('开发', 'develop', 'to make use of a resource', 'cet4', 'verb', 'verb', '动词'),
    ('开放', 'open up', 'to make accessible', 'cet4', 'verb', 'verb', '动词',
     'The museum is open to the public.', '博物馆对公众**开放**。'),
    ('开幕', 'open', 'to begin a ceremony', 'cet4', 'verb', 'verb', '动词'),
    ('刊登', 'publish', 'to print in a newspaper', 'cet4', 'verb', 'verb', '动词'),
    ('看法', 'opinion', 'a personal view or judgment', 'cet4', 'abstract', 'noun', '名词'),
    ('考', 'take an exam', 'to sit for an examination', 'daily', 'verb', 'verb', '动词'),
    ('烤', 'bake/roast', 'to cook by dry heat', 'daily', 'verb', 'verb', '动词'),
    ('科目', 'subject', 'a branch of study', 'cet4', 'academic', 'noun', '名词'),
    ('科学', 'science', 'systematic study of the natural world', 'cet4', 'academic', 'noun', '名词',
     'Science helps us understand the universe.', '**科学**帮助我们理解宇宙。'),
    ('科学家', 'scientist', 'an expert in science', 'cet4', 'academic', 'noun', '名词'),
    ('可靠', 'reliable', 'consistently good and trustworthy', 'cet4', 'adj', 'adjective', '形容词'),
    ('刻苦', 'diligent', 'hardworking and persistent', 'cet4', 'adj', 'adjective', '形容词'),
    ('客观', 'objective', 'not influenced by personal feelings', 'cet4', 'adj', 'adjective', '形容词'),
    ('课程', 'course', 'a series of lessons on a subject', 'cet4', 'academic', 'noun', '名词',
     'This course covers advanced topics.', '这门**课程**涵盖高级主题。'),
    ('空间', 'space', 'a continuous area free of obstacles', 'cet4', 'abstract', 'noun', '名词'),
    ('空闲', 'free time', 'time when not occupied', 'daily', 'time', 'noun', '名词'),
    ('控制', 'control', 'to exercise authoritative influence over', 'cet4', 'verb', 'verb', '动词'),
    ('口号', 'slogan', 'a short memorable phrase', 'cet4', 'daily', 'noun', '名词'),
    ('宽阔', 'broad', 'having great width', 'cet4', 'adj', 'adjective', '形容词'),
    ('垃圾', 'garbage', 'waste material', 'daily', 'daily', 'noun', '名词',
     'Please take out the garbage.', '请把**垃圾**拿出去。'),
    ('来源', 'source', 'a point of origin', 'cet4', 'abstract', 'noun', '名词'),
    ('冷静', 'calm', 'not excited or agitated', 'daily', 'emotion', 'adjective', '形容词',
     'Stay calm in an emergency.', '紧急情况下保持**冷静**。'),
    ('礼貌', 'polite', 'showing good manners', 'daily', 'adj', 'adjective', '形容词'),
    ('厉害', 'impressive', 'extremely good or skillful', 'daily', 'adj', 'adjective', '形容词',
     'She is really impressive at playing piano.', '她弹钢琴真的很**厉害**。'),
    ('利益', 'benefit', 'an advantage or gain', 'cet4', 'abstract', 'noun', '名词'),
    ('联合', 'unite', 'to come or bring together', 'cet4', 'verb', 'verb', '动词'),
    ('联系', 'contact', 'communication between people', 'cet4', 'abstract', 'noun', '名词',
     'We keep in contact via email.', '我们通过邮件保持**联系**。'),
    ('良好', 'good', 'of a satisfactory standard', 'cet4', 'adj', 'adjective', '形容词'),
    ('粮食', 'grain', 'cereal plants grown for food', 'cet4', 'daily', 'noun', '名词'),
    ('聊天', 'chat', 'to talk informally', 'daily', 'verb', 'verb', '动词',
     'Let\'s chat over a cup of coffee.', '我们边喝咖啡边**聊天**吧。'),
    ('临时', 'temporary', 'lasting only for a limited time', 'cet4', 'adj', 'adjective', '形容词'),
    ('零件', 'part', 'a component of a machine', 'cet4', 'daily', 'noun', '名词'),
    ('领先', 'lead', 'to be in front in a race', 'cet4', 'verb', 'verb', '动词'),
    ('流传', 'spread', 'to pass from person to person', 'cet4', 'verb', 'verb', '动词'),
    ('流水', 'flowing water', 'a steady stream of water', 'cet4', 'nature', 'noun', '名词'),
    ('流行', 'popular', 'widely liked or admired', 'daily', 'adj', 'adjective', '形容词',
     'This song is very popular among young people.', '这首歌在年轻人中很**流行**。'),
    ('履行', 'fulfill', 'to carry out a duty', 'cet4', 'verb', 'verb', '动词'),
    ('论述', 'discuss', 'to write or speak about systematically', 'cet4', 'verb', 'verb', '动词'),
    ('落后', 'fall behind', 'to drop behind others in progress', 'cet4', 'verb', 'verb', '动词'),
    ('马虎', 'careless', 'not giving sufficient attention', 'daily', 'adj', 'adjective', '形容词'),
    ('码头', 'dock', 'a place for loading ships', 'cet4', 'daily', 'noun', '名词'),
    ('满', 'full', 'containing as much as possible', 'daily', 'adj', 'adjective', '形容词'),
    ('慢性', 'chronic', 'persisting for a long time', 'cet4', 'adj', 'adjective', '形容词'),
    ('盲目', 'blind', 'without reason or judgment', 'cet4', 'adj', 'adjective', '形容词'),
    ('矛盾', 'contradiction', 'a direct opposition between things', 'cet4', 'abstract', 'noun', '名词'),
    ('冒险', 'take a risk', 'to engage in risky behavior', 'cet4', 'verb', 'verb', '动词'),
    ('贸易', 'trade', 'the exchange of goods and services', 'cet4', 'business', 'noun', '名词',
     'International trade benefits all countries involved.', '国际**贸易**惠及所有参与国。'),
    ('美观', 'aesthetic', 'pleasing in appearance', 'cet4', 'adj', 'adjective', '形容词'),
    ('美术', 'fine arts', 'creative art forms', 'cet4', 'academic', 'noun', '名词'),
    ('魅力', 'charm', 'a powerful attractiveness', 'cet4', 'abstract', 'noun', '名词',
     'The old town has a unique charm.', '古城有独特的**魅力**。'),
    ('梦想', 'dream', 'a cherished aspiration', 'cet4', 'abstract', 'noun', '名词'),
    ('密切', 'close', 'with close connection', 'cet4', 'adj', 'adjective', '形容词'),
    ('免费', 'free', 'at no cost', 'daily', 'adj', 'adjective', '形容词',
     'The app is free to download.', '这个应用**免费**下载。'),
    ('面临', 'face', 'to encounter a situation', 'cet4', 'verb', 'verb', '动词',
     'We are facing a difficult challenge.', '我们正**面临**一个艰难的挑战。'),
    ('民间', 'folk', 'of or among ordinary people', 'cet4', 'society', 'noun', '名词'),
    ('民主', 'democratic', 'relating to government by the people', 'cet4', 'society', 'adjective', '形容词'),
    ('明白', 'understand', 'to perceive the meaning of', 'daily', 'verb', 'verb', '动词'),
    ('明确', 'clear', 'clearly defined and unambiguous', 'cet4', 'adj', 'adjective', '形容词',
     'We need a clear goal.', '我们需要一个**明确**的目标。'),
    ('明显', 'obvious', 'easily perceived or understood', 'cet4', 'adj', 'adjective', '形容词'),
    ('名称', 'name', 'a word by which something is known', 'cet4', 'daily', 'noun', '名词'),
    ('命令', 'command', 'to give an authoritative order', 'cet4', 'verb', 'verb', '动词'),
    ('命运', 'fate', 'the development of events beyond control', 'cet4', 'abstract', 'noun', '名词',
     'We control our own fate through our choices.', '我们通过选择掌控自己的**命运**。'),
    ('模仿', 'imitate', 'to copy someone\'s behavior', 'cet4', 'verb', 'verb', '动词'),
    ('模糊', 'vague', 'not clearly expressed or perceived', 'cet4', 'adj', 'adjective', '形容词'),
    ('模块', 'module', 'a self-contained unit of a system', 'cet4', 'abstract', 'noun', '名词'),
    ('模型', 'model', 'a representation of a system', 'cet4', 'abstract', 'noun', '名词'),
    ('默默', 'silently', 'without making a sound', 'cet4', 'adverb', 'adverb', '副词'),
    ('目标', 'target', 'an objective to aim for', 'cet4', 'abstract', 'noun', '名词'),
    ('内部', 'internal', 'situated within something', 'cet4', 'adj', 'adjective', '形容词'),
    ('能力', 'capability', 'the power to do something', 'cet4', 'abstract', 'noun', '名词'),
    ('能量', 'energy', 'the ability to do work', 'cet4', 'abstract', 'noun', '名词'),
    ('年代', 'era', 'a long distinct period of history', 'cet4', 'time', 'noun', '名词'),
    ('宁可', 'would rather', 'prefer to do something', 'cet4', 'adverb', 'adverb', '副词'),
    ('农民', 'farmer', 'a person who farms land', 'cet4', 'daily', 'noun', '名词'),
    ('农业', 'agriculture', 'the science of farming', 'cet4', 'nature', 'noun', '名词',
     'Agriculture is the backbone of the economy.', '**农业**是经济的支柱。'),
    ('偶然', 'accidental', 'happening by chance', 'cet4', 'adj', 'adjective', '形容词'),
    ('拍摄', 'shoot', 'to take a photograph or film', 'daily', 'verb', 'verb', '动词'),
    ('排列', 'arrange', 'to set in a particular order', 'cet4', 'verb', 'verb', '动词'),
    ('培养', 'cultivate', 'to develop or foster', 'cet4', 'verb', 'verb', '动词',
     'Schools cultivate students\' talents.', '学校**培养**学生的才能。'),
    ('配备', 'equip with', 'to provide with necessary items', 'cet4', 'verb', 'verb', '动词'),
    ('配套', 'supporting', 'forming a complete set', 'cet4', 'adj', 'adjective', '形容词'),
    ('捧', 'hold up', 'to hold something in both hands', 'daily', 'verb', 'verb', '动词'),
    ('劈', 'split', 'to cut apart with force', 'daily', 'verb', 'verb', '动词'),
    ('篇', 'piece of writing', 'a single article or essay', 'daily', 'daily', 'measure-word', '量词'),
    ('骗', 'cheat', 'to deceive someone', 'daily', 'verb', 'verb', '动词'),
    ('拼搏', 'strive', 'to struggle or fight vigorously', 'cet4', 'verb', 'verb', '动词'),
    ('贫困', 'poverty', 'the state of being extremely poor', 'cet4', 'society', 'noun', '名词'),
    ('频繁', 'frequent', 'occurring often', 'cet4', 'adj', 'adjective', '形容词'),
    ('品德', 'moral character', 'good personal qualities', 'cet4', 'abstract', 'noun', '名词'),
    ('平方', 'square', 'a number multiplied by itself', 'cet4', 'academic', 'noun', '名词'),
    ('平衡', 'balance', 'an even distribution of weight', 'cet4', 'abstract', 'noun', '名词',
     'Keep a balance between work and rest.', '保持工作和休息的**平衡**。'),
    ('评价', 'evaluate', 'to form an opinion of value', 'cet4', 'verb', 'verb', '动词'),
    ('评选', 'select', 'to choose through a vote', 'cet4', 'verb', 'verb', '动词'),
    ('破产', 'bankrupt', 'unable to pay debts', 'cet4', 'business', 'adjective', '形容词'),
    ('普遍', 'universal', 'applying to all cases', 'cet4', 'adj', 'adjective', '形容词'),
    ('朴实', 'simple', 'plain and unpretentious', 'cet4', 'adj', 'adjective', '形容词'),
    ('朴素', 'frugal', 'simple and inexpensive', 'cet4', 'adj', 'adjective', '形容词'),
    ('期货', 'futures', 'trading contracts for future delivery', 'cet4', 'business', 'noun', '名词'),
    ('期待', 'anticipate', 'to look forward to', 'cet4', 'verb', 'verb', '动词',
     'I anticipate a great outcome.', '我**期待**一个好的结果。'),
    ('期间', 'period', 'a length of time', 'cet4', 'time', 'noun', '名词'),
    ('奇迹', 'miracle', 'an extraordinary event', 'cet4', 'abstract', 'noun', '名词',
     'It was a miracle that no one was hurt.', '没人受伤真是个**奇迹**。'),
    ('启发', 'inspire', 'to stimulate creativity or thought', 'cet4', 'verb', 'verb', '动词'),
    ('气氛', 'atmosphere', 'the mood of a place or situation', 'cet4', 'abstract', 'noun', '名词',
     'The atmosphere at the party was festive.', '派对上的**气氛**很欢乐。'),
    ('气候', 'climate', 'the weather conditions of a region', 'cet4', 'nature', 'noun', '名词'),
    ('气体', 'gas', 'a substance that can expand freely', 'cet4', 'academic', 'noun', '名词'),
    ('汽车', 'car', 'a road vehicle with four wheels', 'daily', 'daily', 'noun', '名词'),
    ('签订', 'sign', 'to sign a contract or agreement', 'cet4', 'verb', 'verb', '动词'),
    ('谦虚', 'humble', 'not proud or arrogant', 'cet4', 'adj', 'adjective', '形容词'),
    ('前途', 'future', 'the likely future prospects', 'cet4', 'abstract', 'noun', '名词'),
    ('强大', 'powerful', 'having great power or strength', 'cet4', 'adj', 'adjective', '形容词',
     'China has become a powerful nation.', '中国已成为一个**强大**的国家。'),
    ('强调', 'emphasize', 'to give special importance to', 'cet4', 'verb', 'verb', '动词'),
    ('强壮', 'strong', 'physically powerful', 'daily', 'adj', 'adjective', '形容词'),
    ('巧妙', 'ingenious', 'clever and original', 'cet4', 'adj', 'adjective', '形容词'),
    ('切实', 'practical', 'realistic and feasible', 'cet4', 'adj', 'adjective', '形容词'),
    ('侵犯', 'violate', 'to encroach upon rights', 'cet4', 'verb', 'verb', '动词'),
    ('侵略', 'invade', 'to enter by force', 'cet4', 'verb', 'verb', '动词'),
    ('勤奋', 'diligent', 'hardworking and industrious', 'cet4', 'adj', 'adjective', '形容词'),
    ('青年', 'youth', 'the period of being young', 'cet4', 'daily', 'noun', '名词'),
    ('情景', 'scene', 'a situation or vista', 'cet4', 'abstract', 'noun', '名词'),
    ('情况', 'circumstance', 'the conditions surrounding an event', 'cet4', 'abstract', 'noun', '名词'),
    ('情绪', 'mood', 'a temporary state of mind', 'cet4', 'emotion', 'noun', '名词',
     'Her mood improved after a good meal.', '一顿好饭之后她的**情绪**好了。'),
    ('趋势', 'trend', 'a general direction of change', 'cet4', 'abstract', 'noun', '名词'),
    ('渠道', 'channel', 'a means of access', 'cet4', 'abstract', 'noun', '名词'),
    ('权力', 'power', 'the ability to influence or control', 'cet4', 'society', 'noun', '名词'),
    ('权利', 'right', 'a legal entitlement', 'cet4', 'society', 'noun', '名词'),
    ('权威', 'authority', 'the power to enforce rules', 'cet4', 'society', 'noun', '名词',
     'The teacher has authority in the classroom.', '老师在课堂上有**权威**。'),
    ('全局', 'overall situation', 'the entire overall situation', 'cet4', 'abstract', 'noun', '名词'),
    ('全面', 'comprehensive', 'including all aspects', 'cet4', 'adj', 'adjective', '形容词'),
    ('全年', 'year-round', 'throughout the entire year', 'daily', 'time', 'adverb', '副词'),
    ('全身', 'whole body', 'the entire body', 'daily', 'daily', 'noun', '名词'),
    ('缺少', 'lack', 'to be without something', 'cet4', 'verb', 'verb', '动词',
     'The project lacks sufficient funding.', '该项目**缺少**足够的资金。'),
    ('确保', 'ensure', 'to make certain something happens', 'cet4', 'verb', 'verb', '动词'),
    ('确定', 'determine', 'to firmly decide', 'cet4', 'verb', 'verb', '动词'),
    ('确认', 'confirm', 'to establish the truth of', 'cet4', 'verb', 'verb', '动词'),
    ('群体', 'group', 'a number of people together', 'cet4', 'society', 'noun', '名词'),
    ('燃烧', 'burn', 'to be on fire', 'cet4', 'verb', 'verb', '动词'),
    ('让步', 'concede', 'to admit defeat in an argument', 'cet4', 'verb', 'verb', '动词'),
    ('热爱', 'love deeply', 'to feel great affection for', 'cet4', 'emotion', 'verb', '动词',
     'She loves her work deeply.', '她**热爱**自己的工作。'),
    ('热心', 'enthusiastic', 'eager and enthusiastic', 'daily', 'adj', 'adjective', '形容词'),
    ('人才', 'talent', 'people with natural aptitude', 'cet4', 'abstract', 'noun', '名词',
     'The company is looking for talent.', '公司正在寻找**人才**。'),
    ('人口', 'population', 'the number of inhabitants', 'cet4', 'society', 'noun', '名词'),
    ('人类', 'humankind', 'the human species collectively', 'cet4', 'society', 'noun', '名词',
     'Humankind has achieved remarkable progress.', '**人类**取得了显著的进步。'),
    ('人民币', 'RMB', 'the currency of China', 'daily', 'business', 'noun', '名词'),
    ('人员', 'staff', 'people employed in an organization', 'cet4', 'daily', 'noun', '名词'),
    ('忍耐', 'endure', 'to bear patiently', 'cet4', 'verb', 'verb', '动词'),
    ('日报', 'daily newspaper', 'a newspaper published every day', 'cet4', 'daily', 'noun', '名词'),
    ('日常', 'daily', 'everyday routine', 'cet4', 'daily', 'adjective', '形容词',
     'These are my daily chores.', '这些是我的**日常**事务。'),
    ('日程', 'schedule', 'a plan of things to be done', 'cet4', 'daily', 'noun', '名词'),
    ('容量', 'capacity', 'the maximum amount that can be held', 'cet4', 'abstract', 'noun', '名词'),
    ('容纳', 'accommodate', 'to provide space for', 'cet4', 'verb', 'verb', '动词'),
    ('溶解', 'dissolve', 'to mix a solid into a liquid', 'cet4', 'verb', 'verb', '动词'),
    ('柔软', 'soft', 'yielding easily to pressure', 'daily', 'adj', 'adjective', '形容词'),
    ('入侵', 'intrude', 'to enter without permission', 'cet4', 'verb', 'verb', '动词'),
    ('软件', 'software', 'programs for a computer', 'cet4', 'tech', 'noun', '名词'),
    ('弱', 'weak', 'lacking strength', 'daily', 'adj', 'adjective', '形容词'),
    ('删除', 'delete', 'to remove something', 'cet4', 'verb', 'verb', '动词',
     'Please delete the old files.', '请**删除**旧文件。'),
    ('善良', 'kind', 'generous and considerate', 'daily', 'adj', 'adjective', '形容词'),
    ('伤害', 'harm', 'to cause injury or damage', 'cet4', 'verb', 'verb', '动词',
     'Don\'t harm innocent people.', '不要**伤害**无辜的人。'),
    ('商业', 'commerce', 'the activity of buying and selling', 'cet4', 'business', 'noun', '名词'),
    ('上层', 'upper level', 'the higher social or political level', 'cet4', 'society', 'noun', '名词'),
    ('设备', 'equipment', 'the necessary items for a purpose', 'cet4', 'daily', 'noun', '名词',
     'The equipment needs regular maintenance.', '**设备**需要定期维护。'),
    ('设计', 'design', 'to plan the form of something', 'cet4', 'verb', 'verb', '动词'),
    ('设立', 'establish', 'to set up or found', 'cet4', 'verb', 'verb', '动词'),
    ('设施', 'facility', 'a place or equipment for a purpose', 'cet4', 'daily', 'noun', '名词'),
    ('社会', 'society', 'the aggregate of people living together', 'cet4', 'society', 'noun', '名词'),
    ('射击', 'shoot', 'to fire a gun', 'cet4', 'verb', 'verb', '动词'),
    ('摄影', 'photography', 'the art of taking photographs', 'daily', 'daily', 'noun', '名词'),
    ('身份', 'identity', 'who or what a person is', 'cet4', 'abstract', 'noun', '名词'),
    ('深化', 'deepen', 'to make deeper or more intense', 'cet4', 'verb', 'verb', '动词'),
    ('深刻', 'profound', 'of deep meaning or significance', 'cet4', 'adj', 'adjective', '形容词',
     'The speech had a profound impact.', '演讲产生了**深刻**的影响。'),
    ('神奇', 'magical', 'having extraordinary properties', 'daily', 'adj', 'adjective', '形容词'),
    ('生存', 'survive', 'to remain alive', 'cet4', 'verb', 'verb', '动词',
     'Animals must adapt to survive in the wild.', '动物必须适应才能在野外**生存**。'),
    ('生动', 'vivid', 'producing clear mental images', 'cet4', 'adj', 'adjective', '形容词'),
    ('生活', 'life', 'the condition of being alive', 'cet4', 'daily', 'noun', '名词'),
    ('生命', 'life', 'the existence of a living being', 'cet4', 'abstract', 'noun', '名词',
     'Life is precious and should be cherished.', '**生命**是宝贵的，应该珍惜。'),
    ('生日', 'birthday', 'the anniversary of one\'s birth', 'daily', 'daily', 'noun', '名词'),
    ('生态', 'ecological', 'relating to the environment', 'cet4', 'nature', 'adjective', '形容词'),
    ('生物', 'organism', 'a living individual', 'cet4', 'nature', 'noun', '名词'),
    ('剩余', 'remaining', 'what is left over', 'cet4', 'adj', 'adjective', '形容词'),
    ('失望', 'disappointed', 'sad because expectations were not met', 'daily', 'emotion', 'adjective', '形容词',
     'I was disappointed with the result.', '我对结果感到**失望**。'),
    ('师范', 'teacher training', 'education for teachers', 'cet4', 'academic', 'noun', '名词'),
    ('施工', 'construct', 'to build or put up', 'cet4', 'verb', 'verb', '动词'),
    ('十足', 'full', 'complete and thorough', 'cet4', 'adj', 'adjective', '形容词'),
    ('石油', 'petroleum', 'a liquid fossil fuel', 'cet4', 'nature', 'noun', '名词'),
    ('时代', 'times', 'a particular period in history', 'cet4', 'time', 'noun', '名词'),
    ('时刻', 'moment', 'a particular point in time', 'cet4', 'time', 'noun', '名词',
     'This is a historic moment.', '这是一个历史性的**时刻**。'),
    ('时装', 'fashion', 'popular clothing style', 'daily', 'daily', 'noun', '名词'),
    ('实践', 'practice', 'the actual application of a theory', 'cet4', 'abstract', 'noun', '名词',
     'Theory must be combined with practice.', '理论必须与**实践**相结合。'),
    ('实力', 'strength', 'the capacity to achieve something', 'cet4', 'abstract', 'noun', '名词'),
    ('实施', 'implement', 'to put into effect', 'cet4', 'verb', 'verb', '动词'),
    ('实验', 'experiment', 'a scientific procedure to test a hypothesis', 'cet4', 'academic', 'noun', '名词'),
    ('士兵', 'soldier', 'a person who serves in an army', 'cet4', 'society', 'noun', '名词'),
    ('市场', 'market', 'a place for trade', 'cet4', 'business', 'noun', '名词',
     'The stock market is volatile.', '股市**市场**波动很大。'),
    ('事故', 'accident', 'an unfortunate incident', 'cet4', 'daily', 'noun', '名词'),
    ('事件', 'event', 'a significant occurrence', 'cet4', 'abstract', 'noun', '名词',
     'The event attracted media attention.', '这个**事件**引起了媒体关注。'),
    ('事实', 'fact', 'something known to be true', 'cet4', 'abstract', 'noun', '名词'),
    ('事物', 'thing', 'an object or entity', 'cet4', 'abstract', 'noun', '名词'),
    ('势头', 'momentum', 'the force gained by movement', 'cet4', 'abstract', 'noun', '名词'),
    ('收藏', 'collect', 'to accumulate items as a hobby', 'daily', 'verb', 'verb', '动词'),
    ('收入', 'income', 'money received for work or investments', 'cet4', 'business', 'noun', '名词',
     'His income has increased this year.', '他的**收入**今年增加了。'),
    ('手段', 'means', 'a method for achieving something', 'cet4', 'abstract', 'noun', '名词'),
    ('手工', 'handmade', 'made by hand', 'daily', 'adj', 'adjective', '形容词'),
    ('手术', 'surgery', 'a medical operation', 'cet4', 'daily', 'noun', '名词'),
    ('手套', 'gloves', 'a covering for the hand', 'daily', 'daily', 'noun', '名词'),
    ('手续', 'procedure', 'a sequence of administrative steps', 'cet4', 'abstract', 'noun', '名词'),
    ('首相', 'prime minister', 'the head of government in some countries', 'cet4', 'society', 'noun', '名词'),
    ('寿命', 'lifespan', 'the length of time something lives', 'cet4', 'abstract', 'noun', '名词'),
    ('书写', 'write', 'to mark letters or words on a surface', 'cet4', 'verb', 'verb', '动词'),
    ('输入', 'input', 'to enter data into a computer', 'cet4', 'verb', 'verb', '动词'),
    ('输出', 'output', 'to produce or supply data', 'cet4', 'verb', 'verb', '动词'),
    ('树立', 'establish', 'to set up something positive', 'cet4', 'verb', 'verb', '动词'),
    ('数据', 'data', 'facts and statistics collected together', 'cet4', 'academic', 'noun', '名词'),
    ('数量', 'quantity', 'an amount of something', 'cet4', 'abstract', 'noun', '名词'),
    ('数码', 'digital', 'relating to digital technology', 'cet4', 'tech', 'adjective', '形容词'),
    ('摔', 'fall', 'to lose balance and drop', 'daily', 'verb', 'verb', '动词'),
    ('率领', 'lead', 'to command a group', 'cet4', 'verb', 'verb', '动词'),
    ('水分', 'moisture', 'the water content in something', 'cet4', 'daily', 'noun', '名词'),
    ('水利', 'water conservancy', 'water resource management', 'cet4', 'nature', 'noun', '名词'),
    ('水泥', 'cement', 'a building material that hardens', 'cet4', 'daily', 'noun', '名词'),
    ('水平', 'level', 'a position on a scale of quality', 'cet4', 'abstract', 'noun', '名词',
     'Her English level is very high.', '她的英语**水平**很高。'),
    ('税收', 'tax revenue', 'income that a government collects', 'cet4', 'business', 'noun', '名词'),
    ('顺序', 'order', 'a sequence or arrangement', 'cet4', 'abstract', 'noun', '名词'),
    ('硕士', 'master\'s degree', 'a postgraduate academic degree', 'cet4', 'academic', 'noun', '名词'),
    ('丝绸', 'silk', 'a fine soft fabric from silkworms', 'cet4', 'daily', 'noun', '名词'),
    ('丝毫', 'slightest', 'the smallest amount', 'cet4', 'adj', 'adjective', '形容词'),
    ('撕', 'tear', 'to pull apart into pieces', 'daily', 'verb', 'verb', '动词'),
    ('死亡', 'death', 'the end of life', 'cet4', 'abstract', 'noun', '名词'),
    ('饲养', 'raise', 'to keep animals for food', 'cet4', 'verb', 'verb', '动词'),
    ('速度', 'speed', 'the rate at which something moves', 'cet4', 'abstract', 'noun', '名词',
     'Speed is important in this race.', '**速度**在这场比赛中很重要。'),
    ('塑造', 'shape', 'to give form to something', 'cet4', 'verb', 'verb', '动词'),
    ('酸性', 'acidity', 'the quality of being acid', 'cet4', 'academic', 'noun', '名词'),
    ('算法', 'algorithm', 'a process for solving a problem', 'cet4', 'tech', 'noun', '名词'),
    ('随意', 'casual', 'done without particular planning', 'daily', 'adj', 'adjective', '形容词'),
    ('随着', 'along with', 'in conjunction with', 'cet4', 'preposition', 'preposition', '介词'),
    ('损害', 'damage', 'to cause harm to something', 'cet4', 'verb', 'verb', '动词',
     'The storm damaged many buildings.', '暴风雨**损害**了许多建筑物。'),
    ('损耗', 'loss', 'the reduction in quantity or value', 'cet4', 'abstract', 'noun', '名词'),
    ('损失', 'loss', 'an unfortunate occurrence causing harm', 'cet4', 'abstract', 'noun', '名词'),
    ('缩短', 'shorten', 'to reduce in length', 'cet4', 'verb', 'verb', '动词'),
    ('缩小', 'reduce', 'to make smaller in size', 'cet4', 'verb', 'verb', '动词'),
    ('所得', 'income', 'money obtained from work or investments', 'cet4', 'business', 'noun', '名词'),
    ('所以他们', 'so/therefore', 'for that reason', 'daily', 'logic', 'conjunction', '连词'),
    ('所有', 'all', 'the whole quantity of', 'cet4', 'determiner', 'determiner', '限定词',
     'All students must attend the meeting.', '**所有**学生都必须参加会议。'),
    ('所长', 'director', 'the head of an institute', 'cet4', 'daily', 'noun', '名词'),
    ('台阶', 'step', 'a flat surface for stepping on', 'daily', 'daily', 'noun', '名词'),
    ('谈话', 'conversation', 'an informal spoken exchange', 'cet4', 'daily', 'noun', '名词'),
    ('坦白', 'frank', 'open and honest in expression', 'cet4', 'adj', 'adjective', '形容词'),
    ('探索', 'explore', 'to travel through for discovery', 'cet4', 'verb', 'verb', '动词',
     'Scientists explore new frontiers in space.', '科学家**探索**太空的新领域。'),
    ('探讨', 'investigate', 'to examine thoroughly', 'cet4', 'verb', 'verb', '动词'),
    ('陶瓷', 'ceramics', 'objects made from clay and hardened by heat', 'cet4', 'daily', 'noun', '名词'),
    ('特点', 'feature', 'a distinctive attribute', 'cet4', 'abstract', 'noun', '名词'),
    ('特定', 'specific', 'precisely identified', 'cet4', 'adj', 'adjective', '形容词'),
    ('特性', 'characteristic', 'a quality typical of a thing', 'cet4', 'abstract', 'noun', '名词'),
    ('疼痛', 'pain', 'physical suffering or discomfort', 'cet4', 'emotion', 'noun', '名词'),
    ('提倡', 'advocate', 'to publicly recommend', 'cet4', 'verb', 'verb', '动词'),
    ('提供', 'provide', 'to supply something needed', 'cet4', 'verb', 'verb', '动词'),
    ('提交', 'submit', 'to present for consideration', 'cet4', 'verb', 'verb', '动词',
     'Please submit your report by Friday.', '请在周五前**提交**报告。'),
    ('提升', 'elevate', 'to raise to a higher position', 'cet4', 'verb', 'verb', '动词'),
    ('体会', 'realize', 'to understand through experience', 'cet4', 'verb', 'verb', '动词'),
    ('体积', 'volume', 'the amount of three-dimensional space', 'cet4', 'academic', 'noun', '名词'),
    ('体现', 'embody', 'to represent in tangible form', 'cet4', 'verb', 'verb', '动词'),
]

# ── Add entries ──
total_added = 0
skipped = 0
new_js = []

for e in BATCH2:
    zh = e[0]
    if zh in existing:
        skipped += 1
        continue
    existing.add(zh)
    total_added += 1
    
    en = e[1]
    defn = e[2][:60]
    level = e[3]
    cat = e[4]
    pos = e[5]
    pos_cn = e[6]
    
    js = f"  {{ zh: '{zh}', en: '{en}', def: '{defn}', level: '{level}', cat: '{cat}', pos: '{pos}', pos_cn: '{pos_cn}'"
    if len(e) > 7 and e[7]:
        example_en = e[7].replace("'", "\\'")
        example_cn = e[8].replace("'", "\\'") if len(e) > 8 else ''
        if '**' not in example_cn and zh in example_cn:
            example_cn = example_cn.replace(zh, f'**{zh}**')
        js += f", example: '{example_en}', example_cn: '{example_cn}'"
    js += " },"
    new_js.append(js)

print(f"Second batch: added {total_added}, skipped {skipped} (already existed)")

# ── Insert before "];" at end of WORD_BANK ──
insert_pos = content.rfind("];\n\n/* Build lookup Map */")
if insert_pos < 0:
    insert_pos = content.rfind("];")

new_block = "\n" + "\n".join(new_js) + "\n"
modified = content[:insert_pos] + new_block + content[insert_pos:]

with open(WORKBANK_PATH, 'w', encoding='utf-8') as f:
    f.write(modified)

# ── Final count ──
final_count = len(re.findall(r"\{\s*zh:\s*'", modified))
print(f"Final entry count: {final_count}")
print(f"Done! File written to {WORKBANK_PATH}")
