import re, os

FILE = os.path.expanduser('~/IFLL-Web/src/lib/wordbank.js')

with open(FILE, 'r', encoding='utf-8') as f:
    text = f.read()

existing_zh = set(re.findall(r"zh:\s*'([^']+)'", text))
print(f'Existing: {len(existing_zh)} entries')

# Compact new entries
new_raw = [
('安排','arrange','to organize','cet4','verb'),
('安慰','comfort','to soothe','cet4','verb'),
('安装','install','to set up','cet4','verb'),
('把握','grasp','to seize','cet4','verb'),
('包含','include','to contain','cet4','verb'),
('保留','reserve','to keep','cet4','verb'),
('报道','report','to cover news','cet4','noun'),
('抱怨','complain','to express grievance','cet4','verb'),
('背景','background','context','cet4','noun'),
('被动','passive','not active','cet4','adj'),
('彼此','mutual','reciprocal','cet4','adj'),
('毕竟','afterall','ultimately','cet4','adv'),
('边缘','edge','boundary','cet4','noun'),
('变革','reform','radical change','cet6','noun'),
('辩论','debate','formal argument','cet6','noun'),
('表达','express','to convey','cet4','verb'),
('表面','surface','outer layer','cet4','noun'),
('表明','indicate','to show clearly','cet4','verb'),
('并且','moreover','in addition','cet4','conj'),
('播放','broadcast','to air media','cet4','verb'),
('补充','supplement','to add extra','cet4','verb'),
('不安','uneasy','anxious','cet4','adj'),
('不断','constant','unceasing','cet4','adj'),
('不管','despite','regardless','cet4','conj'),
('不良','harmful','not good','cet4','adj'),
('不然','otherwise','or else','cet4','adv'),
('参与','participate','to take part','cet4','verb'),
('灿烂','splendid','very bright','cet4','adj'),
('超过','exceed','to surpass','cet4','verb'),
('迟到','late','after expected time','daily','adj'),
('冲突','conflict','a disagreement','cet4','noun'),
('充分','sufficient','enough','cet4','adj'),
('充满','full','filled with','cet4','adj'),
('崇拜','worship','to admire deeply','cet4','verb'),
('崇高','noble','high moral','cet6','adj'),
('处罚','punish','to penalize','cet4','verb'),
('处理','process','to handle','cet4','verb'),
('传播','spread','to distribute','cet4','verb'),
('传达','convey','to communicate','cet4','verb'),
('传统','tradition','long-established','cet4','noun'),
('创新','innovate','to introduce new','cet4','verb'),
('创业','startup','to start business','cet4','verb'),
('创造','create','to bring into being','cet4','verb'),
('纯洁','pure','morally clean','cet4','adj'),
('刺激','stimulate','to excite','cet4','verb'),
('聪明','smart','quick-witted','cet4','adj'),
('促进','promote','to advance','cet4','verb'),
('脆弱','fragile','easily broken','cet4','adj'),
('答应','promise','to agree to do','cet4','verb'),
('达到','achieve','to reach a goal','cet4','verb'),
('打断','interrupt','to break in','cet4','verb'),
('打算','plan','to intend','cet4','verb'),
('大胆','bold','not afraid','cet4','adj'),
('单纯','simple','not complicated','cet4','adj'),
('单调','monotonous','lacking variety','cet4','adj'),
('但是','however','nevertheless','cet4','conj'),
('担心','worry','to be anxious','cet4','verb'),
('单词','vocabulary','a word','cet4','noun'),
('道德','moral','right and wrong','cet4','adj'),
('道理','reason','a rational basis','cet4','noun'),
('登记','register','to record officially','cet4','verb'),
('等待','wait','to stay in expectation','cet4','verb'),
('的确','indeed','truly','cet4','adv'),
('敌人','enemy','an opponent','cet4','noun'),
('抵达','arrive','to reach a place','cet4','verb'),
('抵抗','resist','to oppose','cet4','verb'),
('调查','investigate','to examine thoroughly','cet4','verb'),
('丢失','lose','to misplace','cet4','verb'),
('独立','independent','self-reliant','cet4','adj'),
('独特','distinctive','having unique quality','cet4','adj'),
('短暂','brief','short in duration','cet4','adj'),
('对比','contrast','to compare','cet4','verb'),
('对待','treat','to behave toward','cet4','verb'),
('对手','opponent','a rival','cet4','noun'),
('兑换','exchange','to swap currency','cet4','verb'),
('多么','how','to what extent','cet4','adv'),
('额外','extra','beyond the usual','cet4','adj'),
('恶劣','harsh','very bad','cet4','adj'),
('而且','furthermore','in addition','cet4','conj'),
('发表','publish','to make public','cet4','verb'),
('发布','release','to issue officially','cet4','verb'),
('发达','developed','advanced','cet4','adj'),
('发动','launch','to start','cet4','verb'),
('发抖','shiver','to tremble','cet4','verb'),
('发挥','utilize','to bring into play','cet4','verb'),
('发明','invent','to create something','cet4','verb'),
('发生','happen','to take place','cet4','verb'),
('发现','discover','to find unexpectedly','cet4','verb'),
('发展','develop','to grow','cet4','verb'),
('罚款','fine','a monetary penalty','cet4','noun'),
('繁荣','flourish','to thrive','cet4','verb'),
('反而','instead','contrary to expectation','cet4','adv'),
('反复','repeat','to do again','cet4','verb'),
('反应','reaction','a response','cet4','noun'),
('反映','reflect','to show an image','cet4','verb'),
('反正','anyway','regardless','cet4','adv'),
('范围','scope','the extent','cet4','noun'),
('方案','scheme','a specific plan','cet4','noun'),
('方便','convenient','easy and suitable','cet4','adj'),
('方向','direction','a course','cet4','noun'),
('放松','relax','to become less tense','cet4','verb'),
('飞机','airplane','an aircraft','cet4','noun'),
('飞跃','leap','a sudden advance','cet6','verb'),
('肥皂','soap','cleaning agent','daily','noun'),
('废物','waste','useless material','cet4','noun'),
('分明','distinct','clearly separate','cet4','adj'),
('分配','allocate','to distribute','cet4','verb'),
('分析','analyze','to examine in detail','cet4','verb'),
('分享','share','to enjoy together','cet4','verb'),
('愤怒','angry','feeling strong displeasure','cet4','adj'),
('风格','style','a distinctive manner','cet4','noun'),
('疯狂','crazy','mentally deranged','cet4','adj'),
('否定','negate','to deny','cet4','verb'),
('否认','disclaim','to refuse to accept','cet4','verb'),
('夫妇','couple','a married pair','cet4','noun'),
('服务','service','work done for others','cet4','noun'),
('符合','conform','to match requirements','cet4','verb'),
('辅导','tutor','to give private lessons','cet4','verb'),
('付款','pay','to give money','cet4','verb'),
('负责','responsible','having a duty','cet4','adj'),
('附近','nearby','close by','cet4','adj'),
('复杂','complex','not simple','cet4','adj'),
('复制','copy','to make a duplicate','cet4','verb'),
('改变','change','to make different','cet4','verb'),
('改革','reform','to make improvements','cet4','verb'),
('改进','improve','to make better','cet4','verb'),
('改造','transform','to change fundamentally','cet4','verb'),
('感动','touched','emotionally affected','cet4','adj'),
('感激','grateful','feeling thanks','cet4','adj'),
('感觉','sensation','a physical feeling','cet4','noun'),
('感情','emotion','a strong feeling','cet4','noun'),
('感受','experience','to undergo','cet4','verb'),
('钢铁','steel','a strong metal','cet4','noun'),
('港口','port','a harbor','cet4','noun'),
('高超','excellent','extremely good','cet4','adj'),
('告别','farewell','to say goodbye','cet4','verb'),
('告诉','inform','to make known','cet4','verb'),
('歌唱','sing','to produce musical sounds','cet4','verb'),
('革命','revolution','a radical change','cet4','noun'),
('隔离','isolate','to separate','cet6','verb'),
('个别','individual','separate','cet4','adj'),
('个人','personal','of a particular person','cet4','adj'),
('个体','individual','a single entity','cet4','noun'),
('各式','various','different kinds','cet4','adj'),
('根本','fundamental','basic and essential','cet4','adj'),
('更加','further','to a greater extent','cet4','adv'),
('工程','engineering','applied science','cet4','noun'),
('工具','tool','a device for work','cet4','noun'),
('工人','worker','a person who works','cet4','noun'),
('工业','industry','economic production','cet4','noun'),
('工资','wage','payment for work','cet4','noun'),
('攻击','attack','to take offensive action','cet4','verb'),
('巩固','consolidate','to make stronger','cet4','verb'),
('共计','total','the complete amount','cet4','noun'),
('共同','common','shared by all','cet4','adj'),
('贡献','contribute','to give towards','cet4','verb'),
('构成','constitute','to form','cet4','verb'),
('构造','structure','a built arrangement','cet4','noun'),
('估计','estimate','to approximate','cet4','verb'),
('鼓励','encourage','to give confidence','cet4','verb'),
('鼓舞','inspire','to fill with motivation','cet4','verb'),
('固定','fixed','not moving','cet4','adj'),
('固然','admittedly','it is true','cet4','adv'),
('故障','fault','a malfunction','cet4','noun'),
('顾客','customer','a buyer','cet4','noun'),
('顾问','consultant','an expert advisor','cet4','noun'),
('关怀','care','to show concern','cet4','verb'),
('关键','key','of crucial importance','cet4','adj'),
('关闭','close','to shut','cet4','verb'),
('关系','relation','a connection','cet4','noun'),
('关于','about','concerning','cet4','prep'),
('观察','observe','to watch closely','cet4','verb'),
('观点','viewpoint','a particular attitude','cet4','noun'),
('观众','audience','the assembled viewers','cet4','noun'),
('管理','manage','to be in charge','cet4','verb'),
('冠军','champion','the best in competition','cet4','noun'),
('光荣','honor','high respect','cet4','noun'),
('广阔','vast','immense in area','cet4','adj'),
('规划','planning','the process of designing','cet4','noun'),
('规律','regularity','a consistent pattern','cet4','noun'),
('规模','scale','the extent of activity','cet4','noun'),
('规则','regulation','an authoritative rule','cet4','noun'),
('国防','defense','national armed protection','cet4','noun'),
('果实','fruit','the product of a plant','cet4','noun'),
('过程','process','a series of actions','cet4','noun'),
('过度','excessive','too much','cet4','adj'),
('过渡','transition','a change of state','cet4','noun'),
('还是','still','nevertheless','cet4','adv'),
('海关','customs','border inspection','cet4','noun'),
('海洋','ocean','the vast sea','cet4','noun'),
('害羞','shy','timid socially','cet4','adj'),
('含义','meaning','the intended sense','cet4','noun'),
('罕见','rare','seldom occurring','cet4','adj'),
('行业','industry','a branch of business','cet4','noun'),
('航班','flight','a scheduled trip','cet4','noun'),
('航空','aviation','air travel','cet4','noun'),
('显然','apparent','clearly evident','cet4','adv'),
('显著','notable','worthy of notice','cet4','adj'),
('现场','scene','the actual location','cet4','noun'),
('现代','modern','of the present time','cet4','adj'),
('现实','reality','the state of things','cet4','noun'),
('现象','phenomenon','an observable fact','cet4','noun'),
('限度','limit','the ultimate boundary','cet4','noun'),
('限制','restrict','to keep within bounds','cet4','verb'),
('相比','compare','to examine differences','cet4','verb'),
('相当','quite','reasonably','cet4','adv'),
('相对','relative','considered in relation','cet4','adj'),
('相反','opposite','completely different','cet4','adj'),
('相关','relevant','related to the matter','cet4','adj'),
('相互','mutual','reciprocal','cet4','adj'),
('相似','similar','having likeness','cet4','adj'),
('象征','symbolize','to represent','cet4','verb'),
('消费','consume','to use up','cet4','verb'),
('消耗','consume','to expend resources','cet4','verb'),
('消灭','eliminate','to remove completely','cet4','verb'),
('消失','disappear','to cease to be visible','cet4','verb'),
('销售','sell','to offer for purchase','cet4','verb'),
('消息','news','newly received information','cet4','noun'),
('小心','careful','cautious','cet4','adj'),
('效果','effect','a result','cet4','noun'),
('效率','efficiency','the ratio of output','cet4','noun'),
('协议','agreement','a negotiated understanding','cet4','noun'),
('协作','collaborate','to work together','cet4','verb'),
('写作','write','to compose text','cet4','verb'),
('心理','psychology','the study of the mind','cet4','noun'),
('心情','mood','emotional state','cet4','noun'),
('辛苦','hard','demanding great effort','cet4','adj'),
('信任','trust','to rely upon','cet4','verb'),
('信息','information','facts and data','cet4','noun'),
('信心','confidence','a feeling of certainty','cet4','noun'),
('形成','form','to take shape','cet4','verb'),
('形式','form','the shape or structure','cet4','noun'),
('形势','situation','the state of affairs','cet4','noun'),
('形象','image','a visual representation','cet4','noun'),
('形状','shape','the outer form','cet4','noun'),
('行动','action','a deed','cet4','noun'),
('行为','behavior','the way one acts','cet4','noun'),
('幸福','happiness','a state of well-being','cet4','noun'),
('性格','personality','distinctive character','cet4','noun'),
('修建','build','to erect a structure','cet4','verb'),
('修理','repair','to fix','cet4','verb'),
('休息','rest','to cease activity','cet4','verb'),
('修改','modify','to change partly','cet4','verb'),
('需要','need','to require','cet4','verb'),
('宣布','declare','to announce formally','cet4','verb'),
('宣传','publicize','to promote','cet4','verb'),
('学历','education','schooling level','cet4','noun'),
('学生','student','a learner','cet4','noun'),
('学术','academic','relating to study','cet4','adj'),
('学习','learn','to gain knowledge','cet4','verb'),
('训练','train','to teach a skill','cet4','verb'),
('迅速','rapid','very quick','cet4','adj'),
('压力','pressure','a pressing force','cet4','noun'),
('严格','strict','demanding exact compliance','cet4','adj'),
('严肃','serious','grave and stern','cet4','adj'),
('延长','extend','to lengthen','cet4','verb'),
('延伸','stretch','to extend further','cet4','verb'),
('延误','delay','to make late','cet4','verb'),
('研究','research','systematic investigation','cet4','noun'),
('眼泪','tears','drops from the eyes','cet4','noun'),
('眼睛','eye','the organ of sight','cet4','noun'),
('要求','require','to demand','cet4','verb'),
('邀请','invite','to ask ones presence','cet4','verb'),
('业务','business','commercial activity','cet4','noun'),
('医疗','medical','relating to medicine','cet4','adj'),
('医生','doctor','a medical professional','cet4','noun'),
('医学','medicine','the science of healing','cet4','noun'),
('医院','hospital','a medical facility','cet4','noun'),
('依靠','depend','to rely on','cet4','verb'),
('移动','move','to change position','cet4','verb'),
('移民','immigrate','to move to another country','cet4','verb'),
('疑问','doubt','a feeling of uncertainty','cet4','noun'),
('以及','alongwith','together with','cet4','conj'),
('以来','since','from a past time','cet4','prep'),
('以前','before','at an earlier time','cet4','adv'),
('意外','accident','an unforeseen event','cet4','noun'),
('因此','therefore','consequently','cet4','conj'),
('因而','thus','as a result','cet4','conj'),
('因素','factor','a contributing element','cet4','noun'),
('因为','because','for the reason that','cet4','conj'),
('音响','speaker','audio device','daily','noun'),
('引导','guide','to lead the way','cet4','verb'),
('引进','introduce','to bring from elsewhere','cet4','verb'),
('引起','cause','to bring about','cet4','verb'),
('印象','impression','an effect on the mind','cet4','noun'),
('营养','nutrition','the food needed for growth','cet4','noun'),
('营业','operate','to run a business','cet4','verb'),
('影片','film','a motion picture','cet4','noun'),
('影响','influence','an effect on behavior','cet4','noun'),
('拥挤','crowded','filled with people','cet4','adj'),
('拥有','possess','to have','cet4','verb'),
('勇敢','brave','courageous','cet4','adj'),
('勇气','courage','ability to face danger','cet4','noun'),
('用户','user','a person who uses','cet4','noun'),
('优点','merit','a good point','cet4','noun'),
('优惠','discount','a special price reduction','cet4','noun'),
('优势','advantage','a favorable condition','cet4','noun'),
('优先','priority','a right to go before','cet4','noun'),
('优秀','excellent','outstandingly good','cet4','adj'),
('幽默','humor','the ability to amuse','cet4','noun'),
('尤其','especially','particularly','cet4','adv'),
('由于','dueto','because of','cet4','conj'),
('游览','tour','to travel around','cet4','verb'),
('友谊','friendship','mutual affection','cet4','noun'),
('有关','related','having a connection','cet4','adj'),
('有利','favorable','giving an advantage','cet4','adj'),
('有趣','interesting','arousing curiosity','cet4','adj'),
('有时','sometimes','on certain occasions','cet4','adv'),
('有限','limited','confined within bounds','cet4','adj'),
('有效','effective','producing desired result','cet4','adj'),
('幼稚','immature','not mature','cet4','adj'),
('于是','thereupon','as a result then','cet4','conj'),
('愉快','pleasant','giving pleasure','cet4','adj'),
('愚蠢','stupid','lacking intelligence','cet4','adj'),
('预测','predict','to forecast','cet4','verb'),
('预防','prevent','to stop before happening','cet4','verb'),
('预算','budget','an estimate of income','cet4','noun'),
('遇到','encounter','to come across','cet4','verb'),
('原来','originally','in the beginning','cet4','adv'),
('原谅','forgive','to pardon','cet4','verb'),
('原因','reason','the grounds for something','cet4','noun'),
('原则','principle','a fundamental rule','cet4','noun'),
('愿望','wish','a desired outcome','cet4','noun'),
('愿意','willing','ready to do','cet4','adj'),
('阅读','read','to look at and understand','cet4','verb'),
('运输','transport','to carry goods','cet4','verb'),
('运行','run','to be in operation','cet4','verb'),
('灾难','disaster','a sudden calamity','cet4','noun'),
('再见','goodbye','a farewell','daily','interj'),
('在乎','care','to be concerned about','cet4','verb'),
('暂时','temporary','for a short time','cet4','adj'),
('赞成','approve','to be in favor of','cet4','verb'),
('赞美','praise','to express admiration','cet4','verb'),
('糟糕','awful','very unpleasant','cet4','adj'),
('早晨','morning','the early part of day','daily','noun'),
('造成','cause','to bring about','cet4','verb'),
('责任','responsibility','a duty','cet4','noun'),
('增加','increase','to add in quantity','cet4','verb'),
('增强','enhance','to make stronger','cet4','verb'),
('增长','grow','to increase in size','cet4','verb'),
('占据','occupy','to take up space','cet4','verb'),
('战斗','battle','a fight','cet4','noun'),
('战胜','defeat','to win over','cet4','verb'),
('战争','war','armed conflict','cet4','noun'),
('掌握','master','to have thorough knowledge','cet4','verb'),
('招聘','recruit','to hire new staff','cet4','verb'),
('哲学','philosophy','the study of knowledge','cet4','noun'),
('针对','target','to aim at','cet4','verb'),
('振动','vibrate','to move back and forth','cet4','verb'),
('征服','conquer','to overcome','cet4','verb'),
('征求','solicit','to ask for opinions','cet4','verb'),
('争论','argue','to exchange differing views','cet4','verb'),
('整理','organize','to arrange neatly','cet4','verb'),
('正常','normal','standard','cet4','adj'),
('正式','formal','officially recognized','cet4','adj'),
('政策','policy','a course of action','cet4','noun'),
('政府','government','the governing body','cet4','noun'),
('政治','politics','the activities of government','cet4','noun'),
('症状','symptom','a sign of illness','cet4','noun'),
('支持','support','to stand behind','cet4','verb'),
('支出','expense','money paid out','cet4','noun'),
('支付','pay','to give money','cet4','verb'),
('知识','knowledge','information gained','cet4','noun'),
('执行','execute','to carry out','cet4','verb'),
('直接','direct','straight without interruption','cet4','adj'),
('值得','worth','deserving of','cet4','adj'),
('职业','career','a line of work','cet4','noun'),
('植物','plant','a living organism','cet4','noun'),
('指标','target','a goal to aim for','cet4','noun'),
('指导','guide','to direct','cet4','verb'),
('指定','designate','to appoint specifically','cet4','verb'),
('指挥','command','to direct an action','cet4','verb'),
('制度','system','a set of rules','cet4','noun'),
('制造','manufacture','to make on a large scale','cet4','verb'),
('治理','govern','to control and manage','cet4','verb'),
('治疗','treat','to provide medical care','cet4','verb'),
('中断','interrupt','to break continuity','cet4','verb'),
('中心','center','the midpoint','cet4','noun'),
('种类','kind','a category','cet4','noun'),
('重大','significant','great in importance','cet4','adj'),
('重点','emphasis','special attention','cet4','noun'),
('重量','weight','the heaviness','cet4','noun'),
('重视','value','to regard as important','cet4','verb'),
('重要','important','of great significance','cet4','adj'),
('周末','weekend','the end of the week','daily','noun'),
('周围','surrounding','the immediate area','cet4','noun'),
('主要','main','most important','cet4','adj'),
('主意','idea','a plan or thought','cet4','noun'),
('主张','advocate','to hold an opinion','cet4','verb'),
('住所','dwelling','a place of residence','cet4','noun'),
('抓住','grasp','to seize firmly','cet4','verb'),
('专家','expert','a specialist','cet4','noun'),
('专门','specially','specifically','cet4','adv'),
('专业','major','a field of study','cet4','noun'),
('转变','transform','to change form','cet4','verb'),
('转移','transfer','to move to another place','cet4','verb'),
('装饰','decorate','to make more attractive','cet4','verb'),
('追求','pursue','to follow with aim','cet4','verb'),
('准备','prepare','to make ready','cet4','verb'),
('准确','accurate','free from error','cet4','adj'),
('准时','punctual','on time','cet4','adj'),
('资源','resource','a stock or supply','cet4','noun'),
('自动','automatic','acting by itself','cet4','adj'),
('自然','nature','the physical world','cet4','noun'),
('自由','freedom','the power to act freely','cet4','noun'),
('自愿','voluntary','of ones own free will','cet4','adj'),
('综合','comprehensive','including everything','cet4','adj'),
('总结','summarize','to give a summary','cet4','verb'),
('总理','premier','the head of government','cet4','noun'),
('走廊','corridor','a long passage','cet4','noun'),
('足够','enough','sufficient','cet4','adj'),
('足球','soccer','a ball game','daily','noun'),
('阻碍','hinder','to block progress','cet4','verb'),
('阻止','prevent','to stop from happening','cet4','verb'),
('组成','compose','to form by putting together','cet4','verb'),
('组织','organize','to arrange systematically','cet4','verb'),
('最初','initial','first','cet4','adj'),
('最后','final','last','cet4','adj'),
('最近','recent','not long past','cet4','adj'),
('尊敬','respect','to hold in high regard','cet4','verb'),
('尊重','honor','to treat with respect','cet4','verb'),
('遵守','obey','to follow rules','cet4','verb'),
]

cat_map = {'noun':'noun,名词', 'verb':'verb,动词', 'adj':'adjective,形容词', 'adv':'adverb,副词', 'conj':'conjunction,连词', 'prep':'preposition,介词', 'interj':'interjection,感叹词'}

pos_cn_map = {'noun':'名词', 'verb':'动词', 'adj':'形容词', 'adv':'副词', 'conj':'连词', 'prep':'介词', 'interj':'感叹词'}

new_lines = []
for zh, en, defn, level, pos in new_raw:
    if zh in existing_zh:
        continue
    pos_cn = pos_cn_map.get(pos, '名词')
    cat = pos
    new_lines.append(f"  {{ zh: '{zh}', en: '{en}', def: '{defn}', level: '{level}', cat: '{cat}', pos: '{pos}', pos_cn: '{pos_cn}' }},")
    existing_zh.add(zh)

print(f'Adding {len(new_lines)} new entries')

# Find end of WORD_BANK
insert_marker = "];\n\n/* Build lookup Map"
idx = text.rfind(insert_marker)
appended = '\n' + '\n'.join(new_lines) + '\n'
new_text = text[:idx] + ',' + appended + text[idx:]

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(new_text)

final = len(re.findall(r"zh:\s*'([^']+)'", new_text))
print(f'Total entries: {final}')
result = os.system('node --check ' + FILE + ' 2>&1')
print('✅ syntax OK' if result == 0 else '❌ syntax error')
