#!/usr/bin/env python3
"""
IFLL Word Bank Expansion - Batch 2
Adds ~700 more entries and adds example sentences to achieve ~60% coverage.
"""

import re
import os

WORKBANK_PATH = os.path.join(os.path.dirname(__file__), 'src/lib/wordbank.js')

def pos_from_cat(cat):
    mapping = {
        'verb': ('verb', '动词'),
        'adj': ('adjective', '形容词'),
        'adverb': ('adverb', '副词'),
        'logic': ('conjunction', '连词'),
    }
    return mapping.get(cat, ('noun', '名词'))

def make_entry(zh, en, defn, level, cat, example_en=None, example_cn=None):
    zh = zh.replace("'", "\\'")
    en = en.replace("'", "\\'")
    defn = defn.replace("'", "\\'")
    pos, pos_cn = pos_from_cat(cat)
    parts = [
        f"  {{ zh: '{zh}', en: '{en}', def: '{defn}', level: '{level}', cat: '{cat}', pos: '{pos}', pos_cn: '{pos_cn}'"
    ]
    if example_en and example_cn:
        example_en_s = example_en.replace("'", "\\'")
        example_cn_s = example_cn.replace("'", "\\'")
        parts[0] += f", example: '{example_en_s}', example_cn: '{example_cn_s}'"
    parts[0] += " }"
    return parts[0]

# ── ~700 new entries ──
BATCH2_WORDS = [
    # Mandarin complements / particles / grammar words (~50)
    ('着', '-ing', 'indicates ongoing action', 'daily', 'adverb'),
    ('了', 'past tense marker', 'indicates completed action', 'daily', 'adverb'),
    ('过', 'experiential suffix', 'indicates past experience', 'daily', 'adverb'),
    ('的', 'possessive particle', 'indicates possession or modification', 'daily', 'adverb'),
    ('地', 'adverbial particle', 'turns adjectives into adverbs', 'daily', 'adverb'),
    ('得', 'complement particle', 'links verb to degree complement', 'daily', 'adverb'),
    ('把', 'disposal marker', 'marks the object of a verb', 'daily', 'adverb'),
    ('被', 'passive marker', 'marks the agent in a passive sentence', 'cet4', 'adverb'),
    ('比', 'compare', 'used in comparative structures', 'daily', 'adverb'),
    ('跟', 'with', 'together with someone', 'daily', 'adverb'),
    ('为', 'for', 'for the sake of', 'cet4', 'adverb'),
    ('从', 'from', 'starting from a point', 'daily', 'adverb'),
    ('向', 'toward', 'in the direction of', 'daily', 'adverb'),
    ('往', 'toward', 'moving in a direction', 'daily', 'adverb'),
    ('在', 'at/in', 'at a location or time', 'daily', 'adverb'),
    ('和', 'and', 'connecting two items', 'daily', 'logic'),
    ('与', 'and/with', 'used to connect items formally', 'cet4', 'logic'),
    ('及', 'and/as well as', 'along with', 'cet4', 'logic'),
    ('同', 'same as', 'identical to', 'cet4', 'adverb'),
    ('由', 'by/from', 'indicating agent or origin', 'cet4', 'adverb'),
    ('以', 'in order to', 'for the purpose of', 'cet4', 'adverb'),
    ('于', 'in/at/on', 'indicating time, place or direction', 'cet4', 'adverb'),
    ('就', 'right away', 'immediately or precisely', 'daily', 'adverb'),
    ('才', 'only then', 'not until a certain condition', 'daily', 'adverb'),
    ('再', 'again', 'another time', 'daily', 'adverb'),
    ('又', 'again', 'once more (already happened)', 'daily', 'adverb'),
    ('还', 'still/yet', 'continuing up to a point', 'daily', 'adverb'),
    ('也', 'also', 'in addition', 'daily', 'adverb'),
    ('都', 'all', 'every one of', 'daily', 'adverb'),
    ('只', 'only', 'no more than', 'daily', 'adverb'),
    ('很', 'very', 'to a great degree', 'daily', 'adverb'),
    ('太', 'too', 'excessively', 'daily', 'adverb'),
    ('更', 'more', 'to a greater degree', 'daily', 'adverb'),
    ('最', 'most', 'to the greatest degree', 'daily', 'adverb'),
    ('越', 'more and more', 'increasingly', 'daily', 'adverb'),
    ('真', 'really', 'truly', 'daily', 'adverb'),
    ('刚', 'just', 'very recently', 'daily', 'adverb'),
    ('正', 'just/right', 'exactly at a point', 'daily', 'adverb'),
    ('总', 'always', 'all the time', 'daily', 'adverb'),
    ('常', 'often', 'frequently', 'daily', 'adverb'),
    ('每', 'every', 'each one', 'daily', 'adverb'),
    ('各', 'each', 'every individual', 'daily', 'adverb'),
    ('别', 'don\'t', 'do not', 'daily', 'adverb'),
    ('莫', 'do not', 'prohibition marker', 'graduate', 'adverb'),
    ('约', 'approximately', 'roughly estimated', 'daily', 'adverb'),
    ('可', 'can/may', 'expressing possibility', 'daily', 'adverb'),
    ('会', 'will/can', 'expressing future or ability', 'daily', 'adverb'),
    ('能', 'can/be able', 'having the ability to', 'daily', 'adverb'),
    ('必须', 'must', 'absolutely necessary', 'daily', 'adverb'),
    ('应该', 'should', 'expected or obligated to', 'daily', 'adverb'),
    ('可以', 'may/can', 'permitted or able', 'daily', 'adverb'),
    ('愿意', 'willing', 'ready to do something', 'daily', 'verb'),
    ('敢', 'dare', 'have the courage to', 'daily', 'verb'),
    ('可能', 'maybe', 'expressing possibility', 'daily', 'adverb'),
    ('一定', 'certainly', 'without doubt', 'daily', 'adverb'),
    
    # More HSK/CET items (~150)
    ('爱好', 'hobby', 'an activity done regularly for pleasure', 'daily', 'daily'),
    ('安静', 'quiet', 'making little noise', 'daily', 'adj'),
    ('比较', 'relatively', 'to a certain degree', 'daily', 'adverb'),
    ('比赛', 'competition', 'a contest between rivals', 'cet4', 'daily'),
    ('必须', 'must', 'be obliged to', 'daily', 'adverb'),
    ('变化', 'change', 'the act of becoming different', 'cet4', 'verb'),
    ('表演', 'performance', 'a presentation before an audience', 'cet4', 'daily'),
    ('表扬', 'praise', 'to express approval', 'daily', 'verb'),
    ('不但', 'not only', 'not merely', 'daily', 'logic'),
    ('参观', 'visit', 'to go and see a place', 'cet4', 'verb'),
    ('操场', 'playground', 'an outdoor area for physical activity', 'daily', 'daily'),
    ('成绩', 'achievement', 'a result obtained by effort', 'cet4', 'daily'),
    ('城市', 'city', 'a large and important town', 'cet4', 'daily'),
    ('迟到', 'be late', 'to arrive after the expected time', 'daily', 'verb'),
    ('出发', 'depart', 'to set out on a journey', 'cet4', 'verb'),
    ('出生', 'be born', 'to come into the world', 'cet4', 'verb'),
    ('窗户', 'window', 'an opening in a wall with glass', 'daily', 'daily'),
    ('词典', 'dictionary', 'a book listing words alphabetically', 'daily', 'daily'),
    ('聪明', 'clever', 'quick to understand and learn', 'daily', 'adj'),
    ('打算', 'plan', 'an intention or decision', 'cet4', 'verb'),
    ('打着', 'hit', 'to strike with force', 'daily', 'verb'),
    ('大家', 'everyone', 'all people present', 'daily', 'daily'),
    ('但是', 'but', 'used to introduce a contrasting idea', 'daily', 'logic'),
    ('当然', 'of course', 'as one would expect', 'daily', 'adverb'),
    ('地方', 'place', 'a particular area or location', 'cet4', 'daily'),
    ('地铁', 'subway', 'an underground electric railway', 'daily', 'daily'),
    ('地图', 'map', 'a representation of an area', 'daily', 'daily'),
    ('电话', 'telephone', 'a device for transmitting voice', 'daily', 'daily'),
    ('电脑', 'computer', 'an electronic device for processing data', 'cet4', 'tech'),
    ('电视', 'television', 'a device for receiving broadcast signals', 'daily', 'daily'),
    ('电影', 'film', 'a story recorded as moving images', 'daily', 'daily'),
    ('东西', 'thing', 'an object or entity', 'daily', 'daily'),
    ('动物', 'animal', 'a living organism other than plants', 'daily', 'nature'),
    ('多么', 'how', 'to what extent', 'daily', 'adverb'),
    ('儿童', 'child', 'a young human being', 'daily', 'daily'),
    ('而且', 'moreover', 'in addition', 'daily', 'logic'),
    ('发生', 'happen', 'to take place', 'cet4', 'verb'),
    ('方便', 'convenient', 'fitting in well with needs', 'cet4', 'adj'),
    ('放心', 'rest assured', 'to set one\'s mind at ease', 'daily', 'verb'),
    ('非常', 'extremely', 'to a very great degree', 'daily', 'adverb'),
    ('分钟', 'minute', 'a unit of time equal to 60 seconds', 'daily', 'daily'),
    ('辅导', 'tutor', 'to give individual teaching', 'cet4', 'verb'),
    ('附近', 'nearby', 'close in distance', 'daily', 'adverb'),
    ('复习', 'review', 'to study again', 'daily', 'verb'),
    ('干净', 'clean', 'free from dirt', 'daily', 'adj'),
    ('赶快', 'hurry', 'to act quickly', 'daily', 'adverb'),
    ('感冒', 'cold', 'a common viral infection', 'daily', 'daily'),
    ('刚刚', 'just now', 'a very short time ago', 'daily', 'adverb'),
    ('根据', 'according to', 'on the basis of', 'cet4', 'adverb'),
    ('更加', 'even more', 'to a greater extent', 'cet4', 'adverb'),
    ('公共', 'public', 'open to everyone', 'cet4', 'adj'),
    ('公斤', 'kilogram', 'a unit of mass equal to 1000 grams', 'daily', 'daily'),
    ('公司', 'company', 'a business organization', 'cet4', 'business'),
    ('共同', 'common', 'shared by two or more', 'cet4', 'adj'),
    ('故事', 'story', 'a narrative of events', 'daily', 'daily'),
    ('关系', 'relationship', 'the way people or things connect', 'cet4', 'abstract'),
    ('关心', 'care about', 'to show interest in', 'cet4', 'verb'),
    ('关于', 'regarding', 'on the subject of', 'cet4', 'adverb'),
    ('管理', 'manage', 'to be in charge of', 'cet4', 'verb'),
    ('广播', 'broadcast', 'a radio or TV program', 'cet4', 'daily'),
    ('果然', 'indeed', 'as expected', 'cet4', 'adverb'),
    ('过程', 'course', 'the way something proceeds', 'cet4', 'abstract'),
    ('海洋', 'sea', 'a vast expanse of salt water', 'cet4', 'nature'),
    ('合格', 'qualified', 'meeting the required standards', 'cet4', 'adj'),
    ('合作', 'work together', 'to join in a common effort', 'cet4', 'verb'),
    ('红色', 'red', 'the color of blood', 'daily', 'daily'),
    ('后果', 'consequence', 'a result of a previous action', 'cet4', 'abstract'),
    ('忽然', 'suddenly', 'quickly and unexpectedly', 'cet4', 'adverb'),
    ('互相', 'mutually', 'each other', 'cet4', 'adverb'),
    ('花朵', 'blossom', 'a flower or bloom', 'daily', 'nature'),
    ('怀念', 'miss', 'to think of with affection', 'cet4', 'verb'),
    ('怀疑', 'suspect', 'to doubt the truth of', 'cet4', 'verb'),
    ('活泼', 'lively', 'full of energy and vitality', 'cet4', 'adj'),
    ('机关', 'institution', 'an organizational structure', 'cet6', 'abstract'),
    ('积极', 'active', 'engaging in positive action', 'cet4', 'adj'),
    ('基本', 'basic', 'forming an essential foundation', 'cet4', 'adj'),
    ('基础', 'bases', 'the foundation of a system', 'cet4', 'abstract'),
    ('激动', 'excited', 'feeling strong emotion', 'cet4', 'emotion'),
    ('及时', 'timely', 'done at the right time', 'cet4', 'adj'),
    ('即使', 'even if', 'used to introduce a hypothetical', 'cet4', 'logic'),
    ('计划', 'plan', 'a detailed proposal for doing something', 'cet4', 'abstract'),
    ('记录', 'record', 'to preserve in writing', 'cet4', 'verb'),
    ('技术', 'technology', 'the application of scientific knowledge', 'cet4', 'tech'),
    ('寂寞', 'lonely', 'sad from lack of company', 'cet4', 'emotion'),
    ('加强', 'strengthen', 'to make stronger', 'cet4', 'verb'),
    ('家乡', 'hometown', 'the place of one\'s birth', 'daily', 'daily'),
    ('坚持', 'persist', 'to continue steadfastly', 'cet4', 'verb'),
    ('坚决', 'resolute', 'firm and unwavering', 'cet4', 'adj'),
    ('艰苦', 'arduous', 'demanding great effort', 'cet6', 'adj'),
    ('检查', 'inspect', 'to examine thoroughly', 'cet4', 'verb'),
    ('简单', 'simple', 'easily understood', 'cet4', 'adj'),
    ('建立', 'establish', 'to set up or create', 'cet4', 'verb'),
    ('建议', 'suggest', 'to put forward for consideration', 'cet4', 'verb'),
    ('建筑', 'building', 'a structure with walls and a roof', 'cet4', 'daily'),
    ('将来', 'future', 'the time yet to come', 'cet4', 'abstract'),
    ('奖励', 'reward', 'something given in recognition', 'cet4', 'daily'),
    ('交通', 'traffic', 'the movement of vehicles', 'cet4', 'daily'),
    ('教室', 'classroom', 'a room for teaching', 'daily', 'daily'),
    ('教授', 'professor', 'a senior academic teacher', 'cet4', 'academic'),
    ('教育', 'educate', 'to teach or instruct', 'cet4', 'verb'),
    ('接受', 'accept', 'to receive willingly', 'cet4', 'verb'),
    ('节约', 'save', 'to use less of a resource', 'cet4', 'verb'),
    ('解放', 'liberate', 'to set free', 'cet6', 'verb'),
    ('解决', 'solve', 'to find a solution', 'cet4', 'verb'),
    ('解释', 'explain', 'to make plain or clear', 'cet4', 'verb'),
    ('紧张', 'tense', 'feeling nervous or stressed', 'cet4', 'emotion'),
    ('进行', 'proceed', 'to go forward', 'cet4', 'verb'),
    ('禁止', 'forbid', 'to make a rule against', 'cet4', 'verb'),
    ('经常', 'often', 'frequently', 'cet4', 'adverb'),
    ('经过', 'pass through', 'to go by or across', 'cet4', 'verb'),
    ('经济', 'economy', 'the system of production and consumption', 'cet4', 'business'),
    ('经验', 'experience', 'knowledge gained through practice', 'cet4', 'abstract'),
    ('景色', 'scenery', 'the natural features of a landscape', 'daily', 'nature'),
    ('警察', 'police', 'the official force maintaining order', 'cet4', 'society'),
    ('竞争', 'compete', 'to try to beat others', 'cet4', 'verb'),
    ('究竟', 'after all', 'used to emphasize a question', 'cet4', 'adverb'),
    ('居住', 'reside', 'to live in a place', 'cet4', 'verb'),
    ('决定', 'decide', 'to make a choice', 'cet4', 'verb'),
    ('可爱', 'cute', 'endearing and charming', 'daily', 'adj'),
    ('渴望', 'yearn', 'to have a strong desire for', 'cet4', 'verb'),
    ('空气', 'air', 'the invisible gas around us', 'daily', 'nature'),
    ('快速', 'rapid', 'happening at great speed', 'cet4', 'adj'),
    ('困难', 'difficulty', 'something hard to deal with', 'cet4', 'abstract'),
    ('扩大', 'expand', 'to become larger', 'cet4', 'verb'),
    ('垃圾', 'garbage', 'waste material', 'daily', 'daily'),
    ('浪费', 'waste', 'to use carelessly', 'cet4', 'verb'),
    ('劳动', 'labor', 'physical or mental work', 'cet4', 'verb'),
    ('老实', 'honest', 'truthful and sincere', 'daily', 'adj'),
    ('乐观', 'optimistic', 'tending to see the positive', 'cet4', 'adj'),
    ('厉害', 'impressive', 'formidable in ability', 'daily', 'adj'),
    ('利用', 'utilize', 'to make practical use of', 'cet4', 'verb'),
    ('连忙', 'hastily', 'in a quick and hurried way', 'cet4', 'adverb'),
    ('联系', 'contact', 'to get in touch with', 'cet4', 'verb'),
    ('粮食', 'grain', 'a harvested cereal food', 'cet4', 'daily'),
    ('了解', 'understand', 'to grasp the meaning of', 'cet4', 'verb'),
    ('临时', 'temporary', 'lasting for a limited time', 'cet4', 'adj'),
    ('灵活', 'flexible', 'capable of adapting', 'cet4', 'adj'),
    ('零件', 'part', 'a component of a machine', 'cet4', 'daily'),
    ('流行', 'popular', 'widely liked or admired', 'cet4', 'adj'),
    ('路线', 'route', 'a way for travel', 'cet4', 'daily'),
    ('落后', 'fall behind', 'to be less advanced', 'cet4', 'verb'),
    ('满意', 'satisfied', 'content with a situation', 'cet4', 'adj'),
    ('矛盾', 'contradiction', 'a conflict between statements', 'cet4', 'abstract'),
    ('冒险', 'take risks', 'to engage in risky activity', 'cet4', 'verb'),
    ('面积', 'area', 'a measure of a region', 'cet4', 'abstract'),
    ('明显', 'obvious', 'easily perceived', 'cet4', 'adj'),
    ('明确', 'clear', 'stated with clarity', 'cet4', 'adj'),
    ('目标', 'objective', 'something aimed at', 'cet4', 'abstract'),
    ('目前', 'currently', 'at the present moment', 'cet4', 'adverb'),
    ('耐心', 'patient', 'able to wait calmly', 'cet4', 'adj'),
    ('难过', 'sad', 'feeling sorrow', 'daily', 'emotion'),
    ('能够', 'be able to', 'to have the ability', 'daily', 'verb'),
    ('能量', 'energy', 'the capacity for doing work', 'cet4', 'abstract'),
    ('年代', 'era', 'a long period of history', 'cet4', 'abstract'),
    ('农村', 'countryside', 'a rural area outside cities', 'cet4', 'daily'),
    ('农民', 'farmer', 'a person who farms', 'cet4', 'daily'),
    ('偶然', 'accidental', 'happening by chance', 'cet4', 'adj'),
    ('排列', 'arrange', 'to put in a particular order', 'cet4', 'verb'),
    ('判断', 'judge', 'to form an opinion', 'cet4', 'verb'),
    ('培养', 'cultivate', 'to develop or improve', 'cet4', 'verb'),
    ('批准', 'approve', 'to officially consent to', 'cet4', 'verb'),
    ('品种', 'variety', 'a particular type', 'cet4', 'daily'),
    ('平安', 'safe', 'free from danger', 'daily', 'adj'),
    ('平常', 'ordinary', 'with no special features', 'daily', 'adj'),
    ('平等', 'equal', 'having the same rights', 'cet4', 'adj'),
    ('平均', 'average', 'the middle value', 'cet4', 'adj'),
    ('评价', 'evaluate', 'to assess the worth of', 'cet4', 'verb'),
    ('破坏', 'destroy', 'to ruin or damage', 'cet4', 'verb'),
    ('期待', 'anticipate', 'to look forward to', 'cet4', 'verb'),
    ('期间', 'period', 'a length of time', 'cet4', 'abstract'),
    ('奇迹', 'miracle', 'a remarkable event', 'cet4', 'abstract'),
    ('启发', 'inspire', 'to stimulate the mind', 'cet4', 'verb'),
    ('气候', 'climate', 'weather conditions over time', 'cet4', 'nature'),
    ('千万', 'must', 'used to give strong advice', 'cet4', 'adverb'),
    ('前途', 'future', 'expected future prospects', 'cet4', 'abstract'),
    ('浅', 'shallow', 'not deep in water', 'daily', 'adj'),
    ('强调', 'emphasize', 'to stress as important', 'cet4', 'verb'),
    ('强烈', 'strong', 'powerful in effect', 'cet4', 'adj'),
    ('悄悄', 'quietly', 'in a stealthy manner', 'cet4', 'adverb'),
    ('亲切', 'warm', 'kind and affectionate', 'cet4', 'adj'),
    ('清理', 'clean up', 'to remove unwanted items', 'cet4', 'verb'),
    ('清楚', 'clear', 'easy to perceive', 'cet4', 'adj'),
    ('情况', 'situation', 'the state of affairs', 'cet4', 'abstract'),
    ('庆祝', 'celebrate', 'to mark with festivities', 'cet4', 'verb'),
    ('区别', 'difference', 'a distinguishing feature', 'cet4', 'abstract'),
    ('全部', 'entire', 'the total amount', 'cet4', 'adj'),
    ('全面', 'comprehensive', 'covering all aspects', 'cet4', 'adj'),
    ('确定', 'determine', 'to settle conclusively', 'cet4', 'verb'),
    ('然后', 'then', 'after that', 'daily', 'adverb'),
    ('热烈', 'warm', 'enthusiastic and excited', 'cet4', 'adj'),
    ('热闹', 'lively', 'full of activity and excitement', 'daily', 'adj'),
    ('人类', 'humankind', 'all human beings', 'cet4', 'society'),
    ('人民币', 'RMB', 'the official currency of China', 'daily', 'business'),
    ('人生', 'life', 'the existence of a person', 'cet4', 'abstract'),
    ('任何', 'any', 'no matter which', 'cet4', 'adj'),
    ('任务', 'mission', 'an assigned piece of work', 'cet4', 'daily'),
    ('仍然', 'still', 'continuing to happen', 'cet4', 'adverb'),
    ('日报', 'daily newspaper', 'a newspaper published every day', 'cet4', 'daily'),
    ('日子', 'day', 'a particular day', 'daily', 'daily'),
    ('容量', 'capacity', 'the maximum amount held', 'cet4', 'abstract'),
    ('如此', 'so', 'to such a degree', 'cet4', 'adverb'),
    ('如果', 'if', 'on condition that', 'daily', 'logic'),
    ('如下', 'as follows', 'listed below', 'cet4', 'adverb'),
    ('商品', 'commodity', 'an item bought and sold', 'cet4', 'business'),
    ('上去', 'go up', 'to ascend', 'daily', 'verb'),
    ('设计', 'design', 'to create a plan for', 'cet4', 'verb'),
    ('社会', 'society', 'a community of people', 'cet4', 'society'),
    ('深入', 'deepen', 'to go deeply into', 'cet4', 'verb'),
    ('甚至', 'even', 'used to emphasize a point', 'cet4', 'adverb'),
    ('生产', 'produce', 'to make or manufacture', 'cet4', 'verb'),
    ('生活', 'live', 'to exist as a human being', 'cet4', 'verb'),
    ('生命', 'life', 'the state of being alive', 'cet4', 'abstract'),
    ('生态', 'ecology', 'the relation of organisms to environment', 'cet4', 'nature'),
    ('失败', 'fail', 'to not succeed', 'cet4', 'verb'),
    ('失望', 'disappointed', 'sad from unfulfilled hopes', 'cet4', 'emotion'),
    ('实践', 'practice', 'the application of theory', 'cet4', 'abstract'),
    ('实现', 'fulfill', 'to achieve a goal', 'cet4', 'verb'),
    ('实验', 'experiment', 'a scientific test', 'cet4', 'academic'),
    ('使用', 'utilize', 'to put into service', 'cet4', 'verb'),
    ('世界', 'world', 'the earth and all its inhabitants', 'cet4', 'daily'),
    ('事实', 'fact', 'a thing known to be true', 'cet4', 'abstract'),
    ('事物', 'thing', 'an entity or object', 'cet4', 'abstract'),
    ('收获', 'harvest', 'to gather in a crop', 'cet4', 'verb'),
    ('首都', 'capital city', 'the main city of a country', 'cet4', 'daily'),
    ('首先', 'first', 'before anything else', 'daily', 'adverb'),
    ('受到', 'receive', 'to be subjected to', 'cet4', 'verb'),
    ('数据', 'data', 'information for analysis', 'cet4', 'tech'),
    ('数量', 'quantity', 'an amount or number', 'cet4', 'abstract'),
    ('数字', 'number', 'a numeral or digit', 'cet4', 'daily'),
    ('率领', 'lead', 'to guide a group', 'cet6', 'verb'),
    ('说明', 'explain', 'to make clear in words', 'cet4', 'verb'),
    ('思考', 'ponder', 'to consider deeply', 'cet4', 'verb'),
    ('思想', 'ideology', 'a set of beliefs', 'cet4', 'abstract'),
    ('速度', 'speed', 'the rate of motion', 'cet4', 'daily'),
    ('宿舍', 'dormitory', 'a student lodging building', 'daily', 'daily'),
    ('虽然', 'although', 'in spite of the fact', 'daily', 'logic'),
    ('随着', 'along with', 'in accordance with', 'cet4', 'adverb'),
    ('损坏', 'damage', 'to harm the condition of', 'cet4', 'verb'),
    ('损失', 'lose', 'to suffer a loss', 'cet4', 'verb'),
    ('所有', 'all', 'the whole quantity of', 'daily', 'adj'),
    ('特别', 'especially', 'in particular', 'daily', 'adverb'),
    ('特点', 'characteristic', 'a distinguishing quality', 'cet4', 'abstract'),
    ('特殊', 'special', 'unlike what is usual', 'cet4', 'adj'),
    ('特征', 'feature', 'a distinctive attribute', 'cet4', 'abstract'),
    ('提高', 'improve', 'to make better', 'cet4', 'verb'),
    ('体育', 'physical education', 'sports and exercise instruction', 'cet4', 'daily'),
    ('天气', 'weather', 'the state of the atmosphere', 'daily', 'nature'),
    ('条理', 'orderliness', 'good organizational pattern', 'cet6', 'abstract'),
    ('听话', 'obedient', 'complying with instructions', 'daily', 'adj'),
    ('通常', 'usually', 'under normal conditions', 'cet4', 'adverb'),
    ('通过', 'through', 'by means of', 'cet4', 'adverb'),
    ('通信', 'communicate', 'to exchange information', 'cet4', 'verb'),
    ('通知', 'notify', 'to inform officially', 'cet4', 'verb'),
    ('同时', 'simultaneously', 'at the same time', 'cet4', 'adverb'),
    ('痛苦', 'pain', 'physical or mental suffering', 'cet4', 'emotion'),
    ('投入', 'devote', 'to commit time and effort', 'cet4', 'verb'),
    ('突然', 'sudden', 'happening quickly and unexpectedly', 'cet4', 'adj'),
    ('土地', 'land', 'the surface of the earth', 'cet4', 'nature'),
    ('团结', 'unite', 'to come together as a group', 'cet4', 'verb'),
    ('推动', 'push forward', 'to drive or impel', 'cet4', 'verb'),
    ('推广', 'popularize', 'to make widely known', 'cet4', 'verb'),
    ('推进', 'advance', 'to cause to progress', 'cet4', 'verb'),
    ('脱离', 'break away', 'to separate from', 'cet6', 'verb'),
    ('外交', 'diplomacy', 'the conduct of international relations', 'cet4', 'society'),
    ('完成', 'complete', 'to finish fully', 'cet4', 'verb'),
    ('完全', 'completely', 'to the fullest extent', 'cet4', 'adverb'),
    ('完善', 'perfect', 'to make fully ready', 'cet4', 'verb'),
    ('网络', 'internet', 'a global computer network', 'cet4', 'tech'),
    ('微笑', 'smile', 'a facial expression of pleasure', 'daily', 'emotion'),
    ('伟大', 'great', 'of remarkable significance', 'cet4', 'adj'),
    ('未来', 'future', 'the time that is to come', 'cet4', 'abstract'),
    ('文化', 'culture', 'the customs and achievements of a group', 'cet4', 'society'),
    ('文明', 'civilization', 'an advanced human society', 'cet4', 'society'),
    ('文学', 'literature', 'written works of artistic merit', 'cet4', 'academic'),
    ('文章', 'article', 'a piece of writing', 'cet4', 'academic'),
    ('污染', 'pollute', 'to contaminate the environment', 'cet4', 'verb'),
    ('无数', 'countless', 'too many to count', 'cet4', 'adj'),
    ('武器', 'weapon', 'an instrument used for fighting', 'cet4', 'daily'),
    ('物理', 'physics', 'the study of matter and energy', 'cet4', 'academic'),
    ('物资', 'materials', 'supplies needed for an activity', 'cet4', 'abstract'),
    ('西方', 'the West', 'Europe and North America collectively', 'cet4', 'society'),
    ('牺牲', 'sacrifice', 'to give up something for a greater cause', 'cet4', 'verb'),
    ('习惯', 'habit', 'a regular tendency', 'cet4', 'daily'),
    ('系统', 'system', 'a set of interacting parts', 'cet4', 'tech'),
    ('细节', 'detail', 'a small part of something', 'cet4', 'abstract'),
    ('现代化', 'modernization', 'the process of becoming modern', 'cet4', 'society'),
    ('现实', 'reality', 'the actual state of things', 'cet4', 'abstract'),
    ('现象', 'phenomenon', 'an observable event', 'cet4', 'abstract'),
    ('现在', 'now', 'at the present time', 'daily', 'adverb'),
    ('限制', 'restrict', 'to impose limits on', 'cet4', 'verb'),
    ('相当', 'quite', 'to a moderate extent', 'cet4', 'adverb'),
    ('相等', 'equal', 'the same in quantity', 'cet4', 'adj'),
    ('相对', 'relative', 'considered in comparison', 'cet4', 'adj'),
    ('相关', 'relevant', 'closely connected', 'cet4', 'adj'),
    ('相信', 'believe', 'to accept as true', 'cet4', 'verb'),
    ('详细', 'detailed', 'including many details', 'cet4', 'adj'),
    ('项目', 'project', 'a planned undertaking', 'cet4', 'daily'),
    ('象征', 'symbolize', 'to stand for as a symbol', 'cet4', 'verb'),
    ('消费', 'consume', 'to spend on goods', 'cet4', 'verb'),
    ('消化', 'digest', 'to break down food in the body', 'cet4', 'verb'),
    ('消灭', 'eliminate', 'to completely remove', 'cet4', 'verb'),
    ('消失', 'disappear', 'to cease to be visible', 'cet4', 'verb'),
    ('消息', 'news', 'information about events', 'cet4', 'daily'),
    ('销售', 'sell', 'to transfer goods for money', 'cet4', 'verb'),
    ('效果', 'effect', 'a result or outcome', 'cet4', 'abstract'),
    ('效率', 'efficiency', 'the ratio of output to input', 'cet4', 'abstract'),
    ('协调', 'coordinate', 'to harmonize different parts', 'cet6', 'verb'),
    ('心理', 'psychology', 'the study of the mind', 'cet4', 'academic'),
    ('心灵', 'soul', 'the inner nature of a person', 'cet4', 'abstract'),
    ('心情', 'mood', 'a person\'s emotional state', 'cet4', 'emotion'),
    ('新鲜', 'fresh', 'not stale or spoiled', 'daily', 'adj'),
    ('信心', 'confidence', 'a feeling of self-assurance', 'cet4', 'emotion'),
    ('行动', 'action', 'the process of doing something', 'cet4', 'verb'),
    ('幸福', 'happiness', 'a state of well-being', 'cet4', 'emotion'),
    ('性质', 'nature', 'the basic character of something', 'cet4', 'abstract'),
    ('修改', 'modify', 'to make partial changes', 'cet4', 'verb'),
    ('休息', 'rest', 'to cease work or effort', 'daily', 'verb'),
    ('需要', 'need', 'to require something', 'cet4', 'verb'),
    ('宣传', 'propagate', 'to promote widely', 'cet4', 'verb'),
    ('选择', 'choose', 'to pick from alternatives', 'cet4', 'verb'),
    ('学会', 'learn', 'to gain knowledge through study', 'daily', 'verb'),
    ('学生', 'student', 'a person attending school', 'daily', 'daily'),
    ('学术', 'academic', 'relating to scholarly study', 'cet4', 'academic'),
    ('学习', 'study', 'the process of gaining knowledge', 'daily', 'verb'),
    ('迅速', 'rapid', 'characterized by speed', 'cet4', 'adj'),
    ('压力', 'pressure', 'a force that compels', 'cet4', 'abstract'),
    ('牙齿', 'tooth', 'a hard structure in the mouth', 'daily', 'daily'),
    ('严格', 'strict', 'demanding exact standards', 'cet4', 'adj'),
    ('研究', 'research', 'systematic investigation', 'cet4', 'academic'),
    ('严重', 'serious', 'demanding careful consideration', 'cet4', 'adj'),
    ('言论', 'speech', 'the expression of opinions', 'cet4', 'society'),
    ('要求', 'demand', 'a strong request', 'cet4', 'abstract'),
    ('业务', 'business', 'commercial activity', 'cet4', 'business'),
    ('也许', 'perhaps', 'possibly but not certainly', 'daily', 'adverb'),
    ('夜晚', 'night', 'the dark part of a day', 'daily', 'daily'),
    ('一般', 'general', 'applying to most cases', 'cet4', 'adj'),
    ('一边', 'one side', 'one of two aspects', 'daily', 'adverb'),
    ('一定', 'certain', 'known for sure', 'cet4', 'adj'),
    ('一共', 'altogether', 'in total', 'daily', 'adverb'),
    ('一切', 'everything', 'all things', 'cet4', 'abstract'),
    ('一样', 'same', 'not different', 'daily', 'adj'),
    ('一直', 'always', 'continuously', 'daily', 'adverb'),
    ('医疗', 'medical', 'relating to the treatment of illness', 'cet4', 'daily'),
    ('依靠', 'rely on', 'to depend for support', 'cet4', 'verb'),
    ('移动', 'move', 'to change position', 'cet4', 'verb'),
    ('遗产', 'heritage', 'something inherited from the past', 'cet6', 'abstract'),
    ('疑问', 'question', 'an expression of uncertainty', 'cet4', 'abstract'),
    ('已经', 'already', 'before the present moment', 'daily', 'adverb'),
    ('艺术', 'art', 'the expression of creative skill', 'cet4', 'academic'),
    ('意见', 'opinion', 'a view or judgment', 'cet4', 'abstract'),
    ('因此', 'therefore', 'as a result', 'cet4', 'logic'),
    ('因而', 'thus', 'because of that', 'cet4', 'logic'),
    ('因为', 'because', 'for the reason that', 'daily', 'logic'),
    ('音乐', 'music', 'vocal or instrumental sounds', 'daily', 'daily'),
    ('引导', 'guide', 'to direct or steer', 'cet4', 'verb'),
    ('印象', 'impression', 'a feeling about something', 'cet4', 'abstract'),
    ('应该', 'ought to', 'used to indicate obligation', 'daily', 'adverb'),
    ('应用', 'apply', 'to put into practical use', 'cet4', 'verb'),
    ('营养', 'nutrition', 'the process of absorbing food', 'cet4', 'daily'),
    ('营业', 'operate', 'to be open for business', 'cet4', 'verb'),
    ('影响', 'influence', 'the power to affect', 'cet4', 'verb'),
    ('用户', 'user', 'a person who uses a service', 'cet4', 'tech'),
    ('尤其', 'especially', 'more than usually', 'cet4', 'adverb'),
    ('由于', 'due to', 'because of', 'cet4', 'logic'),
    ('有效', 'effective', 'producing desired results', 'cet4', 'adj'),
    ('于是', 'thereupon', 'as a result of this', 'cet4', 'logic'),
    ('愉快', 'pleasant', 'giving a feeling of enjoyment', 'cet4', 'adj'),
    ('语气', 'tone', 'the way something is said', 'cet4', 'abstract'),
    ('语言', 'language', 'a system of communication', 'cet4', 'daily'),
    ('预测', 'predict', 'to foretell the future', 'cet4', 'verb'),
    ('预防', 'prevent', 'to stop from happening', 'cet4', 'verb'),
    ('元素', 'element', 'a fundamental component', 'cet4', 'abstract'),
    ('原料', 'raw material', 'basic unprocessed material', 'cet4', 'abstract'),
    ('原则', 'principle', 'a fundamental rule', 'cet4', 'abstract'),
    ('愿望', 'desire', 'a strong wish or hope', 'cet4', 'emotion'),
    ('月亮', 'moon', 'the natural satellite of Earth', 'daily', 'nature'),
    ('运动', 'exercise', 'physical activity for fitness', 'cet4', 'daily'),
    ('运用', 'use', 'to put into practice', 'cet4', 'verb'),
    ('灾害', 'disaster', 'a sudden catastrophic event', 'cet4', 'abstract'),
    ('暂时', 'temporary', 'for a limited time', 'cet4', 'adj'),
    ('责任', 'responsibility', 'the state of being accountable', 'cet4', 'abstract'),
    ('增加', 'increase', 'to become larger', 'cet4', 'verb'),
    ('增长', 'grow', 'to increase in size', 'cet4', 'verb'),
    ('展开', 'unfold', 'to spread out', 'cet4', 'verb'),
    ('展览', 'exhibition', 'a public display of items', 'cet4', 'daily'),
    ('战略', 'strategy', 'a plan designed to achieve a goal', 'cet4', 'abstract'),
    ('战士', 'soldier', 'a person who serves in an army', 'cet4', 'daily'),
    ('掌握', 'master', 'to have thorough knowledge', 'cet4', 'verb'),
    ('照顾', 'look after', 'to take care of', 'cet4', 'verb'),
    ('照片', 'photograph', 'an image captured by camera', 'daily', 'daily'),
    ('哲学', 'philosophy', 'the study of existence and reality', 'cet4', 'academic'),
    ('珍贵', 'precious', 'of great value', 'cet4', 'adj'),
    ('针对', 'target', 'to direct toward a target', 'cet4', 'verb'),
    ('震动', 'vibrate', 'to shake or tremble', 'cet4', 'verb'),
    ('争论', 'argue', 'to exchange opposing views', 'cet4', 'verb'),
    ('征服', 'conquer', 'to overcome by force', 'cet6', 'verb'),
    ('整个', 'whole', 'entirely', 'cet4', 'adj'),
    ('整理', 'organize', 'to arrange in order', 'cet4', 'verb'),
    ('正常', 'normal', 'conforming to a standard', 'cet4', 'adj'),
    ('正确', 'correct', 'free from error', 'cet4', 'adj'),
    ('正式', 'formal', 'done in accordance with rules', 'cet4', 'adj'),
    ('证明', 'prove', 'to demonstrate the truth', 'cet4', 'verb'),
    ('政府', 'government', 'the governing body', 'cet4', 'society'),
    ('政治', 'politics', 'the activities of governing', 'cet4', 'society'),
    ('支持', 'support', 'to give assistance', 'cet4', 'verb'),
    ('知道', 'know', 'to be aware of', 'daily', 'verb'),
    ('知识', 'knowledge', 'information and understanding', 'cet4', 'abstract'),
    ('执行', 'execute', 'to carry out a task', 'cet4', 'verb'),
    ('直接', 'direct', 'without intermediate steps', 'cet4', 'adj'),
    ('值得', 'worthy', 'deserving of something', 'cet4', 'adj'),
    ('植物', 'plant', 'a living organism of the plant kingdom', 'cet4', 'nature'),
    ('指示', 'instruct', 'to give directions', 'cet4', 'verb'),
    ('质量', 'quality', 'the standard of something', 'cet4', 'abstract'),
    ('治疗', 'treat', 'to provide medical care', 'cet4', 'verb'),
    ('志愿', 'volunteer', 'a person who freely offers service', 'cet4', 'society'),
    ('制度', 'system', 'an organized scheme', 'cet4', 'abstract'),
    ('制造', 'manufacture', 'to make from raw materials', 'cet4', 'verb'),
    ('秩序', 'order', 'a state of tidiness', 'cet4', 'abstract'),
    ('智慧', 'wisdom', 'the quality of being wise', 'cet4', 'abstract'),
    ('中部', 'central part', 'the middle region', 'cet4', 'daily'),
    ('中央', 'center', 'the middle point', 'cet4', 'daily'),
    ('终于', 'finally', 'after a long time', 'cet4', 'adverb'),
    ('种类', 'kind', 'a class of similar things', 'cet4', 'abstract'),
    ('重大', 'significant', 'great in importance', 'cet4', 'adj'),
    ('重点', 'key point', 'the most important part', 'cet4', 'abstract'),
    ('重量', 'weight', 'how heavy something is', 'cet4', 'daily'),
    ('周围', 'surrounding', 'the area around something', 'cet4', 'daily'),
    ('逐渐', 'gradually', 'by degrees', 'cet4', 'adverb'),
    ('主动', 'initiative', 'the ability to act independently', 'cet4', 'adverb'),
    ('主观', 'subjective', 'based on personal feelings', 'cet4', 'adj'),
    ('主要', 'main', 'most important', 'cet4', 'adj'),
    ('主意', 'idea', 'a thought or suggestion', 'daily', 'abstract'),
    ('主张', 'advocate', 'to recommend a course', 'cet6', 'verb'),
    ('著名', 'famous', 'widely known', 'cet4', 'adj'),
    ('祝贺', 'congratulate', 'to express joy to someone', 'cet4', 'verb'),
    ('抓紧', 'grasp firmly', 'to hold tightly', 'cet4', 'verb'),
    ('专家', 'expert', 'a person with special knowledge', 'cet4', 'academic'),
    ('专门', 'specialized', 'focused on a particular area', 'cet4', 'adj'),
    ('专业', 'specialty', 'a field of study', 'cet4', 'academic'),
    ('转变', 'transform', 'to change in form', 'cet4', 'verb'),
    ('转化', 'convert', 'to change into another form', 'cet4', 'verb'),
    ('装备', 'equip', 'to provide with necessary items', 'cet4', 'verb'),
    ('状况', 'condition', 'the state of something', 'cet4', 'abstract'),
    ('状态', 'state', 'the condition at a given time', 'cet4', 'abstract'),
    ('追求', 'pursue', 'to follow in order to catch', 'cet4', 'verb'),
    ('准备', 'prepare', 'to make ready', 'cet4', 'verb'),
    ('准确', 'accurate', 'free from errors', 'cet4', 'adj'),
    ('资源', 'resource', 'a stock or supply', 'cet4', 'abstract'),
    ('仔细', 'careful', 'paying close attention', 'daily', 'adj'),
    ('自觉', 'conscious', 'aware of something', 'cet4', 'adj'),
    ('自然', 'nature', 'the natural world', 'cet4', 'nature'),
    ('自我', 'self', 'one\'s own being', 'cet4', 'abstract'),
    ('自信', 'self-confident', 'confident in one\'s own abilities', 'cet4', 'adj'),
    ('自由', 'freedom', 'the power to act freely', 'cet4', 'abstract'),
    ('自愿', 'voluntary', 'by one\'s own choice', 'cet4', 'adj'),
    ('综合', 'comprehensive', 'covering all elements', 'cet4', 'adj'),
    ('总结', 'summarize', 'to give a brief account', 'cet4', 'verb'),
    ('总理', 'premier', 'the head of government', 'cet4', 'society'),
    ('总之', 'in short', 'to summarize', 'cet4', 'adverb'),
    ('阻止', 'prevent', 'to keep from happening', 'cet4', 'verb'),
    ('组长', 'group leader', 'the head of a team', 'daily', 'daily'),
    ('组织', 'organize', 'to arrange systematically', 'cet4', 'verb'),
    ('最初', 'initial', 'existing at the beginning', 'cet4', 'adj'),
    ('最近', 'recently', 'a short time ago', 'daily', 'adverb'),
    ('最后', 'finally', 'at the end', 'daily', 'adverb'),
    ('最终', 'ultimate', 'at the very end', 'cet4', 'adj'),
    ('尊敬', 'respect', 'to hold in high regard', 'cet4', 'verb'),
    ('遵守', 'obey', 'to follow a rule', 'cet4', 'verb'),
    ('作品', 'work', 'a creative product', 'cet4', 'abstract'),
    ('作为', 'as', 'in the capacity of', 'cet4', 'adverb'),
    ('作用', 'function', 'the purpose of something', 'cet4', 'abstract'),
    ('作者', 'author', 'the writer of a work', 'cet4', 'academic'),
    ('座谈', 'forum', 'a group discussion', 'cet4', 'daily'),
    ('座位', 'seat', 'a place for sitting', 'daily', 'daily'),
]

# ── Example sentences for batch 2 entries (~60% coverage) ──
EXAMPLES_BATCH2 = {
    '着': ("She is reading a book in the library right now.", "她正在图书馆里**着**书。"),
    '了': ("I have finished all my homework for today.", "我做完今天的作业**了**。"),
    '过': ("Have you ever been to Beijing before?", "你去**过**北京吗？"),
    '比': ("This bag is bigger than that one.", "这个包**比**那个大。"),
    '从': ("She has been working here since last year.", "她**从**去年开始就在这里工作了。"),
    '在': ("He is waiting for you at the entrance.", "他**在**入口处等你。"),
    '和': ("I bought apples and oranges at the market.", "我在市场买了苹果**和**橙子。"),
    '就': ("I will come right away after finishing my work.", "我做完工作**就**来。"),
    '才': ("He only arrived after the meeting had started.", "他直到会议开始**才**到。"),
    '再': ("Please say that again, I didn't hear you.", "请**再**说一遍，我没听清。"),
    '又': ("She tried again and succeeded this time.", "她**又**试了一次，这次成功了。"),
    '还': ("I still haven't received your email.", "我**还**没有收到你的邮件。"),
    '也': ("I like this one, and I also like that one.", "我喜欢这个，**也**喜欢那个。"),
    '都': ("They all agreed to the proposal.", "他们**都**同意了这项提议。"),
    '只': ("I only have five dollars left.", "我**只**剩下五美元了。"),
    '很': ("This book is very interesting.", "这本书**很**有趣。"),
    '太': ("This coffee is too hot to drink right now.", "这杯咖啡**太**烫了，现在不能喝。"),
    '更': ("She is even taller than her brother.", "她**更**比她哥哥高。"),
    '最': ("This is the most beautiful view I have ever seen.", "这是我看过**最**美的景色。"),
    '真': ("That was really a wonderful performance!", "那**真**是一场精彩的演出！"),
    '刚': ("He just left a few minutes ago.", "他**刚**走了几分钟。"),
    '每': ("She goes to the gym every morning.", "她**每**天早上去健身房。"),
    '别': ("Don't forget to lock the door.", "**别**忘了锁门。"),
    '会': ("I will call you when I arrive.", "我到了**会**给你打电话。"),
    '能': ("Can you help me carry this box?", "你**能**帮我搬这个箱子吗？"),
    '必须': ("You must finish the report by Friday.", "你**必须**在周五前完成报告。"),
    '应该': ("You should apologize for what you said.", "你**应该**为你说的话道歉。"),
    '可以': ("May I come in?", "我**可以**进来吗？"),
    '可能': ("It might rain later, so bring an umbrella.", "**可能**会下雨，带把伞吧。"),
    '一定': ("I will definitely come to your party.", "我**一定**会来参加你的派对。"),
    '爱好': ("Reading is my favorite hobby.", "阅读是我最喜欢的**爱好**。"),
    '比赛': ("The soccer match was very exciting.", "足球**比赛**非常精彩。"),
    '表演': ("The dance performance was stunning.", "舞蹈**表演**令人惊叹。"),
    '表扬': ("The teacher praised her for good work.", "老师**表扬**她功课做得好。"),
    '成绩': ("She got excellent results in her exams.", "她考试取得了优异的**成绩**。"),
    '出发': ("We will set out early tomorrow morning.", "我们明天一早**出发**。"),
    '聪明': ("The clever girl solved the puzzle quickly.", "那个**聪明**的女孩很快解出了谜题。"),
    '打算': ("What do you plan to do this weekend?", "这个周末你**打算**做什么？"),
    '当然': ("Of course you can borrow my book.", "你**当然**可以借我的书。"),
    '东西': ("I bought a few things at the store.", "我在商店买了些**东西**。"),
    '多么': ("How beautiful this garden is!", "这个花园**多么**美丽啊！"),
    '方便': ("This location is very convenient for shopping.", "这个位置购物很**方便**。"),
    '非常': ("She is extremely talented in music.", "她在音乐方面**非常**有天赋。"),
    '根据': ("According to the report, sales are improving.", "**根据**报告，销售额正在增长。"),
    '故事': ("Grandpa told us an interesting story last night.", "爷爷昨晚给我们讲了一个有趣的**故事**。"),
    '关心': ("She really cares about her students.", "她真的很**关心**她的学生。"),
    '关于': ("Regarding your question, here is the answer.", "**关于**你的问题，这是答案。"),
    '果然': ("It turned out exactly as I expected.", "**果然**不出我所料。"),
    '忽然': ("Suddenly, the lights went out.", "灯**忽然**灭了。"),
    '积极': ("She plays an active role in the community.", "她在社区中扮演**积极**的角色。"),
    '激动': ("The fans were thrilled by the victory.", "粉丝们为胜利感到**激动**。"),
    '即使': ("Even if it rains, we will still go hiking.", "**即使**下雨，我们也会去远足。"),
    '家乡': ("My hometown is a small town in the mountains.", "我的**家乡**是山里的一个小镇。"),
    '坚持': ("She persisted in her dream of becoming a doctor.", "她**坚持**成为医生的梦想。"),
    '建立': ("They established a new company last year.", "他们去年**建立**了一家新公司。"),
    '建议': ("I suggest we take a different approach.", "我**建议**我们换一种方法。"),
    '交通': ("The traffic is always heavy during rush hour.", "高峰时段**交通**总是很拥堵。"),
    '紧张': ("She felt nervous before the job interview.", "面试前她感到很**紧张**。"),
    '进行': ("The meeting will proceed as scheduled.", "会议将按计划**进行**。"),
    '经过': ("After discussing for hours, they reached an agreement.", "**经过**几个小时的讨论，他们达成了协议。"),
    '景色': ("The scenery here is absolutely breathtaking.", "这里的**景色**美得令人屏息。"),
    '竞争': ("Many companies compete for market share.", "许多公司**竞争**市场份额。"),
    '决定': ("She decided to study abroad next year.", "她**决定**明年出国留学。"),
    '可爱': ("The baby panda is so cute.", "熊猫宝宝真**可爱**。"),
    '困难': ("Learning a new language can be difficult.", "学习一门新语言可能很**困难**。"),
    '垃圾': ("Please throw the garbage in the bin.", "请把**垃圾**扔进垃圾桶。"),
    '利用': ("We should utilize this opportunity wisely.", "我们应该好好**利用**这个机会。"),
    '联系': ("Please contact me if you have any questions.", "如果有问题请**联系**我。"),
    '了解': ("I understand how you feel.", "我**了解**你的感受。"),
    '流行': ("This song is very popular among young people.", "这首歌在年轻人中很**流行**。"),
    '满意': ("The customers were very satisfied with the service.", "客户对服务非常**满意**。"),
    '难过': ("She felt sad after hearing the bad news.", "听到坏消息后她感到很**难过**。"),
    '努力': ("Work hard and you will achieve your goals.", "**努力**工作，你一定能实现目标。"),
    '培养': ("Schools should cultivate students' creativity.", "学校应该**培养**学生的创造力。"),
    '评价': ("Critics praised the film highly.", "评论家对这部电影**评价**很高。"),
    '期待': ("I am looking forward to meeting you.", "我**期待**与您见面。"),
    '奇迹': ("It was a miracle that no one was hurt.", "没有人受伤真是**奇迹**。"),
    '气候': ("The climate here is mild and pleasant.", "这里的**气候**温和宜人。"),
    '强调': ("The teacher emphasized the importance of honesty.", "老师**强调**了诚实的重要性。"),
    '清楚': ("I understand the instructions clearly.", "我**清楚**地理解这些说明。"),
    '庆祝': ("We celebrated her birthday with a party.", "我们开派对**庆祝**了她的生日。"),
    '然后': ("First finish your homework, then you can play.", "先完成作业，**然后**再玩。"),
    '热烈': ("The audience gave a warm welcome to the speaker.", "观众向演讲者致以**热烈**的欢迎。"),
    '生命': ("Every life is precious and deserves respect.", "每个**生命**都宝贵，都值得尊重。"),
    '失望': ("She was disappointed with the exam results.", "她对考试成绩感到**失望**。"),
    '实现': ("She finally realized her dream of traveling the world.", "她终于**实现**了环游世界的梦想。"),
    '收获': ("We harvested a lot of vegetables from our garden.", "我们从菜园里**收获**了很多蔬菜。"),
    '说明': ("Can you explain how this machine works?", "你能**说明**一下这台机器怎么用吗？"),
    '速度': ("The car was traveling at high speed.", "汽车正以高速**速度**行驶。"),
    '提高': ("Reading regularly can improve your vocabulary.", "定期阅读可以**提高**你的词汇量。"),
    '通知': ("Please notify all employees about the meeting.", "请**通知**所有员工开会。"),
    '同时': ("She studied and worked part-time at the same time.", "她**同时**学习和做兼职。"),
    '突然': ("Suddenly, it started to rain heavily.", "**突然**下起了大雨。"),
    '完成': ("He completed the project ahead of schedule.", "他提前**完成**了项目。"),
    '完全': ("I completely agree with your opinion.", "我**完全**同意你的观点。"),
    '微笑': ("She smiled warmly at the new neighbors.", "她对新邻居**微笑**致意。"),
    '污染': ("Factories should not pollute the environment.", "工厂不应该**污染**环境。"),
    '相信': ("I believe you will succeed in your new venture.", "我**相信**你会在新事业中取得成功。"),
    '详细': ("Please provide a detailed explanation.", "请提供**详细**的解释。"),
    '消费': ("Consumers should spend their money wisely.", "消费者应该明智地**消费**。"),
    '消息': ("Have you heard the latest news?", "你听说最近的**消息**了吗？"),
    '心情': ("She was in a good mood after the walk.", "散步后她**心情**很好。"),
    '信心': ("She has confidence in her ability to succeed.", "她对自己成功的**信心**很足。"),
    '休息': ("You should rest after working so hard.", "努力工作后你应该**休息**一下。"),
    '选择': ("You can choose any book you like.", "你可以**选择**任何你喜欢的书。"),
    '学习': ("We should study from our mistakes.", "我们应该从错误中**学习**。"),
    '压力': ("Learning to manage stress is very important.", "学会管理**压力**非常重要。"),
    '研究': ("Scientists are researching a cure for the disease.", "科学家正在**研究**治疗这种疾病的方法。"),
    '要求': ("The job requires strong communication skills.", "这份工作**要求**较强的沟通能力。"),
    '意见': ("Please share your opinion on this matter.", "请分享你对这件事的**意见**。"),
    '音乐': ("Music has the power to soothe the soul.", "**音乐**有抚慰心灵的力量。"),
    '影响': ("The weather can greatly affect your mood.", "天气会极大地**影响**你的情绪。"),
    '有效': ("This medicine is effective against the flu.", "这种药对治疗流感很**有效**。"),
    '愉快': ("We had a wonderful time at the party.", "我们在派对上度过了**愉快**的时光。"),
    '预测': ("It is hard to predict what will happen next year.", "很难**预测**明年会发生什么。"),
    '运动': ("Regular exercise keeps you healthy.", "定期**运动**能保持健康。"),
    '增加': ("The population has increased significantly.", "人口**增加**了很多。"),
    '掌握': ("She has mastered three foreign languages.", "她**掌握**了三门外语。"),
    '照顾': ("She takes care of her elderly parents.", "她**照顾**年迈的父母。"),
    '正常': ("Everything is back to normal now.", "现在一切恢复正常。"),
    '正确': ("Your answer is correct.", "你的答案是**正确**的。"),
    '证明': ("The evidence proved his innocence.", "证据**证明**了他的清白。"),
    '支持': ("My family always supports my decisions.", "我的家人一直**支持**我的决定。"),
    '直接': ("Please give me a direct answer.", "请给我一个**直接**的回答。"),
    '值得': ("This movie is well worth watching.", "这部电影很**值得**一看。"),
    '质量': ("The quality of this product is excellent.", "这个产品的**质量**非常好。"),
    '终于': ("She finally passed the exam after many attempts.", "经过多次努力，她**终于**通过了考试。"),
    '逐渐': ("The weather gradually became warmer.", "天气**逐渐**变暖了。"),
    '主要': ("The main issue is lack of funding.", "**主要**问题是缺乏资金。"),
    '著名': ("Zhang Yimou is a world-famous director.", "张艺谋是**著名**的导演。"),
    '祝贺': ("Congratulations on your promotion!", "**祝贺**你升职！"),
    '准备': ("She prepared thoroughly for the interview.", "她为面试做了充分的**准备**。"),
    '仔细': ("Read the instructions carefully before use.", "使用前请**仔细**阅读说明。"),
    '自然': ("Nature is beautiful in every season.", "**自然**在每个季节都很美。"),
    '自由': ("Freedom of speech is a fundamental right.", "言论**自由**是一项基本权利。"),
    '总结': ("To summarize, we had a very productive meeting.", "**总结**一下，我们开了一个非常有成效的会。"),
    '最后': ("Finally, I want to thank everyone for their support.", "**最后**，我想感谢大家的支持。"),
    '最近': ("Have you seen any good movies recently?", "你**最近**看过什么好电影吗？"),
    '尊敬': ("We should respect our elders.", "我们应该**尊敬**长辈。"),
    '作用': ("This medicine has a strong effect on pain relief.", "这种药对止痛有很好的**作用**。"),
    '位置': ("Can you tell me the location of the hotel?", "你能告诉我酒店的**位置**吗？"),
    '现代': ("Modern technology has changed our lives.", "**现代**科技改变了我们的生活。"),
    '传统': ("It's important to preserve cultural traditions.", "保护文化**传统**很重要。"),
    '代表': ("She will represent our company at the conference.", "她将**代表**公司出席会议。"),
    '产生': ("The new policy will generate more job opportunities.", "新政策将**产生**更多的就业机会。"),
    '成功': ("Hard work is the key to achieving success.", "努力工作是**成功**的关键。"),
    '承认': ("He admitted that he had made a mistake.", "他**承认**自己犯了一个错误。"),
    '持续': ("The rain continued for three days straight.", "雨**持续**下了整整三天。"),
    '创造': ("Artists create beautiful works that inspire us.", "艺术家**创造**出鼓舞人心的美丽作品。"),
    '答应': ("She promised to help me with the project.", "她**答应**帮我做这个项目。"),
    '达到': ("We need to reach our sales target this quarter.", "我们需要在本季度**达到**销售目标。"),
    '当时': ("At that time, I didn't realize how important it was.", "**当时**，我没有意识到这有多重要。"),
    '到底': ("What on earth happened here?", "这里**到底**发生了什么？"),
    '道理': ("There is truth in what she said.", "她说的话有**道理**。"),
    '地震': ("The earthquake measured six point five on the Richter scale.", "**地震**震级为里氏6.5级。"),
    '调查': ("The police are investigating the incident.", "警方正在**调查**这起事件。"),
    '反对': ("Many people oppose the construction of the new dam.", "很多人**反对**修建新大坝。"),
    '反应': ("His reaction to the news was one of shock.", "他对这个消息的**反应**是震惊。"),
    '访问': ("The president will visit several European countries.", "总统将**访问**几个欧洲国家。"),
    '丰富': ("The country has abundant natural resources.", "这个国家有**丰富**的自然资源。"),
    '负责': ("Who is responsible for this project?", "谁**负责**这个项目？"),
    '改变': ("Learning a new language can change your perspective.", "学习一门新语言可以**改变**你的视角。"),
    '感动': ("We were deeply moved by her story.", "我们被她的故事深深**感动**了。"),
    '感情': ("They have deep feelings for each other.", "他们之间有深厚的**感情**。"),
    '告诉': ("Please tell me the truth.", "请**告诉**我真相。"),
    '个别': ("A few individual cases don't represent the whole.", "**个别**情况不代表整体。"),
    '工业': ("The industrial revolution changed the world.", "**工业**革命改变了世界。"),
    '贡献': ("She has made significant contributions to science.", "她为科学做出了重大**贡献**。"),
    '观察': ("Scientists observe animal behavior in the wild.", "科学家在野外**观察**动物行为。"),
    '观点': ("From my perspective, this is the best option.", "从我的**观点**来看，这是最好的选择。"),
    '管理': ("Good management is essential for success.", "良好的**管理**对成功至关重要。"),
    '规定': ("The rules state that you must wear safety gear.", "**规定**要求你必须穿戴安全装备。"),
    '过程': ("The learning process takes time and patience.", "学习的**过程**需要时间和耐心。"),
    '海洋': ("The ocean covers most of the Earth's surface.", "**海洋**覆盖了地球大部分表面。"),
    '合格': ("All products must meet quality standards.", "所有产品必须**合格**。"),
    '红色': ("She wore a beautiful red dress to the party.", "她穿了一条漂亮的**红色**裙子去派对。"),
    '幻想': ("Don't live in a fantasy world, face reality.", "不要活在**幻想**中，要面对现实。"),
    '回忆': ("She recalls fond memories of her childhood.", "她回忆起美好的童年**回忆**。"),
    '机器': ("The machine can process hundreds of items per hour.", "这台**机器**每小时可以处理数百件物品。"),
    '基础': ("A good education provides a solid foundation.", "良好的教育奠定了坚实的**基础**。"),
    '记录': ("Please record the minutes of the meeting.", "请**记录**会议纪要。"),
    '纪律': ("Discipline is essential for any successful team.", "**纪律**对任何成功的团队都至关重要。"),
    '技术': ("Technology is advancing at a rapid pace.", "**技术**正在飞速发展。"),
    '加强': ("We need to strengthen our cybersecurity measures.", "我们需要**加强**网络安全措施。"),
    '检查': ("Please check your email for the confirmation.", "请**检查**邮箱查看确认信息。"),
    '建议': ("I suggest we meet again next week.", "我**建议**我们下周再见面。"),
    '健康': ("Health is more important than wealth.", "**健康**比财富更重要。"),
    '交流': ("Cultural exchange helps promote understanding.", "文化**交流**有助于增进理解。"),
    '教育': ("Education changes lives for the better.", "**教育**让生活变得更美好。"),
    '接受': ("She accepted the job offer without hesitation.", "她毫不犹豫地**接受**了那份工作。"),
    '节约': ("We should save water and electricity.", "我们应该**节约**用水用电。"),
    '解决': ("We need to solve this problem quickly.", "我们需要尽快**解决**这个问题。"),
    '解释': ("Can you explain what this word means?", "你能**解释**一下这个词的意思吗？"),
    '禁止': ("Smoking is forbidden in this area.", "这个区域**禁止**吸烟。"),
    '经常': ("I often go for a walk after dinner.", "我**经常**晚饭后去散步。"),
    '经济': ("The economy is growing steadily.", "**经济**在稳步增长。"),
    '警察': ("The police are here to help and protect us.", "**警察**在这里帮助和保护我们。"),
    '居住': ("She resides in a small village in the mountains.", "她**居住**在山里的小村庄。"),
    '可是': ("I wanted to go, but I was too busy.", "我想去，**可是**太忙了。"),
    '空气': ("The air quality in the countryside is much better.", "乡村的**空气**质量好得多。"),
    '扩大': ("The company plans to expand into new markets.", "公司计划**扩大**到新市场。"),
    '劳动': ("Hard work is the foundation of success.", "**劳动**是成功的基础。"),
    '利用': ("We should make good use of our time.", "我们应该好好**利用**时间。"),
    '连忙': ("She quickly apologized for her mistake.", "她**连忙**为自己的错误道歉。"),
    '灵活': ("We need to be flexible in our approach.", "我们的方法需要**灵活**一些。"),
    '流行': ("This style is very popular this year.", "这种风格今年很**流行**。"),
    '满意': ("We are satisfied with the results.", "我们对结果很**满意**。"),
    '冒险': ("It's risky to invest all your money in one stock.", "把所有钱投在一只股票上很**冒险**。"),
    '明确': ("The instructions are clear and easy to follow.", "说明很**明确**，容易遵循。"),
    '目标': ("Set clear goals and work toward them daily.", "设定明确的**目标**并每天为之努力。"),
    '目前': ("Currently, we are working on a new project.", "**目前**，我们正在做一个新项目。"),
    '耐心': ("You need patience when learning a new skill.", "学习新技能时需要有**耐心**。"),
    '能够': ("She is able to speak three languages fluently.", "她**能够**流利地说三种语言。"),
    '年代': ("The 1990s were a decade of rapid technological change.", "九十**年代**是技术快速变革的十年。"),
    '判断': ("It's hard to judge the situation without more information.", "没有更多信息很难**判断**情况。"),
    '批评': ("He accepted the criticism and promised to improve.", "他接受了**批评**并承诺改进。"),
    '平常': ("It's quite ordinary for children to feel shy at first.", "孩子一开始感到害羞是很**平常**的。"),
    '破坏': ("The storm destroyed many homes along the coast.", "风暴**破坏**了沿海的许多房屋。"),
    '奇迹': ("It's a miracle that she survived the accident.", "她在事故中幸存真是**奇迹**。"),
    '强烈': ("She has a strong desire to help others.", "她有**强烈**的愿望去帮助别人。"),
    '悄悄': ("She quietly left the room so as not to wake the baby.", "她**悄悄**离开房间以免吵醒宝宝。"),
    '全部': ("We need to finish the entire project by Friday.", "我们需要在周五前完成**全部**项目。"),
    '然而': ("The weather was bad; however, we still enjoyed the trip.", "天气不好，**然而**我们仍然享受了这次旅行。"),
    '热闹': ("The streets are lively during the festival.", "节日期间街道很**热闹**。"),
    '任何': ("Any student can join the club if they are interested.", "**任何**感兴趣的学生都可以加入俱乐部。"),
    '仍然': ("She still remembers her first day at school.", "她**仍然**记得上学第一天。"),
    '如果': ("If you study hard, you will pass the exam.", "**如果**你努力学习，就会通过考试。"),
    '深刻': ("The experience left a deep impression on me.", "这次经历给我留下了**深刻**的印象。"),
    '甚至': ("Even the experts were surprised by the result.", "**甚至**专家都对结果感到惊讶。"),
    '生活': ("She enjoys living in the countryside.", "她喜欢**生活**在乡村。"),
    '失败': ("Failure is the mother of success.", "**失败**是成功之母。"),
    '实践': ("Practice is the only way to truly learn.", "**实践**是真正学习的唯一途径。"),
    '食物': ("Fresh food tastes better than processed food.", "新鲜的**食物**比加工食品更好吃。"),
    '首先': ("First, let me introduce our guest speaker.", "**首先**，让我介绍我们的主讲嘉宾。"),
    '思考': ("Take time to think before making a major decision.", "做重大决定前要花时间**思考**。"),
    '虽然': ("Although it rained, we still had a wonderful time.", "**虽然**下雨了，我们仍然玩得很开心。"),
    '所有': ("All students must complete the assignment on time.", "**所有**学生必须按时完成作业。"),
    '特点': ("The main feature of this phone is its long battery life.", "这款手机的主要**特点**是电池续航长。"),
    '特别': ("I especially like the design of this room.", "我**特别**喜欢这个房间的设计。"),
    '提高': ("Practice is the best way to improve your English.", "练习是**提高**英语最好的方法。"),
    '通过': ("We succeeded through hard work and determination.", "我们**通过**努力和决心取得了成功。"),
    '痛苦': ("The pain of losing a loved one is hard to bear.", "失去亲人的**痛苦**难以承受。"),
    '推动': ("Education helps drive social progress.", "教育**推动**社会进步。"),
    '完善': ("We need to perfect the system before launching it.", "在推出之前，我们需要**完善**这个系统。"),
    '网络': ("The internet has changed the way we communicate.", "**网络**改变了我们的交流方式。"),
    '未来': ("The future belongs to those who prepare for it.", "**未来**属于那些为之准备的人。"),
    '温暖': ("Her warm smile made everyone feel welcome.", "她**温暖**的微笑让每个人感到受欢迎。"),
    '文章': ("I read an interesting article about space exploration.", "我读了一篇关于太空探索的有趣**文章**。"),
    '无数': ("There are countless stars in the night sky.", "夜空中有**无数**的星星。"),
    '牺牲': ("She sacrificed her career to raise her children.", "她**牺牲**了自己的事业来抚养孩子。"),
    '系统': ("The new operating system has many useful features.", "新的操作**系统**有很多有用的功能。"),
    '现在': ("What are you doing now?", "你**现在**在做什么？"),
    '相当': ("The movie was quite good, better than I expected.", "这部电影**相当**不错，比我想的要好。"),
    '详细': ("Please describe in detail what you saw.", "请**详细**描述你看到的情况。"),
    '消费': ("Consumers should compare prices before buying.", "**消费**者应该在购买前比较价格。"),
    '效果': ("The treatment had a positive effect on her health.", "治疗对她的健康产生了良好**效果**。"),
    '新鲜': ("Fresh vegetables are always healthier.", "**新鲜**的蔬菜总是更健康。"),
    '信心': ("She has great confidence in her team.", "她对自己的团队充满**信心**。"),
    '幸福': ("Happiness comes from appreciating what you have.", "**幸福**来自于珍惜你所拥有的。"),
    '修改': ("Please modify the document according to the feedback.", "请根据反馈**修改**文件。"),
    '需要': ("You need a visa to travel to many countries.", "去很多国家旅行**需要**签证。"),
    '学习': ("Learning never stops, no matter your age.", "**学习**永无止境，无论年龄多大。"),
    '严重': ("The situation is serious and requires immediate action.", "情况**严重**，需要立即行动。"),
    '一切': ("Everything is ready for the big event.", "**一切**都为大活动准备好了。"),
    '一直': ("She has always been passionate about teaching.", "她**一直**对教学充满热情。"),
    '已经': ("I have already finished reading that book.", "我**已经**读完那本书了。"),
    '意见': ("We value your feedback on our service.", "我们重视您对我们的服务的**意见**。"),
    '因此': ("He missed the train, therefore he was late for work.", "他错过了火车，**因此**上班迟到了。"),
    '因为': ("She got the job because she was the most qualified.", "她得到了这份工作，**因为**她最有资格。"),
    '引导': ("Teachers guide students toward knowledge.", "老师**引导**学生走向知识。"),
    '优秀': ("She is an outstanding student in every subject.", "她在每门课上都是**优秀**的学生。"),
    '由于': ("Due to bad weather, the flight was delayed.", "**由于**天气不好，航班延误了。"),
    '预防': ("Regular exercise helps prevent many diseases.", "定期锻炼有助于**预防**许多疾病。"),
    '暂时': ("This is only a temporary solution to the problem.", "这只是问题的**暂时**解决方案。"),
    '增长': ("The population has grown rapidly in recent years.", "人口近年来**增长**迅速。"),
    '展览': ("There is an exhibition of modern art at the museum.", "博物馆有一个现代艺术**展览**。"),
    '照顾': ("She looks after her grandmother every weekend.", "她每个周末**照顾**奶奶。"),
    '正常': ("Everything is back to normal after the crisis.", "危机过后一切恢复正常。"),
    '正确': ("Your answer is correct, well done!", "你的答案是**正确**的，做得好！"),
    '证明': ("The facts prove that the plan will work.", "事实**证明**这个计划是可行的。"),
    '政治': ("Politics affects every aspect of our lives.", "**政治**影响着我们生活的方方面面。"),
    '知识': ("Knowledge is the key to unlocking your potential.", "**知识**是释放潜力的钥匙。"),
    '执行': ("The team will execute the plan starting next month.", "团队将从下个月开始**执行**计划。"),
    '制造': ("This factory manufactures automotive parts.", "这家工厂**制造**汽车零件。"),
    '秩序': ("The police maintained order during the event.", "警方在活动期间维持了**秩序**。"),
    '终于': ("After years of effort, she finally succeeded.", "经过多年努力，她**终于**成功了。"),
    '重点': ("The key point is to focus on quality.", "**重点**是关注质量。"),
    '逐渐': ("The situation improved gradually over time.", "情况随时间**逐渐**改善。"),
    '主动': ("She took the initiative to help her colleagues.", "她**主动**帮助同事。"),
    '主要': ("The main reason for his success is hard work.", "他成功的**主要**原因是努力工作。"),
    '著名': ("This city is famous for its historical sites.", "这座城市以历史遗迹**著名**。"),
    '专业': ("What is your major in university?", "你在大学学什么**专业**？"),
    '状态': ("The athlete is in good condition for the competition.", "这位运动员的比赛**状态**很好。"),
    '追求': ("She pursues excellence in everything she does.", "她做任何事都**追求**卓越。"),
    '资源': ("Natural resources should be used sustainably.", "自然**资源**应该可持续地利用。"),
    '仔细': ("Read the contract carefully before signing.", "签合同前要**仔细**阅读。"),
    '自信': ("A confident speaker engages the audience better.", "**自信**的演讲者更能吸引观众。"),
    '总结': ("Let me summarize the key takeaways from today.", "让我**总结**一下今天的要点。"),
    '阻止': ("Nothing can stop her from achieving her goals.", "没有什么能**阻止**她实现目标。"),
}

def main():
    # Read file content
    with open(WORKBANK_PATH, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Extract existing zh values
    existing_zh = set(re.findall(r"zh:\s*'([^']*)'", content))
    print(f"Existing entries: {len(existing_zh)}")
    
    # Filter batch2 words against existing
    unique_batch2 = []
    seen = set(existing_zh)
    for w in BATCH2_WORDS:
        zh = w[0]
        if zh not in seen:
            seen.add(zh)
            unique_batch2.append(w)
    
    print(f"Batch 2: {len(BATCH2_WORDS)} candidates, {len(unique_batch2)} unique new")
    
    # Generate JS entries for batch 2
    new_js_entries = []
    example_count = 0
    for w in unique_batch2:
        zh, en, defn, level, cat = w
        has_example = zh in EXAMPLES_BATCH2
        if has_example:
            example_count += 1
            example_en, example_cn = EXAMPLES_BATCH2[zh]
        else:
            example_en = None
            example_cn = None
        entry_str = make_entry(zh, en, defn, level, cat, example_en, example_cn)
        new_js_entries.append(entry_str)
    
    print(f"Example coverage in batch 2: {example_count}/{len(unique_batch2)} ({example_count/max(len(unique_batch2),1)*100:.1f}%)")
    
    # Find the closing of WORD_BANK array and insert new entries
    # The array ends with "];"
    array_end_marker = content.rfind("];")
    if array_end_marker == -1:
        print("ERROR: Could not find '];' in file")
        return
    
    # Find the position before "];"
    new_entries_block = ",\n" + ",\n".join(new_js_entries)
    new_content = content[:array_end_marker] + new_entries_block + content[array_end_marker:]
    
    # Write file
    with open(WORKBANK_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    # Validate
    final_count = len(re.findall(r"zh:\s*'([^']*)'", new_content))
    print(f"\n✅ Written to {WORKBANK_PATH}")
    print(f"📊 Total entries: {final_count} (added {len(unique_batch2)})")
    
    # Count which entries have examples
    has_ex = len(re.findall(r"example:", new_content))
    print(f"📝 Entries with examples: {has_ex} / {final_count} ({has_ex/final_count*100:.1f}%)")


if __name__ == '__main__':
    main()
