/*
 * IFLL — Extended Word Bank (~672 additional entries)
 * Generated from Obsidian thesaurus inspiration
 * Covers 16 semantic categories for immersive web learning
 */
(function() {
  const EXTRA_WORDS = [
    { zh: '思维', en: 'thinking', def: 'the process of using the mind to reason', level: 'cet4', cat: 'abstract' },
    { zh: '推理', en: 'reasoning', def: 'the action of drawing conclusions logically', level: 'cet6', cat: 'abstract' },
    { zh: '逻辑', en: 'logic', def: 'reasoning conducted according to principles', level: 'cet4', cat: 'abstract' },
    { zh: '判断', en: 'judgment', def: 'the ability to form sound conclusions', level: 'cet4', cat: 'abstract' },
    { zh: '认知', en: 'cognition', def: 'the mental action of acquiring knowledge', level: 'cet6', cat: 'abstract' },
    { zh: '领悟', en: 'comprehend', def: 'to grasp mentally; understand fully', level: 'cet6', cat: 'verb' },
    { zh: '洞察', en: 'insight', def: 'the capacity to gain deep understanding', level: 'cet6', cat: 'abstract' },
    { zh: '辨别', en: 'distinguish', def: 'to recognize differences between things', level: 'cet6', cat: 'verb' },
    { zh: '思索', en: 'ponder', def: 'to think about something carefully', level: 'cet6', cat: 'verb' },
    { zh: '推测', en: 'speculate', def: 'to form a theory without firm evidence', level: 'cet6', cat: 'verb' },
    { zh: '推断', en: 'deduce', def: 'to conclude from reasoning', level: 'cet6', cat: 'verb' },
    { zh: '构思', en: 'conceive', def: 'to form an idea in the mind', level: 'cet6', cat: 'verb' },
    { zh: '设想', en: 'envision', def: 'to imagine as a future possibility', level: 'cet6', cat: 'verb' },
    { zh: '理智', en: 'reason', def: 'the power of the mind to think logically', level: 'cet4', cat: 'abstract' },
    { zh: '直觉', en: 'intuition', def: 'the ability to understand without reasoning', level: 'cet6', cat: 'abstract' },
    { zh: '心智', en: 'mindset', def: 'a habitual mental attitude', level: 'cet6', cat: 'abstract' },
    { zh: '虚构', en: 'fiction', def: 'something invented by the imagination', level: 'cet4', cat: 'abstract' },
    { zh: '幻觉', en: 'illusion', def: 'a false perception of reality', level: 'cet6', cat: 'abstract' },
    { zh: '误解', en: 'misunderstand', def: 'to interpret incorrectly', level: 'cet4', cat: 'verb' },
    { zh: '曲解', en: 'distort', def: 'to twist the meaning of something', level: 'cet6', cat: 'verb' },
    { zh: '领会', en: 'grasp', def: 'to understand something fully', level: 'cet6', cat: 'verb' },
    { zh: '深思', en: 'contemplate', def: 'to look at thoughtfully for a long time', level: 'cet6', cat: 'verb' },
    { zh: '反思', en: 'reflect', def: 'to think deeply about own actions', level: 'cet4', cat: 'verb' },
    { zh: '归纳', en: 'generalize', def: 'to infer a general rule from specifics', level: 'cet6', cat: 'verb' },
    { zh: '联想', en: 'associate', def: 'to connect ideas in the mind', level: 'cet6', cat: 'verb' },
    { zh: '迷惑', en: 'confuse', def: 'to make someone unable to think clearly', level: 'cet4', cat: 'verb' },
    { zh: '模糊', en: 'vague', def: 'not clearly expressed or understood', level: 'cet4', cat: 'adj' },
    { zh: '清晰', en: 'clear', def: 'easy to perceive or understand', level: 'cet4', cat: 'adj' },
    { zh: '混淆', en: 'confound', def: 'to mix up mentally; mistake one for another', level: 'cet6', cat: 'verb' },
    { zh: '察觉', en: 'perceive', def: 'to become aware of through the senses', level: 'cet6', cat: 'verb' },
    { zh: '知晓', en: 'know', def: 'to be aware of through observation', level: 'cet4', cat: 'verb' },
    { zh: '智力', en: 'intellect', def: 'the faculty of reasoning and understanding', level: 'cet4', cat: 'abstract' },
    { zh: '喜悦', en: 'joy', def: 'a feeling of great pleasure and happiness', level: 'cet4', cat: 'emotion' },
    { zh: '悲伤', en: 'sorrow', def: 'a feeling of deep distress caused by loss', level: 'cet4', cat: 'emotion' },
    { zh: '愤怒', en: 'anger', def: 'a strong feeling of displeasure', level: 'cet4', cat: 'emotion' },
    { zh: '恐惧', en: 'fear', def: 'an unpleasant emotion caused by threat', level: 'cet4', cat: 'emotion' },
    { zh: '焦虑', en: 'anxiety', def: 'a feeling of worry or unease', level: 'cet4', cat: 'emotion' },
    { zh: '抑郁', en: 'depression', def: 'a state of low mood and aversion to activity', level: 'cet6', cat: 'emotion' },
    { zh: '厌恶', en: 'disgust', def: 'a strong feeling of disapproval or dislike', level: 'cet6', cat: 'emotion' },
    { zh: '羞愧', en: 'shame', def: 'a painful feeling of humiliation or guilt', level: 'cet4', cat: 'emotion' },
    { zh: '自豪', en: 'pride', def: 'a feeling of deep pleasure from achievement', level: 'cet4', cat: 'emotion' },
    { zh: '遗憾', en: 'regret', def: 'a feeling of sadness over something done wrong', level: 'cet4', cat: 'emotion' },
    { zh: '感激', en: 'gratitude', def: 'a feeling of thankfulness', level: 'cet4', cat: 'emotion' },
    { zh: '同情', en: 'sympathy', def: 'feelings of pity for misfortunes of others', level: 'cet4', cat: 'emotion' },
    { zh: '怜悯', en: 'compassion', def: 'sympathetic pity for the suffering of others', level: 'cet6', cat: 'emotion' },
    { zh: '嫉妒', en: 'jealousy', def: 'resentful envy of anothers advantages', level: 'cet4', cat: 'emotion' },
    { zh: '憎恨', en: 'hatred', def: 'intense dislike or ill will', level: 'cet6', cat: 'emotion' },
    { zh: '欣慰', en: 'relief', def: 'a feeling of reassurance after stress', level: 'cet6', cat: 'emotion' },
    { zh: '烦躁', en: 'irritation', def: 'a state of annoyed impatience', level: 'cet6', cat: 'emotion' },
    { zh: '震惊', en: 'shock', def: 'a sudden upsetting or surprising event', level: 'cet4', cat: 'emotion' },
    { zh: '困惑', en: 'bewilderment', def: 'a state of being confused or puzzled', level: 'cet6', cat: 'emotion' },
    { zh: '满足', en: 'satisfaction', def: 'the state of being fulfilled or content', level: 'cet4', cat: 'emotion' },
    { zh: '憧憬', en: 'longing', def: 'a strong desire for something in the future', level: 'cet6', cat: 'emotion' },
    { zh: '忧郁', en: 'melancholy', def: 'a deep, persistent sadness', level: 'cet6', cat: 'emotion' },
    { zh: '乐趣', en: 'delight', def: 'great pleasure or enjoyment', level: 'cet4', cat: 'emotion' },
    { zh: '苦闷', en: 'anguish', def: 'severe mental or physical pain', level: 'cet6', cat: 'emotion' },
    { zh: '疼爱', en: 'fondness', def: 'affection or liking for someone', level: 'cet6', cat: 'emotion' },
    { zh: '绝望', en: 'despair', def: 'the complete loss of hope', level: 'cet4', cat: 'emotion' },
    { zh: '怨恨', en: 'resentment', def: 'bitter indignation at unfair treatment', level: 'cet6', cat: 'emotion' },
    { zh: '惊喜', en: 'surprise', def: 'a feeling of unexpected delight', level: 'cet4', cat: 'emotion' },
    { zh: '寂寞', en: 'loneliness', def: 'sadness from being without company', level: 'cet4', cat: 'emotion' },
    { zh: '无聊', en: 'boredom', def: 'a state of being weary due to lack of interest', level: 'cet4', cat: 'emotion' },
    { zh: '尴尬', en: 'embarrassment', def: 'a feeling of self-conscious discomfort', level: 'cet4', cat: 'emotion' },
    { zh: '懊悔', en: 'remorse', def: 'deep regret for a wrong committed', level: 'cet6', cat: 'emotion' },
    { zh: '沮丧', en: 'frustration', def: 'the feeling of being upset or annoyed', level: 'cet4', cat: 'emotion' },
    { zh: '陶醉', en: 'enjoyment', def: 'the state of taking pleasure in something', level: 'cet6', cat: 'emotion' },
    { zh: '冷淡', en: 'indifference', def: 'lack of interest or concern', level: 'cet6', cat: 'emotion' },
    { zh: '热情', en: 'passion', def: 'strong and barely controllable emotion', level: 'cet4', cat: 'emotion' },
    { zh: '温情', en: 'tenderness', def: 'gentle and caring feelings', level: 'cet6', cat: 'emotion' },
    { zh: '渴望', en: 'eagerness', def: 'keen and enthusiastic desire', level: 'cet4', cat: 'emotion' },
    { zh: '乐观', en: 'optimistic', def: 'positive and hopeful about the future', level: 'cet4', cat: 'adj' },
    { zh: '悲观', en: 'pessimistic', def: 'tending to see the worst aspect of things', level: 'cet4', cat: 'adj' },
    { zh: '傲慢', en: 'arrogant', def: 'having an exaggerated sense of self-worth', level: 'cet6', cat: 'adj' },
    { zh: '谦虚', en: 'modest', def: 'not excessively proud of oneself', level: 'cet4', cat: 'adj' },
    { zh: '固执', en: 'stubborn', def: 'unreasonably unwilling to change ones mind', level: 'cet4', cat: 'adj' },
    { zh: '慷慨', en: 'generous', def: 'freely giving more than is expected', level: 'cet4', cat: 'adj' },
    { zh: '自私', en: 'selfish', def: 'concerned chiefly with own interests', level: 'cet4', cat: 'adj' },
    { zh: '真诚', en: 'sincere', def: 'free from pretense or deceit', level: 'cet4', cat: 'adj' },
    { zh: '虚伪', en: 'hypocritical', def: 'pretending to have virtues one does not have', level: 'cet6', cat: 'adj' },
    { zh: '懒惰', en: 'lazy', def: 'unwilling to work or use energy', level: 'cet4', cat: 'adj' },
    { zh: '勤奋', en: 'diligent', def: 'careful and persistent in work', level: 'cet4', cat: 'adj' },
    { zh: '勇敢', en: 'brave', def: 'ready to face danger or pain', level: 'cet4', cat: 'adj' },
    { zh: '懦弱', en: 'cowardly', def: 'lacking courage or resolve', level: 'cet6', cat: 'adj' },
    { zh: '温柔', en: 'gentle', def: 'mild and kind in temperament', level: 'cet4', cat: 'adj' },
    { zh: '粗暴', en: 'rude', def: 'offensively impolite or ill-mannered', level: 'cet4', cat: 'adj' },
    { zh: '谨慎', en: 'cautious', def: 'careful to avoid potential problems', level: 'cet4', cat: 'adj' },
    { zh: '鲁莽', en: 'reckless', def: 'acting without care for consequences', level: 'cet6', cat: 'adj' },
    { zh: '忠诚', en: 'loyal', def: 'giving firm and constant support', level: 'cet4', cat: 'adj' },
    { zh: '背叛', en: 'betray', def: 'to be disloyal to a trust', level: 'cet4', cat: 'verb' },
    { zh: '顺从', en: 'obedient', def: 'complying with orders or requests', level: 'cet6', cat: 'adj' },
    { zh: '叛逆', en: 'rebellious', def: 'showing a desire to resist authority', level: 'cet6', cat: 'adj' },
    { zh: '正直', en: 'honest', def: 'truthful and morally upright', level: 'cet4', cat: 'adj' },
    { zh: '狡猾', en: 'sly', def: 'cunning and deceitful in nature', level: 'cet6', cat: 'adj' },
    { zh: '善良', en: 'kind', def: 'having a good and gentle nature', level: 'cet4', cat: 'adj' },
    { zh: '残忍', en: 'cruel', def: 'causing pain or suffering without pity', level: 'cet4', cat: 'adj' },
    { zh: '友好', en: 'friendly', def: 'kind and pleasant toward others', level: 'cet4', cat: 'adj' },
    { zh: '冷漠', en: 'apathetic', def: 'showing no interest or emotion', level: 'cet6', cat: 'adj' },
    { zh: '坦率', en: 'frank', def: 'open and honest in expression', level: 'cet6', cat: 'adj' },
    { zh: '幽默', en: 'humorous', def: 'funny; causing laughter or amusement', level: 'cet4', cat: 'adj' },
    { zh: '严肃', en: 'serious', def: 'earnest and not light-hearted', level: 'cet4', cat: 'adj' },
    { zh: '挑剔', en: 'picky', def: 'very careful in making choices', level: 'cet6', cat: 'adj' },
    { zh: '宽容', en: 'tolerant', def: 'showing willingness to accept different views', level: 'cet6', cat: 'adj' },
    { zh: '吝啬', en: 'stingy', def: 'unwilling to spend money or resources', level: 'cet6', cat: 'adj' },
    { zh: '果断', en: 'decisive', def: 'able to make decisions quickly', level: 'cet6', cat: 'adj' },
    { zh: '深沉', en: 'reserved', def: 'tending to keep feelings private', level: 'cet6', cat: 'adj' },
    { zh: '极度', en: 'extremely', def: 'to a very great degree', level: 'cet4', cat: 'adverb' },
    { zh: '略微', en: 'slightly', def: 'to a small degree; a little', level: 'cet4', cat: 'adverb' },
    { zh: '颇为', en: 'quite', def: 'to a significant extent', level: 'cet6', cat: 'adverb' },
    { zh: '过于', en: 'excessively', def: 'to a greater degree than is necessary', level: 'cet4', cat: 'adverb' },
    { zh: '足以', en: 'sufficiently', def: 'enough to meet a purpose', level: 'cet4', cat: 'adverb' },
    { zh: '深刻', en: 'profound', def: 'very great or intense in depth', level: 'cet4', cat: 'adj' },
    { zh: '轻微', en: 'mild', def: 'gentle and not severe', level: 'cet4', cat: 'adj' },
    { zh: '强烈', en: 'intense', def: 'extreme in strength or degree', level: 'cet4', cat: 'adj' },
    { zh: '适度', en: 'moderate', def: 'within reasonable limits; not extreme', level: 'cet4', cat: 'adj' },
    { zh: '充足', en: 'ample', def: 'enough or more than enough', level: 'cet4', cat: 'adj' },
    { zh: '匮乏', en: 'scarce', def: 'insufficient for the demand', level: 'cet6', cat: 'adj' },
    { zh: '显著', en: 'remarkable', def: 'worthy of attention; striking', level: 'cet4', cat: 'adj' },
    { zh: '大体', en: 'roughly', def: 'in general terms; approximately', level: 'cet4', cat: 'adverb' },
    { zh: '纯粹', en: 'pure', def: 'not mixed with any other substance', level: 'cet4', cat: 'adj' },
    { zh: '深厚', en: 'deep', def: 'very intense or profound', level: 'cet4', cat: 'adj' },
    { zh: '肤浅', en: 'shallow', def: 'not deep; lacking depth of understanding', level: 'cet6', cat: 'adj' },
    { zh: '狭小', en: 'narrow', def: 'limited in extent or scope', level: 'cet4', cat: 'adj' },
    { zh: '广阔', en: 'vast', def: 'very great in extent or size', level: 'cet4', cat: 'adj' },
    { zh: '差劲', en: 'poor', def: 'of a low quality or standard', level: 'cet4', cat: 'adj' },
    { zh: '优秀', en: 'excellent', def: 'extremely good; outstanding', level: 'cet4', cat: 'adj' },
    { zh: '杰出', en: 'outstanding', def: 'remarkably good or excellent', level: 'cet4', cat: 'adj' },
    { zh: '薄弱', en: 'weak', def: 'lacking strength or effectiveness', level: 'cet4', cat: 'adj' },
    { zh: '强劲', en: 'robust', def: 'strong and healthy in capability', level: 'cet6', cat: 'adj' },
    { zh: '勉强', en: 'barely', def: 'only just; by a narrow margin', level: 'cet4', cat: 'adverb' },
    { zh: '充分', en: 'fully', def: 'to the greatest degree possible', level: 'cet4', cat: 'adverb' },
    { zh: '过度', en: 'overly', def: 'excessively; too much', level: 'cet4', cat: 'adverb' },
    { zh: '大抵', en: 'generally', def: 'in most cases; usually', level: 'cet6', cat: 'adverb' },
    { zh: '极力', en: 'utmost', def: 'the greatest possible degree or effort', level: 'cet6', cat: 'adverb' },
    { zh: '丝毫', en: 'slightly', def: 'the smallest amount or degree', level: 'cet4', cat: 'adverb' },
    { zh: '进度', en: 'progress', def: 'forward movement toward a goal', level: 'cet4', cat: 'abstract' },
    { zh: '推进', en: 'advance', def: 'to move forward in a purposeful way', level: 'cet4', cat: 'verb' },
    { zh: '停滞', en: 'stagnate', def: 'to cease to develop or advance', level: 'cet6', cat: 'verb' },
    { zh: '延误', en: 'delay', def: 'to make later than planned', level: 'cet4', cat: 'verb' },
    { zh: '加速', en: 'accelerate', def: 'to increase in speed or rate', level: 'cet4', cat: 'verb' },
    { zh: '减缓', en: 'slow', def: 'to reduce the speed or rate of', level: 'cet4', cat: 'verb' },
    { zh: '启动', en: 'launch', def: 'to set in motion or begin', level: 'cet4', cat: 'verb' },
    { zh: '终止', en: 'terminate', def: 'to bring to an end', level: 'cet6', cat: 'verb' },
    { zh: '暂停', en: 'pause', def: 'to stop temporarily', level: 'cet4', cat: 'verb' },
    { zh: '延续', en: 'extend', def: 'to prolong in time or space', level: 'cet4', cat: 'verb' },
    { zh: '中断', en: 'interrupt', def: 'to break the continuity of', level: 'cet4', cat: 'verb' },
    { zh: '筹备', en: 'prepare', def: 'to make ready for a future event', level: 'cet6', cat: 'verb' },
    { zh: '酝酿', en: 'brew', def: 'to develop gradually over time', level: 'cet6', cat: 'verb' },
    { zh: '过渡', en: 'transition', def: 'the process of changing from one state', level: 'cet4', cat: 'abstract' },
    { zh: '步骤', en: 'step', def: 'an individual action in a sequence', level: 'cet4', cat: 'abstract' },
    { zh: '环节', en: 'segment', def: 'a distinct part of a process', level: 'cet6', cat: 'abstract' },
    { zh: '流程', en: 'workflow', def: 'a sequence of processes through work', level: 'cet6', cat: 'abstract' },
    { zh: '次序', en: 'order', def: 'the arrangement of things in sequence', level: 'cet4', cat: 'abstract' },
    { zh: '排序', en: 'sort', def: 'to arrange in a particular order', level: 'cet4', cat: 'verb' },
    { zh: '着手', en: 'undertake', def: 'to begin or set about doing something', level: 'cet6', cat: 'verb' },
    { zh: '完工', en: 'finish', def: 'to complete a building or work', level: 'cet4', cat: 'verb' },
    { zh: '竣工', en: 'complete', def: 'to finish the construction of', level: 'cet6', cat: 'verb' },
    { zh: '进展', en: 'progress', def: 'development toward a desired outcome', level: 'cet4', cat: 'abstract' },
    { zh: '回溯', en: 'retrace', def: 'to go back over a path or sequence', level: 'cet6', cat: 'verb' },
    { zh: '循环', en: 'cycle', def: 'a repeated sequence of events', level: 'cet4', cat: 'abstract' },
    { zh: '迭代', en: 'iterate', def: 'to repeat a process for improvement', level: 'cet6', cat: 'verb' },
    { zh: '串联', en: 'sequence', def: 'to arrange in a connected series', level: 'cet6', cat: 'verb' },
    { zh: '并联', en: 'parallel', def: 'side-by-side and simultaneous', level: 'cet6', cat: 'adj' },
    { zh: '速度', en: 'speed', def: 'the rate at which something moves', level: 'cet4', cat: 'abstract' },
    { zh: '实体', en: 'entity', def: 'a thing with distinct existence', level: 'cet6', cat: 'abstract' },
    { zh: '虚无', en: 'nothingness', def: 'the state of being nothing', level: 'cet6', cat: 'abstract' },
    { zh: '客观', en: 'objective', def: 'based on facts, not feelings', level: 'cet4', cat: 'adj' },
    { zh: '主观', en: 'subjective', def: 'based on personal opinions or feelings', level: 'cet4', cat: 'adj' },
    { zh: '绝对', en: 'absolute', def: 'not dependent on other things', level: 'cet4', cat: 'adj' },
    { zh: '永恒', en: 'eternal', def: 'lasting or existing forever', level: 'cet4', cat: 'adj' },
    { zh: '短暂', en: 'brief', def: 'lasting for a short time', level: 'cet4', cat: 'adj' },
    { zh: '虚拟', en: 'virtual', def: 'simulated or existing in digital form', level: 'cet4', cat: 'adj' },
    { zh: '真实', en: 'genuine', def: 'truly what something is said to be', level: 'cet4', cat: 'adj' },
    { zh: '虚假', en: 'false', def: 'not according with truth or fact', level: 'cet4', cat: 'adj' },
    { zh: '潜在', en: 'latent', def: 'existing but not yet developed', level: 'cet6', cat: 'adj' },
    { zh: '固有', en: 'inherent', def: 'existing as a natural part of', level: 'cet6', cat: 'adj' },
    { zh: '天然', en: 'natural', def: 'existing in nature; not made by humans', level: 'cet4', cat: 'adj' },
    { zh: '空洞', en: 'empty', def: 'lacking substance or meaning', level: 'cet4', cat: 'adj' },
    { zh: '充实', en: 'substantial', def: 'of considerable importance or size', level: 'cet4', cat: 'adj' },
    { zh: '缺席', en: 'absence', def: 'the state of being away or not present', level: 'cet4', cat: 'abstract' },
    { zh: '诞生', en: 'birth', def: 'the emergence of a new entity', level: 'cet4', cat: 'abstract' },
    { zh: '消亡', en: 'perish', def: 'to cease to exist gradually', level: 'cet6', cat: 'verb' },
    { zh: '幸存', en: 'survive', def: 'to continue to exist despite hardship', level: 'cet4', cat: 'verb' },
    { zh: '消失', en: 'vanish', def: 'to cease to be visible or exist', level: 'cet4', cat: 'verb' },
    { zh: '浮现', en: 'emerge', def: 'to come into view or existence', level: 'cet6', cat: 'verb' },
    { zh: '显现', en: 'manifest', def: 'to become clear or visible', level: 'cet6', cat: 'verb' },
    { zh: '评价', en: 'evaluate', def: 'to determine the value or quality of', level: 'cet4', cat: 'verb' },
    { zh: '鉴定', en: 'appraise', def: 'to assess the value or quality of', level: 'cet6', cat: 'verb' },
    { zh: '论断', en: 'assert', def: 'to state a conclusion confidently', level: 'cet6', cat: 'verb' },
    { zh: '界定', en: 'define', def: 'to state the precise meaning of', level: 'cet4', cat: 'verb' },
    { zh: '裁决', en: 'arbitrate', def: 'to settle a dispute by judgment', level: 'cet6', cat: 'verb' },
    { zh: '否决', en: 'reject', def: 'to refuse to accept or approve', level: 'cet6', cat: 'verb' },
    { zh: '认可', en: 'approve', def: 'to officially agree to or accept', level: 'cet4', cat: 'verb' },
    { zh: '质疑', en: 'question', def: 'to express doubt about something', level: 'cet4', cat: 'verb' },
    { zh: '权衡', en: 'weigh', def: 'to consider carefully before deciding', level: 'cet6', cat: 'verb' },
    { zh: '断定', en: 'conclude', def: 'to reach a firm decision about', level: 'cet6', cat: 'verb' },
    { zh: '预估', en: 'estimate', def: 'to roughly calculate or judge', level: 'cet4', cat: 'verb' },
    { zh: '评比', en: 'compare', def: 'to evaluate relative merits', level: 'cet6', cat: 'verb' },
    { zh: '鉴别', en: 'identify', def: 'to recognize as being a particular thing', level: 'cet6', cat: 'verb' },
    { zh: '衡量', en: 'measure', def: 'to assess the extent or quality of', level: 'cet4', cat: 'verb' },
    { zh: '筛选', en: 'filter', def: 'to select the best from a group', level: 'cet4', cat: 'verb' },
    { zh: '优选', en: 'select', def: 'to choose as best or most suitable', level: 'cet4', cat: 'verb' },
    { zh: '参考', en: 'reference', def: 'the use of information for evaluation', level: 'cet4', cat: 'abstract' },
    { zh: '偏见', en: 'bias', def: 'a prejudice in favor or against', level: 'cet4', cat: 'abstract' },
    { zh: '片面', en: 'one-sided', def: 'considering only one aspect', level: 'cet6', cat: 'adj' },
    { zh: '可靠', en: 'reliable', def: 'consistently good in quality', level: 'cet4', cat: 'adj' },
    { zh: '可疑', en: 'suspicious', def: 'arousing distrust or doubt', level: 'cet4', cat: 'adj' },
    { zh: '可信', en: 'credible', def: 'able to be believed; trustworthy', level: 'cet6', cat: 'adj' },
    { zh: '合理', en: 'reasonable', def: 'based on good sense or logic', level: 'cet4', cat: 'adj' },
    { zh: '荒谬', en: 'absurd', def: 'wildly unreasonable or illogical', level: 'cet6', cat: 'adj' },
    { zh: '明智', en: 'wise', def: 'showing good judgment and prudence', level: 'cet4', cat: 'adj' },
    { zh: '交往', en: 'interact', def: 'to communicate or engage with others', level: 'cet4', cat: 'verb' },
    { zh: '交际', en: 'socialize', def: 'to mix socially with others', level: 'cet6', cat: 'verb' },
    { zh: '联络', en: 'contact', def: 'to get in touch with someone', level: 'cet4', cat: 'verb' },
    { zh: '相处', en: 'get-along', def: 'to have a harmonious relationship', level: 'cet4', cat: 'verb' },
    { zh: '团结', en: 'unite', def: 'to come together for a common purpose', level: 'cet4', cat: 'verb' },
    { zh: '分裂', en: 'divide', def: 'to separate into opposing groups', level: 'cet4', cat: 'verb' },
    { zh: '对立', en: 'oppose', def: 'to be in conflict or opposition', level: 'cet6', cat: 'verb' },
    { zh: '融洽', en: 'harmonious', def: 'having a pleasing relationship', level: 'cet6', cat: 'adj' },
    { zh: '亲密', en: 'intimate', def: 'very close in relationship', level: 'cet4', cat: 'adj' },
    { zh: '疏远', en: 'distant', def: 'not close in relationship; aloof', level: 'cet6', cat: 'adj' },
    { zh: '纽带', en: 'bond', def: 'something that connects people', level: 'cet6', cat: 'abstract' },
    { zh: '归属', en: 'belonging', def: 'a feeling of being accepted', level: 'cet6', cat: 'abstract' },
    { zh: '隔阂', en: 'estrangement', def: 'a state of mutual distance in relations', level: 'cet6', cat: 'abstract' },
    { zh: '协作', en: 'collaborate', def: 'to work jointly on an activity', level: 'cet4', cat: 'verb' },
    { zh: '盟友', en: 'ally', def: 'a person or group united with another', level: 'cet6', cat: 'abstract' },
    { zh: '对手', en: 'rival', def: 'a person competing with another', level: 'cet4', cat: 'abstract' },
    { zh: '伙伴', en: 'partner', def: 'a person you work or do things with', level: 'cet4', cat: 'daily' },
    { zh: '同胞', en: 'compatriot', def: 'a person from the same country', level: 'cet6', cat: 'daily' },
    { zh: '亲属', en: 'relative', def: 'a person connected by blood or marriage', level: 'cet4', cat: 'daily' },
    { zh: '配偶', en: 'spouse', def: 'a husband or wife; marriage partner', level: 'cet4', cat: 'daily' },
    { zh: '长辈', en: 'elder', def: 'a person of greater age or authority', level: 'cet4', cat: 'daily' },
    { zh: '晚辈', en: 'junior', def: 'a person younger or lower in rank', level: 'cet4', cat: 'daily' },
    { zh: '同辈', en: 'peer', def: 'a person of similar age or status', level: 'cet6', cat: 'daily' },
    { zh: '社交', en: 'social', def: 'relating to society or companionship', level: 'cet4', cat: 'abstract' },
    { zh: '敌意', en: 'hostility', def: 'unfriendly or antagonistic behavior', level: 'cet6', cat: 'abstract' },
    { zh: '友谊', en: 'friendship', def: 'the emotions of mutual friendship', level: 'cet4', cat: 'abstract' },
    { zh: '和睦', en: 'harmony', def: 'a state of peaceful agreement', level: 'cet6', cat: 'abstract' },
    { zh: '既然', en: 'since', def: 'used to introduce a logical premise', level: 'cet4', cat: 'logic' },
    { zh: '尚且', en: 'even', def: 'used to emphasize a logical extreme', level: 'cet6', cat: 'logic' },
    { zh: '何况', en: 'let-alone', def: 'used to add a stronger point', level: 'cet6', cat: 'logic' },
    { zh: '况且', en: 'besides', def: 'used to add an additional reason', level: 'cet6', cat: 'logic' },
    { zh: '乃至', en: 'even', def: 'extending to the point of including', level: 'cet6', cat: 'logic' },
    { zh: '以及', en: 'as-well-as', def: 'and in addition; along with', level: 'cet4', cat: 'logic' },
    { zh: '与其', en: 'rather-than', def: 'indicating a preference in comparison', level: 'cet4', cat: 'logic' },
    { zh: '宁可', en: 'prefer', def: 'would rather; choosing one over another', level: 'cet4', cat: 'logic' },
    { zh: '要么', en: 'either', def: 'used to introduce alternatives', level: 'cet4', cat: 'logic' },
    { zh: '否则', en: 'otherwise', def: 'if not; or else', level: 'cet4', cat: 'logic' },
    { zh: '反之', en: 'conversely', def: 'in an opposite way or manner', level: 'cet6', cat: 'logic' },
    { zh: '以便', en: 'so-that', def: 'in order to; for the purpose of', level: 'cet4', cat: 'logic' },
    { zh: '以免', en: 'lest', def: 'to avoid the risk of something', level: 'cet6', cat: 'logic' },
    { zh: '鉴于', en: 'given-that', def: 'considering the fact that', level: 'cet6', cat: 'logic' },
    { zh: '基于', en: 'based-on', def: 'using something as a starting point', level: 'cet4', cat: 'logic' },
    { zh: '按照', en: 'according-to', def: 'as stated or directed by', level: 'cet4', cat: 'logic' },
    { zh: '凭借', en: 'rely-on', def: 'using something as a means', level: 'cet6', cat: 'logic' },
    { zh: '任凭', en: 'regardless', def: 'without being affected by; no matter', level: 'cet6', cat: 'logic' },
    { zh: '纵使', en: 'even-if', def: 'even though; despite the condition', level: 'cet6', cat: 'logic' },
    { zh: '不论', en: 'whether', def: 'expressing a choice between options', level: 'cet4', cat: 'logic' },
    { zh: '无非', en: 'merely', def: 'nothing more than; only', level: 'cet6', cat: 'logic' },
    { zh: '譬如', en: 'for-instance', def: 'as an example; for example', level: 'cet6', cat: 'logic' },
    { zh: '例如', en: 'for-example', def: 'used to introduce an example', level: 'cet4', cat: 'logic' },
    { zh: '诸如', en: 'such-as', def: 'for example; like', level: 'cet6', cat: 'logic' },
    { zh: '众多', en: 'numerous', def: 'great in number; many', level: 'cet4', cat: 'adj' },
    { zh: '稀少', en: 'rare', def: 'not occurring very often', level: 'cet4', cat: 'adj' },
    { zh: '丰富', en: 'abundant', def: 'existing in large quantities', level: 'cet4', cat: 'adj' },
    { zh: '贫乏', en: 'deficient', def: 'lacking in quantity or quality', level: 'cet6', cat: 'adj' },
    { zh: '繁多', en: 'various', def: 'many and of different kinds', level: 'cet4', cat: 'adj' },
    { zh: '单一', en: 'single', def: 'only one; not multiple', level: 'cet4', cat: 'adj' },
    { zh: '加倍', en: 'double', def: 'twice as much or many', level: 'cet4', cat: 'adj' },
    { zh: '多半', en: 'mostly', def: 'for the most part; mainly', level: 'cet4', cat: 'adverb' },
    { zh: '少量', en: 'a-little', def: 'a small amount or number', level: 'cet4', cat: 'adj' },
    { zh: '大量', en: 'a-lot-of', def: 'a large amount or number', level: 'cet4', cat: 'adj' },
    { zh: '全体', en: 'all', def: 'the whole number or amount', level: 'cet4', cat: 'adj' },
    { zh: '部分', en: 'part', def: 'a piece or segment of a whole', level: 'cet4', cat: 'abstract' },
    { zh: '剩余', en: 'remainder', def: 'what is left after use', level: 'cet4', cat: 'abstract' },
    { zh: '总数', en: 'total', def: 'the whole sum or amount', level: 'cet4', cat: 'abstract' },
    { zh: '平均', en: 'average', def: 'the typical or normal amount', level: 'cet4', cat: 'adj' },
    { zh: '额外', en: 'extra', def: 'added to a usual amount', level: 'cet4', cat: 'adj' },
    { zh: '多余', en: 'surplus', def: 'more than what is needed', level: 'cet4', cat: 'adj' },
    { zh: '缺乏', en: 'lack', def: 'not having enough of something', level: 'cet4', cat: 'verb' },
    { zh: '无穷', en: 'infinite', def: 'limitless in amount or extent', level: 'cet4', cat: 'adj' },
    { zh: '有限', en: 'limited', def: 'restricted in size or amount', level: 'cet4', cat: 'adj' },
    { zh: '对比', en: 'contrast', def: 'the state of being different', level: 'cet4', cat: 'abstract' },
    { zh: '差异', en: 'difference', def: 'a way in which things differ', level: 'cet4', cat: 'abstract' },
    { zh: '相似', en: 'similarity', def: 'the quality of being alike', level: 'cet4', cat: 'abstract' },
    { zh: '等同', en: 'equivalent', def: 'equal in value or meaning', level: 'cet6', cat: 'adj' },
    { zh: '悬殊', en: 'disparity', def: 'a great difference between things', level: 'cet6', cat: 'abstract' },
    { zh: '均匀', en: 'uniform', def: 'consistent in form or distribution', level: 'cet4', cat: 'adj' },
    { zh: '稀疏', en: 'sparse', def: 'thinly dispersed or scattered', level: 'cet6', cat: 'adj' },
    { zh: '密集', en: 'dense', def: 'closely packed together', level: 'cet4', cat: 'adj' },
    { zh: '累计', en: 'cumulative', def: 'increasing by successive addition', level: 'cet4', cat: 'adj' },
    { zh: '转变', en: 'transform', def: 'to make a thorough change in form', level: 'cet4', cat: 'verb' },
    { zh: '转化', en: 'convert', def: 'to change from one form to another', level: 'cet4', cat: 'verb' },
    { zh: '演变', en: 'evolve', def: 'to develop gradually over time', level: 'cet4', cat: 'verb' },
    { zh: '变革', en: 'revolution', def: 'a dramatic change in a system', level: 'cet4', cat: 'abstract' },
    { zh: '变迁', en: 'shift', def: 'a gradual change over time', level: 'cet6', cat: 'abstract' },
    { zh: '动荡', en: 'turmoil', def: 'a state of great change or disturbance', level: 'cet6', cat: 'abstract' },
    { zh: '稳定', en: 'stable', def: 'not likely to change or move', level: 'cet4', cat: 'adj' },
    { zh: '固定', en: 'fixed', def: 'firmly in place; not moving', level: 'cet4', cat: 'adj' },
    { zh: '灵活', en: 'flexible', def: 'able to change readily', level: 'cet4', cat: 'adj' },
    { zh: '僵化', en: 'rigid', def: 'unable to change or adapt', level: 'cet6', cat: 'adj' },
    { zh: '扭转', en: 'reverse', def: 'to turn the opposite direction', level: 'cet6', cat: 'verb' },
    { zh: '翻转', en: 'flip', def: 'to turn over or upside down', level: 'cet4', cat: 'verb' },
    { zh: '波动', en: 'fluctuate', def: 'to rise and fall irregularly', level: 'cet6', cat: 'verb' },
    { zh: '变异', en: 'mutate', def: 'to change in form or nature', level: 'cet6', cat: 'verb' },
    { zh: '暂时', en: 'temporary', def: 'lasting for only a limited time', level: 'cet4', cat: 'adj' },
    { zh: '持续', en: 'sustained', def: 'continuing for an extended period', level: 'cet4', cat: 'adj' },
    { zh: '间断', en: 'intermittent', def: 'occurring at irregular intervals', level: 'cet6', cat: 'adj' },
    { zh: '连贯', en: 'coherent', def: 'logically consistent and connected', level: 'cet6', cat: 'adj' },
    { zh: '日常', en: 'daily', def: 'done or occurring every day', level: 'cet4', cat: 'adj' },
    { zh: '往常', en: 'usual', def: 'habitual or customary', level: 'cet4', cat: 'adj' },
    { zh: '如常', en: 'as-usual', def: 'in the customary manner', level: 'cet6', cat: 'adverb' },
    { zh: '依旧', en: 'still', def: 'as before; unchanged', level: 'cet4', cat: 'adverb' },
    { zh: '照旧', en: 'same', def: 'unchanged in condition', level: 'cet4', cat: 'adverb' },
    { zh: '突变', en: 'sudden-change', def: 'an abrupt or unexpected change', level: 'cet6', cat: 'abstract' },
    { zh: '进化', en: 'evolution', def: 'the process of gradual development', level: 'cet4', cat: 'abstract' },
    { zh: '退化', en: 'degenerate', def: 'to decline in quality or function', level: 'cet6', cat: 'verb' },
    { zh: '革新', en: 'innovate', def: 'to introduce significant changes', level: 'cet6', cat: 'verb' },
    { zh: '稳固', en: 'steady', def: 'firmly fixed and not changing', level: 'cet4', cat: 'adj' },
    { zh: '保障', en: 'safeguard', def: 'to protect from harm or risk', level: 'cet4', cat: 'verb' },
    { zh: '防范', en: 'prevent', def: 'to keep something bad from happening', level: 'cet4', cat: 'verb' },
    { zh: '防御', en: 'defend', def: 'to protect against attack', level: 'cet4', cat: 'verb' },
    { zh: '避难', en: 'take-refuge', def: 'to seek shelter from danger', level: 'cet6', cat: 'verb' },
    { zh: '威胁', en: 'threaten', def: 'to express intention to harm', level: 'cet4', cat: 'verb' },
    { zh: '袭击', en: 'attack', def: 'to act aggressively against', level: 'cet4', cat: 'verb' },
    { zh: '毁灭', en: 'destroy', def: 'to damage irreparably', level: 'cet4', cat: 'verb' },
    { zh: '挽救', en: 'rescue', def: 'to save from danger or loss', level: 'cet4', cat: 'verb' },
    { zh: '防护', en: 'protect', def: 'to shield from harm', level: 'cet4', cat: 'verb' },
    { zh: '隐患', en: 'hidden-danger', def: 'a lurking potential hazard', level: 'cet6', cat: 'abstract' },
    { zh: '警报', en: 'alert', def: 'a warning of imminent danger', level: 'cet4', cat: 'daily' },
    { zh: '警戒', en: 'vigilance', def: 'watchful attention to danger', level: 'cet6', cat: 'abstract' },
    { zh: '损伤', en: 'damage', def: 'physical harm impairing function', level: 'cet4', cat: 'abstract' },
    { zh: '创伤', en: 'trauma', def: 'a deeply distressing injury', level: 'cet6', cat: 'abstract' },
    { zh: '死亡', en: 'death', def: 'the end of life', level: 'cet4', cat: 'abstract' },
    { zh: '生存', en: 'existence', def: 'the state of continuing to live', level: 'cet4', cat: 'abstract' },
    { zh: '生命', en: 'life', def: 'the condition of being alive', level: 'cet4', cat: 'daily' },
    { zh: '伤亡', en: 'casualty', def: 'a person killed or injured', level: 'cet6', cat: 'abstract' },
    { zh: '脆弱', en: 'fragile', def: 'easily broken or damaged', level: 'cet4', cat: 'adj' },
    { zh: '坚固', en: 'sturdy', def: 'strongly built and durable', level: 'cet6', cat: 'adj' },
    { zh: '牢固', en: 'secure', def: 'firmly fixed and safe', level: 'cet4', cat: 'adj' },
    { zh: '冒险', en: 'risk', def: 'to engage in dangerous activity', level: 'cet4', cat: 'verb' },
    { zh: '避险', en: 'hedge', def: 'to avoid or reduce risk', level: 'cet6', cat: 'verb' },
    { zh: '致命', en: 'deadly', def: 'causing or able to cause death', level: 'cet4', cat: 'adj' },
    { zh: '无害', en: 'harmless', def: 'not likely to cause injury', level: 'cet4', cat: 'adj' },
    { zh: '有毒', en: 'toxic', def: 'poisonous; harmful to health', level: 'cet4', cat: 'adj' },
    { zh: '引发', en: 'trigger', def: 'to cause something to happen', level: 'cet4', cat: 'verb' },
    { zh: '导致', en: 'lead-to', def: 'to bring about as a consequence', level: 'cet4', cat: 'verb' },
    { zh: '促成', en: 'facilitate', def: 'to make an event more likely', level: 'cet6', cat: 'verb' },
    { zh: '起源', en: 'originate', def: 'to have a beginning or source', level: 'cet4', cat: 'verb' },
    { zh: '源于', en: 'stem-from', def: 'to originate or be derived from', level: 'cet6', cat: 'verb' },
    { zh: '归因', en: 'attribute', def: 'to regard as being caused by', level: 'cet6', cat: 'verb' },
    { zh: '后果', en: 'consequence', def: 'the result of an earlier action', level: 'cet4', cat: 'abstract' },
    { zh: '效应', en: 'effect', def: 'a change resulting from a cause', level: 'cet4', cat: 'abstract' },
    { zh: '根源', en: 'root-cause', def: 'the basic cause of something', level: 'cet6', cat: 'abstract' },
    { zh: '诱因', en: 'inducement', def: 'a factor that provokes an event', level: 'cet6', cat: 'abstract' },
    { zh: '动机', en: 'motive', def: 'a reason for doing something', level: 'cet4', cat: 'abstract' },
    { zh: '激发', en: 'stimulate', def: 'to encourage or rouse to action', level: 'cet4', cat: 'verb' },
    { zh: '抑制', en: 'inhibit', def: 'to hinder or restrain a process', level: 'cet6', cat: 'verb' },
    { zh: '催生', en: 'spawn', def: 'to cause to develop or appear', level: 'cet6', cat: 'verb' },
    { zh: '加剧', en: 'intensify', def: 'to make more extreme or severe', level: 'cet6', cat: 'verb' },
    { zh: '缓和', en: 'mitigate', def: 'to make less severe or serious', level: 'cet6', cat: 'verb' },
    { zh: '激起', en: 'arouse', def: 'to evoke or awaken a feeling', level: 'cet4', cat: 'verb' },
    { zh: '连锁', en: 'chain', def: 'a connected series of events', level: 'cet6', cat: 'abstract' },
    { zh: '推动', en: 'prompt', def: 'to cause someone to take action', level: 'cet4', cat: 'verb' },
    { zh: '促使', en: 'impel', def: 'to drive or urge forward', level: 'cet6', cat: 'verb' },
    { zh: '功效', en: 'efficacy', def: 'the ability to produce a desired result', level: 'cet6', cat: 'abstract' },
    { zh: '获取', en: 'acquire', def: 'to obtain through own effort', level: 'cet4', cat: 'verb' },
    { zh: '索取', en: 'demand', def: 'to ask for something forcefully', level: 'cet4', cat: 'verb' },
    { zh: '赐予', en: 'grant', def: 'to give something formally', level: 'cet6', cat: 'verb' },
    { zh: '捐献', en: 'donate', def: 'to give something for a cause', level: 'cet4', cat: 'verb' },
    { zh: '支付', en: 'pay', def: 'to give money in exchange for goods', level: 'cet4', cat: 'verb' },
    { zh: '补偿', en: 'compensate', def: 'to make up for a loss or injury', level: 'cet4', cat: 'verb' },
    { zh: '赔偿', en: 'reimburse', def: 'to repay someone for expenses', level: 'cet6', cat: 'verb' },
    { zh: '盗窃', en: 'steal', def: 'to take without permission', level: 'cet4', cat: 'verb' },
    { zh: '掠夺', en: 'plunder', def: 'to take goods by force', level: 'cet6', cat: 'verb' },
    { zh: '耗费', en: 'consume', def: 'to use up a resource', level: 'cet4', cat: 'verb' },
    { zh: '节省', en: 'save', def: 'to use less of a resource', level: 'cet4', cat: 'verb' },
    { zh: '浪费', en: 'waste', def: 'to use carelessly or extravagantly', level: 'cet4', cat: 'verb' },
    { zh: '保留', en: 'retain', def: 'to keep or continue to have', level: 'cet4', cat: 'verb' },
    { zh: '扣除', en: 'deduct', def: 'to subtract from a total', level: 'cet4', cat: 'verb' },
    { zh: '赋予', en: 'endow', def: 'to give a quality or ability', level: 'cet6', cat: 'verb' },
    { zh: '剥夺', en: 'deprive', def: 'to take something away from', level: 'cet6', cat: 'verb' },
    { zh: '归还', en: 'return', def: 'to give back to the original owner', level: 'cet4', cat: 'verb' },
    { zh: '征收', en: 'levy', def: 'to impose a tax or fee', level: 'cet6', cat: 'verb' },
    { zh: '收支', en: 'income-expense', def: 'money received and spent', level: 'cet4', cat: 'abstract' },
    { zh: '盈利', en: 'profit', def: 'financial gain after costs', level: 'cet4', cat: 'abstract' },
    { zh: '亏损', en: 'loss', def: 'financial deficit or damage', level: 'cet4', cat: 'abstract' },
    { zh: '资产', en: 'asset', def: 'something valuable owned', level: 'cet4', cat: 'abstract' },
    { zh: '债务', en: 'debt', def: 'money owed to another party', level: 'cet4', cat: 'abstract' },
    { zh: '交易', en: 'transaction', def: 'an exchange of goods or services', level: 'cet4', cat: 'abstract' },
    { zh: '贸易', en: 'trade', def: 'the action of buying and selling', level: 'cet4', cat: 'abstract' },
    { zh: '交换', en: 'exchange', def: 'to give something in return', level: 'cet4', cat: 'verb' },
    { zh: '赚取', en: 'earn', def: 'to receive money for work done', level: 'cet4', cat: 'verb' },
    { zh: '借入', en: 'borrow', def: 'to take with promise of return', level: 'cet4', cat: 'verb' },
    { zh: '借出', en: 'lend', def: 'to give for temporary use', level: 'cet4', cat: 'verb' },
    { zh: '呈现', en: 'present', def: 'to show or display something', level: 'cet4', cat: 'verb' },
    { zh: '暴露', en: 'expose', def: 'to reveal to view or danger', level: 'cet4', cat: 'verb' },
    { zh: '掩盖', en: 'conceal', def: 'to keep something from being seen', level: 'cet4', cat: 'verb' },
    { zh: '隐藏', en: 'hide', def: 'to put out of sight', level: 'cet4', cat: 'verb' },
    { zh: '揭露', en: 'disclose', def: 'to reveal something previously secret', level: 'cet6', cat: 'verb' },
    { zh: '泄露', en: 'leak', def: 'to allow secret info to escape', level: 'cet4', cat: 'verb' },
    { zh: '伪装', en: 'pretend', def: 'to disguise true nature', level: 'cet4', cat: 'verb' },
    { zh: '揭示', en: 'reveal', def: 'to make something known', level: 'cet4', cat: 'verb' },
    { zh: '展示', en: 'showcase', def: 'to display prominently', level: 'cet4', cat: 'verb' },
    { zh: '体现', en: 'embody', def: 'to be an expression of quality', level: 'cet6', cat: 'verb' },
    { zh: '蕴含', en: 'contain', def: 'to include as a part or quality', level: 'cet6', cat: 'verb' },
    { zh: '表象', en: 'appearance', def: 'the way something looks from outside', level: 'cet6', cat: 'abstract' },
    { zh: '迹象', en: 'indication', def: 'a sign suggesting a condition', level: 'cet6', cat: 'abstract' },
    { zh: '痕迹', en: 'trace', def: 'a mark or sign left behind', level: 'cet4', cat: 'abstract' },
    { zh: '踪影', en: 'sign', def: 'any trace or evidence', level: 'cet6', cat: 'abstract' },
    { zh: '暗示', en: 'imply', def: 'to hint or suggest indirectly', level: 'cet4', cat: 'verb' },
    { zh: '象征', en: 'symbolize', def: 'to represent an abstract quality', level: 'cet4', cat: 'verb' },
    { zh: '表明', en: 'demonstrate', def: 'to show clearly with evidence', level: 'cet4', cat: 'verb' },
    { zh: '凸显', en: 'highlight', def: 'to draw attention to', level: 'cet6', cat: 'verb' },
    { zh: '淡化', en: 'downplay', def: 'to make something appear less important', level: 'cet6', cat: 'verb' },
    { zh: '隐约', en: 'faint', def: 'barely perceptible; indistinct', level: 'cet4', cat: 'adj' },
    { zh: '醒目', en: 'striking', def: 'clearly visible and noticeable', level: 'cet6', cat: 'adj' },
    { zh: '透明', en: 'transparent', def: 'allowing light to pass through', level: 'cet4', cat: 'adj' },
    { zh: '隐蔽', en: 'covert', def: 'not openly acknowledged', level: 'cet6', cat: 'adj' },
    { zh: '公开', en: 'public', def: 'openly visible or known', level: 'cet4', cat: 'adj' },
    { zh: '秘密', en: 'secret', def: 'kept hidden from others', level: 'cet4', cat: 'adj' },
    { zh: '隐性', en: 'latent', def: 'hidden; not outwardly visible', level: 'cet6', cat: 'adj' },
    { zh: '成就', en: 'success', def: 'the accomplishment of a goal', level: 'cet4', cat: 'abstract' },
    { zh: '失败', en: 'fail', def: 'to not achieve a desired outcome', level: 'cet4', cat: 'verb' },
    { zh: '获胜', en: 'win', def: 'to be victorious in a contest', level: 'cet4', cat: 'verb' },
    { zh: '取胜', en: 'triumph', def: 'a great victory or achievement', level: 'cet6', cat: 'verb' },
    { zh: '克服', en: 'overcome', def: 'to succeed in dealing with difficulty', level: 'cet4', cat: 'verb' },
    { zh: '击败', en: 'defeat', def: 'to beat an opponent in a contest', level: 'cet4', cat: 'verb' },
    { zh: '挫折', en: 'setback', def: 'a reversal or check in progress', level: 'cet4', cat: 'abstract' },
    { zh: '障碍', en: 'obstacle', def: 'something that blocks the way', level: 'cet4', cat: 'abstract' },
    { zh: '辉煌', en: 'glorious', def: 'marked by great success', level: 'cet6', cat: 'adj' },
    { zh: '跌落', en: 'fall', def: 'to drop from a higher position', level: 'cet6', cat: 'verb' },
    { zh: '崛起', en: 'rise', def: 'to become powerful or successful', level: 'cet6', cat: 'verb' },
    { zh: '衰落', en: 'decline', def: 'to decrease in power or success', level: 'cet6', cat: 'verb' },
    { zh: '兴旺', en: 'prosper', def: 'to flourish or thrive economically', level: 'cet6', cat: 'verb' },
    { zh: '破产', en: 'bankrupt', def: 'unable to pay debts; failed', level: 'cet4', cat: 'adj' },
    { zh: '胜利', en: 'victory', def: 'an act of winning or succeeding', level: 'cet4', cat: 'abstract' },
    { zh: '突破', en: 'breakthrough', def: 'a sudden important development', level: 'cet4', cat: 'abstract' },
    { zh: '尝试', en: 'attempt', def: 'to try to achieve something', level: 'cet4', cat: 'verb' },
    { zh: '达成', en: 'reach', def: 'to achieve a goal or agreement', level: 'cet4', cat: 'verb' },
    { zh: '成效', en: 'effectiveness', def: 'the degree of successful results', level: 'cet6', cat: 'abstract' },
    { zh: '无效', en: 'invalid', def: 'not achieving the intended result', level: 'cet4', cat: 'adj' },
    { zh: '行之有效', en: 'effective', def: 'producing the intended result', level: 'cet4', cat: 'adj' },
    { zh: '徒劳', en: 'futile', def: 'pointless; incapable of success', level: 'cet6', cat: 'adj' },
    { zh: '尾声', en: 'end', def: 'the final part of a process', level: 'cet4', cat: 'abstract' },
    { zh: '开局', en: 'opening', def: 'the first part of something', level: 'cet6', cat: 'abstract' },
    { zh: '栽跟头', en: 'tumble', def: 'to fail or make a mistake', level: 'cet6', cat: 'verb' },
    { zh: '获胜者', en: 'winner', def: 'a person who wins a contest', level: 'cet4', cat: 'daily' },
    { zh: '失败者', en: 'loser', def: 'a person who is defeated', level: 'cet4', cat: 'daily' },
    { zh: '落幕', en: 'conclude', def: 'to bring to an end or close', level: 'cet6', cat: 'verb' },
    { zh: '询问', en: 'inquire', def: 'to ask for information', level: 'cet4', cat: 'verb' },
    { zh: '答复', en: 'reply', def: 'to respond to a question', level: 'cet4', cat: 'verb' },
    { zh: '嘱咐', en: 'instruct', def: 'to tell someone to do something', level: 'cet6', cat: 'verb' },
    { zh: '叮嘱', en: 'urge', def: 'to advise earnestly', level: 'cet6', cat: 'verb' },
    { zh: '恳求', en: 'beg', def: 'to ask earnestly for something', level: 'cet6', cat: 'verb' },
    { zh: '命令', en: 'command', def: 'to give an authoritative order', level: 'cet4', cat: 'verb' },
    { zh: '禁止', en: 'forbid', def: 'to refuse to allow formally', level: 'cet4', cat: 'verb' },
    { zh: '允许', en: 'permit', def: 'to grant authorization to do', level: 'cet4', cat: 'verb' },
    { zh: '强迫', en: 'compel', def: 'to force someone to do something', level: 'cet6', cat: 'verb' },
    { zh: '劝导', en: 'persuade', def: 'to convince someone through reason', level: 'cet6', cat: 'verb' },
    { zh: '警告', en: 'warn', def: 'to inform of possible danger', level: 'cet4', cat: 'verb' },
    { zh: '阻拦', en: 'obstruct', def: 'to block or prevent passage', level: 'cet6', cat: 'verb' },
    { zh: '放任', en: 'allow', def: 'to let something happen freely', level: 'cet4', cat: 'verb' },
    { zh: '忍受', en: 'tolerate', def: 'to endure something unpleasant', level: 'cet4', cat: 'verb' },
    { zh: '反抗', en: 'resist', def: 'to oppose actively', level: 'cet4', cat: 'verb' },
    { zh: '挣扎', en: 'struggle', def: 'to make a strenuous effort', level: 'cet4', cat: 'verb' },
    { zh: '逃亡', en: 'flee', def: 'to run away from danger', level: 'cet6', cat: 'verb' },
    { zh: '追赶', en: 'chase', def: 'to pursue in order to catch', level: 'cet4', cat: 'verb' },
    { zh: '迎接', en: 'welcome', def: 'to greet someone arriving', level: 'cet4', cat: 'verb' },
    { zh: '告别', en: 'say-goodbye', def: 'to take leave from someone', level: 'cet4', cat: 'verb' },
    { zh: '拜访', en: 'visit', def: 'to go and see someone socially', level: 'cet4', cat: 'verb' },
    { zh: '邀请', en: 'invite', def: 'to request the presence of', level: 'cet4', cat: 'verb' },
    { zh: '称呼', en: 'address', def: 'to speak to using a name or title', level: 'cet4', cat: 'verb' },
    { zh: '介绍', en: 'introduce', def: 'to make someone known to another', level: 'cet4', cat: 'verb' },
    { zh: '报告', en: 'report', def: 'to give a spoken or written account', level: 'cet4', cat: 'verb' },
    { zh: '记录', en: 'record', def: 'to set down in writing or other form', level: 'cet4', cat: 'verb' },
    { zh: '登记', en: 'register', def: 'to record in an official list', level: 'cet4', cat: 'verb' },
    { zh: '签署', en: 'sign', def: 'to authorize by signing ones name', level: 'cet4', cat: 'verb' },
    { zh: '盖章', en: 'seal', def: 'to stamp a mark of authentication', level: 'cet4', cat: 'verb' },
    { zh: '核实', en: 'verify', def: 'to confirm the truth or accuracy of', level: 'cet4', cat: 'verb' },
    { zh: '校对', en: 'proofread', def: 'to check text for errors', level: 'cet6', cat: 'verb' },
    { zh: '采纳', en: 'adopt', def: 'to take up a suggestion or plan', level: 'cet4', cat: 'verb' },
    { zh: '废除', en: 'abolish', def: 'to officially put an end to', level: 'cet6', cat: 'verb' },
    { zh: '修建', en: 'build', def: 'to construct by assembling parts', level: 'cet4', cat: 'verb' },
    { zh: '拆除', en: 'demolish', def: 'to pull down a structure', level: 'cet6', cat: 'verb' },
    { zh: '填补', en: 'fill', def: 'to make something full or complete', level: 'cet4', cat: 'verb' },
    { zh: '混合', en: 'mix', def: 'to combine two or more things', level: 'cet4', cat: 'verb' },
    { zh: '分离', en: 'separate', def: 'to move or come apart', level: 'cet4', cat: 'verb' },
    { zh: '捆绑', en: 'bind', def: 'to tie together securely', level: 'cet6', cat: 'verb' },
    { zh: '解开', en: 'unbind', def: 'to undo or release from binding', level: 'cet4', cat: 'verb' },
    { zh: '悬挂', en: 'hang', def: 'to suspend from above', level: 'cet4', cat: 'verb' },
    { zh: '旋转', en: 'rotate', def: 'to move in a circle around a center', level: 'cet4', cat: 'verb' },
    { zh: '倾斜', en: 'tilt', def: 'to lean or incline to one side', level: 'cet6', cat: 'verb' },
    { zh: '弯曲', en: 'bend', def: 'to change shape into a curve', level: 'cet4', cat: 'verb' },
    { zh: '伸展', en: 'stretch', def: 'to extend in length or breadth', level: 'cet6', cat: 'verb' },
    { zh: '压缩', en: 'compress', def: 'to press into a smaller space', level: 'cet4', cat: 'verb' },
    { zh: '扩展', en: 'expand', def: 'to become larger in size or scope', level: 'cet4', cat: 'verb' },
    { zh: '收缩', en: 'shrink', def: 'to contract or become smaller', level: 'cet4', cat: 'verb' },
    { zh: '注入', en: 'inject', def: 'to introduce a substance into', level: 'cet4', cat: 'verb' },
    { zh: '抽取', en: 'extract', def: 'to take or pull out forcibly', level: 'cet4', cat: 'verb' },
    { zh: '倾倒', en: 'pour', def: 'to flow or cause to flow', level: 'cet4', cat: 'verb' },
    { zh: '堆积', en: 'pile', def: 'to place things on top of each other', level: 'cet6', cat: 'verb' },
    { zh: '分散', en: 'disperse', def: 'to spread over a wide area', level: 'cet4', cat: 'verb' },
    { zh: '集中', en: 'concentrate', def: 'to bring together in one place', level: 'cet4', cat: 'verb' },
    { zh: '奔波', en: 'rush', def: 'to move with urgent haste', level: 'cet6', cat: 'verb' },
    { zh: '徘徊', en: 'wander', def: 'to walk about without purpose', level: 'cet6', cat: 'verb' },
    { zh: '跨越', en: 'cross', def: 'to go from one side to another', level: 'cet4', cat: 'verb' },
    { zh: '绕行', en: 'detour', def: 'to go around an obstacle', level: 'cet6', cat: 'verb' },
    { zh: '潜入', en: 'dive', def: 'to plunge headfirst into water', level: 'cet6', cat: 'verb' },
    { zh: '漂浮', en: 'float', def: 'to stay on the surface of liquid', level: 'cet6', cat: 'verb' },
    { zh: '沉没', en: 'sink', def: 'to go down below a surface', level: 'cet6', cat: 'verb' },
    { zh: '碰撞', en: 'collide', def: 'to hit with force when moving', level: 'cet6', cat: 'verb' },
    { zh: '摩擦', en: 'rub', def: 'to move against with pressure', level: 'cet6', cat: 'verb' },
    { zh: '振动', en: 'vibrate', def: 'to move continuously back and forth', level: 'cet6', cat: 'verb' },
    { zh: '闪烁', en: 'flicker', def: 'to shine with a wavering light', level: 'cet6', cat: 'verb' },
    { zh: '弥漫', en: 'permeate', def: 'to spread throughout an area', level: 'cet6', cat: 'verb' },
    { zh: '消散', en: 'dissipate', def: 'to gradually disappear or scatter', level: 'cet6', cat: 'verb' },
    { zh: '凝固', en: 'solidify', def: 'to become solid from liquid', level: 'cet6', cat: 'verb' },
    { zh: '融化', en: 'melt', def: 'to change from solid to liquid', level: 'cet4', cat: 'verb' },
    { zh: '蒸发', en: 'evaporate', def: 'to turn from liquid into vapor', level: 'cet6', cat: 'verb' },
    { zh: '沉淀', en: 'settle', def: 'to sink to the bottom of liquid', level: 'cet6', cat: 'verb' },
    { zh: '污染', en: 'pollute', def: 'to make dirty or impure', level: 'cet4', cat: 'verb' },
    { zh: '净化', en: 'purify', def: 'to remove impurities from', level: 'cet6', cat: 'verb' },
    { zh: '消毒', en: 'disinfect', def: 'to clean by destroying germs', level: 'cet6', cat: 'verb' },
    { zh: '繁殖', en: 'reproduce', def: 'to produce offspring or copies', level: 'cet6', cat: 'verb' },
    { zh: '消耗', en: 'deplete', def: 'to reduce the amount of something', level: 'cet6', cat: 'verb' },
    { zh: '补充', en: 'replenish', def: 'to fill something up again', level: 'cet4', cat: 'verb' },
    { zh: '积累', en: 'accumulate', def: 'to gather over time', level: 'cet4', cat: 'verb' },
    { zh: '释放', en: 'release', def: 'to allow to escape or be free', level: 'cet4', cat: 'verb' },
    { zh: '吸收', en: 'absorb', def: 'to take in or soak up', level: 'cet4', cat: 'verb' },
    { zh: '排除', en: 'exclude', def: 'to keep out or remove', level: 'cet4', cat: 'verb' },
    { zh: '包含', en: 'contain', def: 'to hold or have within', level: 'cet4', cat: 'verb' },
    { zh: '省略', en: 'omit', def: 'to leave out or not include', level: 'cet6', cat: 'verb' },
    { zh: '附加', en: 'attach', def: 'to join as an extra part', level: 'cet4', cat: 'verb' },
    { zh: '嵌入', en: 'embed', def: 'to fix firmly in a surrounding mass', level: 'cet6', cat: 'verb' },
    { zh: '插入', en: 'insert', def: 'to place something into something else', level: 'cet4', cat: 'verb' },
    { zh: '替换', en: 'replace', def: 'to take the place of', level: 'cet4', cat: 'verb' },
    { zh: '合并', en: 'merge', def: 'to combine into a single entity', level: 'cet4', cat: 'verb' },
    { zh: '拆分', en: 'split', def: 'to divide into separate parts', level: 'cet4', cat: 'verb' },
    { zh: '复制', en: 'copy', def: 'to make an identical version of', level: 'cet4', cat: 'verb' },
    { zh: '粘贴', en: 'paste', def: 'to stick something onto a surface', level: 'cet4', cat: 'verb' },
    { zh: '移动', en: 'move', def: 'to change position or location', level: 'cet4', cat: 'verb' },
    { zh: '搬运', en: 'carry', def: 'to transport from one place to another', level: 'cet4', cat: 'verb' },
    { zh: '装载', en: 'load', def: 'to put a load on or into', level: 'cet6', cat: 'verb' },
    { zh: '卸载', en: 'unload', def: 'to remove a load from', level: 'cet6', cat: 'verb' },
    { zh: '包裹', en: 'wrap', def: 'to cover or enclose in paper', level: 'cet4', cat: 'verb' },
    { zh: '展开', en: 'unfold', def: 'to open or spread from a folded state', level: 'cet4', cat: 'verb' },
    { zh: '折叠', en: 'fold', def: 'to bend something over on itself', level: 'cet6', cat: 'verb' },
    { zh: '割裂', en: 'sever', def: 'to cut off or separate forcibly', level: 'cet6', cat: 'verb' },
    { zh: '撕裂', en: 'tear', def: 'to pull apart with force', level: 'cet6', cat: 'verb' },
    { zh: '缝合', en: 'stitch', def: 'to join together with thread', level: 'cet6', cat: 'verb' },
    { zh: '磨损', en: 'wear', def: 'to gradually damage through use', level: 'cet6', cat: 'verb' },
    { zh: '侵蚀', en: 'erode', def: 'to gradually wear away', level: 'cet6', cat: 'verb' },
    { zh: '腐蚀', en: 'corrode', def: 'to gradually destroy by chemical action', level: 'cet6', cat: 'verb' },
    { zh: '生锈', en: 'rust', def: 'to become corroded by oxidation', level: 'cet4', cat: 'verb' },
    { zh: '腐烂', en: 'rot', def: 'to decompose or decay', level: 'cet6', cat: 'verb' },
    { zh: '发酵', en: 'ferment', def: 'to undergo chemical breakdown by yeast', level: 'cet6', cat: 'verb' },
    { zh: '焚烧', en: 'burn', def: 'to destroy by fire', level: 'cet6', cat: 'verb' },
    { zh: '爆炸', en: 'explode', def: 'to burst violently with noise', level: 'cet4', cat: 'verb' },
    { zh: '倒塌', en: 'collapse', def: 'to fall down suddenly', level: 'cet6', cat: 'verb' },
    { zh: '颤抖', en: 'tremble', def: 'to shake involuntarily', level: 'cet6', cat: 'verb' },
    { zh: '抽搐', en: 'twitch', def: 'to make a sudden jerking movement', level: 'cet6', cat: 'verb' },
    { zh: '打哈欠', en: 'yawn', def: 'to open mouth wide involuntarily', level: 'cet4', cat: 'verb' },
    { zh: '咳嗽', en: 'cough', def: 'to expel air from the lungs sharply', level: 'cet4', cat: 'verb' },
    { zh: '打喷嚏', en: 'sneeze', def: 'to expel air through nose involuntarily', level: 'cet4', cat: 'verb' },
    { zh: '呼吸', en: 'breathe', def: 'to take air into the lungs', level: 'cet4', cat: 'verb' },
    { zh: '咀嚼', en: 'chew', def: 'to grind food with the teeth', level: 'cet6', cat: 'verb' },
    { zh: '吞咽', en: 'swallow', def: 'to cause food to pass down the throat', level: 'cet4', cat: 'verb' },
    { zh: '品尝', en: 'taste', def: 'to sample the flavor of something', level: 'cet4', cat: 'verb' },
    { zh: '闻起来', en: 'smell', def: 'to perceive the odor of', level: 'cet4', cat: 'verb' },
    { zh: '触摸', en: 'touch', def: 'to come into physical contact with', level: 'cet4', cat: 'verb' },
    { zh: '倾听', en: 'listen', def: 'to pay attention to sound', level: 'cet4', cat: 'verb' },
    { zh: '注视', en: 'gaze', def: 'to look steadily and intently', level: 'cet6', cat: 'verb' },
    { zh: '凝视', en: 'stare', def: 'to look fixedly at something', level: 'cet6', cat: 'verb' },
    { zh: '扫视', en: 'glance', def: 'to take a brief look at', level: 'cet6', cat: 'verb' },
    { zh: '眨眼', en: 'blink', def: 'to close and open the eyes quickly', level: 'cet4', cat: 'verb' },
    { zh: '皱眉', en: 'frown', def: 'to furrow the brows in displeasure', level: 'cet6', cat: 'verb' },
    { zh: '微笑', en: 'smile', def: 'to form facial expression of pleasure', level: 'cet4', cat: 'verb' },
    { zh: '大笑', en: 'laugh', def: 'to make sounds of amusement', level: 'cet4', cat: 'verb' },
    { zh: '哭泣', en: 'cry', def: 'to shed tears from emotion', level: 'cet4', cat: 'verb' },
    { zh: '尖叫', en: 'scream', def: 'to cry out with a shrill sound', level: 'cet4', cat: 'verb' },
    { zh: '低语', en: 'whisper', def: 'to speak very softly', level: 'cet6', cat: 'verb' },
    { zh: '呼喊', en: 'shout', def: 'to call out loudly', level: 'cet4', cat: 'verb' },
    { zh: '沉默', en: 'silence', def: 'the absence of sound or speech', level: 'cet4', cat: 'abstract' },
    { zh: '喧嚣', en: 'noise', def: 'loud and unpleasant sound', level: 'cet6', cat: 'abstract' },
    { zh: '寂静', en: 'quiet', def: 'free from noise or disturbance', level: 'cet4', cat: 'adj' },
    { zh: '闹腾', en: 'rowdy', def: 'noisy and disorderly', level: 'cet6', cat: 'adj' },
    { zh: '坚硬', en: 'hard', def: 'solid and firm; not soft', level: 'cet4', cat: 'adj' },
    { zh: '光滑', en: 'smooth', def: 'having an even and regular surface', level: 'cet4', cat: 'adj' },
    { zh: '粗糙', en: 'rough', def: 'having an uneven surface', level: 'cet4', cat: 'adj' },
    { zh: '锋利', en: 'sharp', def: 'having a fine edge for cutting', level: 'cet4', cat: 'adj' },
    { zh: '迟钝', en: 'dull', def: 'not sharp; lacking sensitivity', level: 'cet4', cat: 'adj' },
    { zh: '沉重', en: 'heavy', def: 'having great weight or gravity', level: 'cet4', cat: 'adj' },
    { zh: '轻盈', en: 'light', def: 'having little weight; easy to lift', level: 'cet6', cat: 'adj' },
    { zh: '潮湿', en: 'wet', def: 'covered or saturated with liquid', level: 'cet4', cat: 'adj' },
    { zh: '干燥', en: 'dry', def: 'free from moisture or liquid', level: 'cet4', cat: 'adj' },
    { zh: '寒冷', en: 'cold', def: 'of or at a low temperature', level: 'cet4', cat: 'adj' },
    { zh: '炎热', en: 'hot', def: 'having a high temperature', level: 'cet4', cat: 'adj' },
    { zh: '温暖', en: 'warm', def: 'at a fairly high temperature', level: 'cet4', cat: 'adj' },
    { zh: '凉爽', en: 'cool', def: 'pleasantly cold; not warm', level: 'cet4', cat: 'adj' },
    { zh: '明亮', en: 'bright', def: 'giving out or reflecting much light', level: 'cet4', cat: 'adj' },
    { zh: '黑暗', en: 'dark', def: 'with little or no light', level: 'cet4', cat: 'adj' },
    { zh: '拥挤', en: 'crowded', def: 'filled with many people or things', level: 'cet4', cat: 'adj' },
    { zh: '空旷', en: 'spacious', def: 'having plenty of space', level: 'cet6', cat: 'adj' },
    { zh: '干净', en: 'clean', def: 'free from dirt or marks', level: 'cet4', cat: 'adj' },
    { zh: '肮脏', en: 'dirty', def: 'covered or marked with an unclean substance', level: 'cet4', cat: 'adj' },
    { zh: '新鲜', en: 'fresh', def: 'not stale; recently made or obtained', level: 'cet4', cat: 'adj' },
    { zh: '陈旧', en: 'stale', def: 'no longer new or fresh', level: 'cet4', cat: 'adj' },
    { zh: '崭新', en: 'brand-new', def: 'completely new and unused', level: 'cet6', cat: 'adj' },
    { zh: '破旧', en: 'worn', def: 'damaged through use or age', level: 'cet4', cat: 'adj' },
    { zh: '完整', en: 'intact', def: 'not broken or damaged', level: 'cet4', cat: 'adj' },
    { zh: '破碎', en: 'broken', def: 'shattered into pieces', level: 'cet4', cat: 'adj' },
    { zh: '平坦', en: 'flat', def: 'level and even in surface', level: 'cet4', cat: 'adj' },
    { zh: '陡峭', en: 'steep', def: 'rising sharply at an angle', level: 'cet6', cat: 'adj' },
    { zh: '狭窄', en: 'narrow', def: 'of small width in relation to length', level: 'cet4', cat: 'adj' },
    { zh: '宽阔', en: 'wide', def: 'of great extent from side to side', level: 'cet4', cat: 'adj' },
    { zh: '薄薄', en: 'thin', def: 'with opposite surfaces close together', level: 'cet4', cat: 'adj' },
    { zh: '笔直', en: 'straight', def: 'extending in one direction without bending', level: 'cet4', cat: 'adj' },
    { zh: '垂直', en: 'vertical', def: 'at right angles to the horizon', level: 'cet4', cat: 'adj' },
    { zh: '水平', en: 'horizontal', def: 'parallel to the horizon', level: 'cet4', cat: 'adj' },
    { zh: '平行', en: 'parallel', def: 'extending in the same direction', level: 'cet4', cat: 'adj' },
    { zh: '对称', en: 'symmetrical', def: 'balanced in proportions', level: 'cet6', cat: 'adj' },
    { zh: '整齐', en: 'neat', def: 'arranged tidily', level: 'cet4', cat: 'adj' },
    { zh: '凌乱', en: 'messy', def: 'untidy; in a state of disorder', level: 'cet4', cat: 'adj' },
    { zh: '规律', en: 'regular', def: 'arranged in a constant pattern', level: 'cet4', cat: 'adj' },
    { zh: '混乱', en: 'chaotic', def: 'in a state of complete disorder', level: 'cet4', cat: 'adj' },
    { zh: '有序', en: 'orderly', def: 'neatly and methodically arranged', level: 'cet6', cat: 'adj' },
    { zh: '和谐', en: 'harmonious', def: 'forming a pleasing whole', level: 'cet4', cat: 'adj' },
    { zh: '一致', en: 'consistent', def: 'unchanging in nature or effect', level: 'cet4', cat: 'adj' },
    { zh: '分歧', en: 'divergent', def: 'tending to differ or move apart', level: 'cet6', cat: 'adj' },
    { zh: '异常', en: 'abnormal', def: 'deviating from what is normal', level: 'cet4', cat: 'adj' },
    { zh: '典型', en: 'typical', def: 'having the distinctive qualities of a type', level: 'cet4', cat: 'adj' },
    { zh: '独特', en: 'unique', def: 'being the only one of its kind', level: 'cet4', cat: 'adj' },
    { zh: '罕见', en: 'rare', def: 'not common; seldom found', level: 'cet4', cat: 'adj' },
    { zh: '常见', en: 'common', def: 'occurring or found frequently', level: 'cet4', cat: 'adj' },
    { zh: '平凡', en: 'ordinary', def: 'with no distinctive features; normal', level: 'cet4', cat: 'adj' },
    { zh: '非凡', en: 'extraordinary', def: 'very unusual or remarkable', level: 'cet4', cat: 'adj' },
    { zh: '珍贵', en: 'precious', def: 'of great value or worth', level: 'cet4', cat: 'adj' },
    { zh: '廉价', en: 'cheap', def: 'low in price; costing little', level: 'cet4', cat: 'adj' },
    { zh: '昂贵', en: 'expensive', def: 'costing a great deal of money', level: 'cet4', cat: 'adj' },
    { zh: '便利', en: 'convenient', def: 'fitting in well with needs', level: 'cet4', cat: 'adj' },
    { zh: '麻烦', en: 'troublesome', def: 'causing difficulty or annoyance', level: 'cet4', cat: 'adj' },
    { zh: '有趣', en: 'interesting', def: 'arousing curiosity or attention', level: 'cet4', cat: 'adj' },
    { zh: '乏味', en: 'dull', def: 'lacking interest or excitement', level: 'cet6', cat: 'adj' },
    { zh: '刺激', en: 'exciting', def: 'causing great enthusiasm', level: 'cet4', cat: 'adj' },
    { zh: '平淡', en: 'plain', def: 'not exciting; ordinary', level: 'cet4', cat: 'adj' },
    { zh: '剧烈', en: 'violent', def: 'using physical force with great energy', level: 'cet4', cat: 'adj' },
    { zh: '柔和', en: 'gentle', def: 'soft and mild in effect', level: 'cet4', cat: 'adj' },
    { zh: '紧急', en: 'urgent', def: 'requiring immediate action', level: 'cet4', cat: 'adj' },
    { zh: '次要', en: 'secondary', def: 'of less importance than the primary', level: 'cet4', cat: 'adj' },
    { zh: '核心', en: 'core', def: 'the central or most important part', level: 'cet4', cat: 'abstract' },
    { zh: '边缘', en: 'edge', def: 'the outer part or boundary', level: 'cet4', cat: 'abstract' },
    { zh: '内部', en: 'internal', def: 'existing or occurring inside', level: 'cet4', cat: 'adj' },
    { zh: '外部', en: 'external', def: 'belonging to the outside', level: 'cet4', cat: 'adj' },
    { zh: '表面', en: 'surface', def: 'the outside layer of something', level: 'cet4', cat: 'abstract' },
    { zh: '深层', en: 'deep', def: 'far down from the surface', level: 'cet4', cat: 'adj' },
    { zh: '上层', en: 'upper', def: 'higher in position or rank', level: 'cet4', cat: 'adj' },
    { zh: '下层', en: 'lower', def: 'lower in position or rank', level: 'cet4', cat: 'adj' },
    { zh: '顶层', en: 'top', def: 'the highest level or position', level: 'cet4', cat: 'adj' },
    { zh: '底层', en: 'bottom', def: 'the lowest level or position', level: 'cet4', cat: 'adj' },
    { zh: '前方', en: 'front', def: 'the side or part that faces forward', level: 'cet4', cat: 'abstract' },
    { zh: '后方', en: 'rear', def: 'the back part of something', level: 'cet4', cat: 'abstract' },
    { zh: '左侧', en: 'left', def: 'the left-hand side', level: 'cet4', cat: 'daily' },
    { zh: '右侧', en: 'right', def: 'the right-hand side', level: 'cet4', cat: 'daily' },
    { zh: '中心', en: 'center', def: 'the middle point of something', level: 'cet4', cat: 'abstract' },
    { zh: '角落', en: 'corner', def: 'the place where two sides meet', level: 'cet4', cat: 'daily' },
    { zh: '周围', en: 'around', def: 'in the area surrounding something', level: 'cet4', cat: 'adverb' },
    { zh: '附近', en: 'nearby', def: 'close at hand; not far away', level: 'cet4', cat: 'adverb' },
    { zh: '远处', en: 'distant', def: 'far away in space or time', level: 'cet4', cat: 'adj' },
    { zh: '沿途', en: 'along', def: 'on the way; from one point to another', level: 'cet6', cat: 'adverb' },
    { zh: '源头', en: 'source', def: 'the point of origin or beginning', level: 'cet4', cat: 'abstract' },
    { zh: '终点', en: 'destination', def: 'the place to which someone travels', level: 'cet4', cat: 'abstract' },
    { zh: '历程', en: 'journey', def: 'a long and involved process', level: 'cet4', cat: 'abstract' },
  ];
  // Add to global WORD_BANK, avoiding duplicates
  const existingZh = new Set(WORD_BANK.map(w => w.zh));
  for (const w of EXTRA_WORDS) {
    if (!existingZh.has(w.zh)) {
      WORD_BANK.push(w);
      WORD_BANK_MAP.set(w.zh, w);
      existingZh.add(w.zh);
    }
  }
})();
